#!/bin/bash

#echo "temporary disabled since there are no packages available for sketch on kolabsys"
#echo "please enable it manually"
#add kolab repository
#echo "deb http://xi.rename-it.nl/debian/ stable-auto/dovecot-2.2  main" > /etc/apt/sources.list.d/dovecot-2.2.15.list
#echo "deb http://obs.kolabsys.com/repositories/Kolab:/3.3/Debian_8.1/ ./
#deb http://obs.kolabsys.com/repositories/Kolab:/3.3:/Updates/Debian_8.1/ ./
#" > /etc/apt/sources.list.d/kolab-3.3.list
# activate dovecot metadata
sed -i s/#machinet-disabled#//g  /etc/dovecot/conf.d/20-imap.conf
sed -i s/#machinet-disabled#//g  /etc/dovecot/conf.d/10-mail.conf
git clone https://git.kolab.org/diffusion/RPK/roundcubemail-plugins-kolab.git  /tmp/plugins
cp -r /tmp/plugins/plugins /usr/share/roundcubemail
which apt-get
if [ $? == 0 ]; then
echo "debian based system"

apt-get update
apt-get install php-kolabformat
apt-get install php-pear
apt-get install cmake libboost-dev g++ libboost-thread1.67-dev libboost-system1.67-dev libxerces-c-dev xsdcxx libcurl4-openssl-dev swig libpython-dev php-dev
echo "extension=libkolab.so" > /etc/php/7.3/modules-available/libkolab.ini
ln -s /etc/php/7.3/modules-available/libkolab.ini /etc/php/7.3/apache2/conf.d/30-libkolab.ini
fi

which slackpkg
if [ $? == 0 ]; then
echo "slackware system, you are brave :)"
git clone https://git.kolab.org/diffusion/LKX/libkolabxml.git
wget http://mirrors.hostingromania.ro/apache.org//xerces/c/3/sources/xerces-c-3.2.2.tar.xz

fi
pear install HTTP_Request2

git clone https://gitlab.com/roundcube/net_ldap3 /tmp/net_ldap3
cp -R /tmp/net_ldap3/lib/Net/* /usr/share/php/Net/

#mv kolabformat.php /usr/lib/php/
git clone https://git.kolab.org/diffusion/LKX/libkolabxml.git /tmp/libkolabxml
cd /tmp/libkolabxml


./autogen.sh
sed -i.bak 's/-php /-php7 /g' src/php/CMakeLists.txt; \
cd build
 cmake .. -DBUILD_TESTS=FALSE ;  \

make;make install
cp src/libkolab*  /lib/x86_64-linux-gnu/
