<?php
/**
 * Localizations for the Kolab Folders plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_notes/
 */
$labels['navtitle'] = 'Бележки';
$labels['tags'] = 'Етикети';
$labels['notes'] = 'Бележки';
$labels['created'] = 'Създаден';
$labels['changed'] = 'Последна промяна';
$labels['title'] = 'Заглавие';
$labels['listname'] = 'Име';
$labels['tabsharing'] = 'Споделяне';
$labels['foldersubscribe'] = 'Постоянен списък';
$labels['removelist'] = 'Премахни от списъка';
$labels['removelink'] = 'Премахни е-мейл препратките';
$labels['savingdata'] = 'Запазване на данни...';
