<?php
/**
 * Localizations for the Kolab Folders plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_notes/
 */
$labels['navtitle'] = 'Notes';
$labels['tags'] = 'Etiquetes';
$labels['notes'] = 'Notes';
$labels['created'] = 'Creat';
$labels['changed'] = 'Darrera modificació';
$labels['title'] = 'Títol';
$labels['listname'] = 'Nom';
$labels['tabsharing'] = 'Compartit';
$labels['foldersubscribe'] = 'Llista permanentment';
$labels['savingdata'] = 'S\'estan desant les dades...';
