<?php
/**
 * Localizations for the Kolab Folders plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_notes/
 */
$labels['navtitle'] = 'Poznámky';
$labels['tags'] = 'Značky';
$labels['lists'] = 'Zápisníky';
$labels['notes'] = 'Poznámky';
$labels['create'] = 'Nová poznámka';
$labels['createnote'] = 'Vytvořit novou poznámku';
$labels['send'] = 'Poslat';
$labels['sendnote'] = 'Poslat poznámku elektronickou poštou';
$labels['newnote'] = 'Nová poznámka';
$labels['notags'] = 'Žádné značky';
$labels['removetag'] = 'Odstranit značky';
$labels['created'] = 'Vytvořeno';
$labels['changed'] = 'Naposledy změněno';
$labels['title'] = 'Název';
$labels['now'] = 'Nyní';
$labels['sortby'] = 'Třídit dle';
$labels['newnotebook'] = 'Vytvořit nový zápisník';
$labels['addnotebook'] = 'Přidat zápisník';
$labels['editlist'] = 'Upravit zápisník';
$labels['listname'] = 'Název';
$labels['tabsharing'] = 'Sdílení';
$labels['discard'] = 'Zahodit';
$labels['abort'] = 'Zrušit';
$labels['unsavedchanges'] = 'Neuložené změny!';
$labels['appendnote'] = 'Přidat poznámku';
$labels['editnote'] = 'Upravit poznámku';
$labels['savein'] = 'Uložit do';
$labels['foldersubscribe'] = 'Ukazovat seznam trvale';
$labels['findnotebooks'] = 'Najít zápisníky...';
$labels['listsearchresults'] = 'Další zápisníky';
$labels['nrnotebooksfound'] = '$nr zápisníků nalezeno';
$labels['nonotebooksfound'] = 'Nenalezeny žádné zápisníky';
$labels['removelist'] = 'Odstranit ze seznamu';
$labels['removelink'] = 'Odstranit odkaz na e-mail';
$labels['savingdata'] = 'Ukládají se data...';
$labels['recordnotfound'] = 'Záznam nenalezen';
$labels['norecordsfound'] = 'Nenalezeny žádné poznámky';
$labels['nochanges'] = 'Žádné změny k uložení';
$labels['entertitle'] = 'Zadejte, prosím, název této poznámky!';
$labels['deletenotesconfirm'] = 'Opravdu chcete smazat vybrané poznámky?';
$labels['deletenotebookconfirm'] = 'Opravdu chcete smazat tento zápisník se všemi jeho poznámkami? Tento krok nelze vrátit zpět.';
$labels['discardunsavedchanges'] = 'Nynější poznámka nebyla uložena. Zahodit změny?';
$labels['invalidlistproperties'] = 'Neplatné vlastnosti zápisníku! Vložte, prosím, platný název.';
$labels['entertitle'] = 'Zadejte, prosím, název této poznámky!';
$labels['aclnorights'] = 'Nemáte administrátorská práva k tomuto seznamu zápisníku.';
$labels['arialabelnoteslist'] = 'Seznam poznámek';
$labels['arialabelnotesearchform'] = 'Hledání poznámek';
$labels['arialabelnotesquicksearchbox'] = 'Zadání hledání poznámek';
$labels['arialabelnotessortmenu'] = 'Volby pro třídění seznamů poznámek';
$labels['arialabelnotesoptionsmenu'] = 'Nabídka činností pro zápisník';
$labels['arialabelnotebookform'] = 'Vlastnosti zápisníku';
$labels['arialabelmessagereferences'] = 'Odkazované zprávy elektronické pošty';
$labels['arialabelfolderearchform'] = 'Hledání zápisníků';
$labels['arialabelnoteform'] = 'Úprava poznámky';
