<?php
/**
 * Localizations for the Kolab Folders plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_notes/
 */
$labels['navtitle'] = 'Noter';
$labels['tags'] = 'Mærker';
$labels['lists'] = 'Notesbøger';
$labels['notes'] = 'Noter';
$labels['create'] = 'Ny note';
$labels['createnote'] = 'Opret en ny note';
$labels['send'] = 'Send';
$labels['sendnote'] = 'Send note per e-mail';
$labels['newnote'] = 'Ny note';
$labels['notags'] = 'Ingen mærker';
$labels['removetag'] = 'Fjern mærke';
$labels['created'] = 'Oprettet';
$labels['changed'] = 'Senest ændret';
$labels['title'] = 'Titel';
$labels['now'] = 'Nu';
$labels['sortby'] = 'Sortér efter';
$labels['newnotebook'] = 'Opret en ny notesbog';
$labels['addnotebook'] = 'Tilføj notesbog';
$labels['editlist'] = 'Redigér notesbog';
$labels['listname'] = 'Navn';
$labels['tabsharing'] = 'Deling';
$labels['discard'] = 'Forkast';
$labels['abort'] = 'Afbryd';
$labels['unsavedchanges'] = 'Ændringer som ikke er gemt!';
$labels['appendnote'] = 'Tilføj en note';
$labels['editnote'] = 'Redigér note';
$labels['savein'] = 'Gem i';
$labels['foldersubscribe'] = 'Vis bestandigt';
$labels['findnotebooks'] = 'Find notesbøger...';
$labels['listsearchresults'] = 'Ekstra notesbøger';
$labels['nrnotebooksfound'] = '$nr notesbøger blev fundet';
$labels['nonotebooksfound'] = 'Fandt ingen notesbøger';
$labels['removelist'] = 'Fjern fra listen';
$labels['removelink'] = 'Fjern e-mailreference';
$labels['savingdata'] = 'Gemmer data...';
$labels['recordnotfound'] = 'Post blev ikke fundet';
$labels['norecordsfound'] = 'Fandt ingen noter';
$labels['nochanges'] = 'Ingen ændringer til lagring';
$labels['entertitle'] = 'Angiv venligst en titel for denne note!';
$labels['deletenotesconfirm'] = 'Sikker på at du vil slette de valgte noter?';
$labels['deletenotebookconfirm'] = 'Sikker på at du vil slette denne notesbog med alle dens noter? Denne handling kan ikke fortrydes.';
$labels['discardunsavedchanges'] = 'Den aktuelle note er endnu ikke blevet gemt. Skal ændringerne forkastes?';
$labels['invalidlistproperties'] = 'Ugyldige egenskaber for notesbog! Angiv venligst et gyldigt navn.';
$labels['entertitle'] = 'Angiv venligst en titel for denne note!';
$labels['aclnorights'] = 'Du har ikke administratorrettigheder for denne notesbog.';
$labels['arialabelnoteslist'] = 'Liste med noter';
$labels['arialabelnotesearchform'] = 'Søgeformular for noter';
$labels['arialabelnotesquicksearchbox'] = 'Søgeinput for noter';
$labels['arialabelnotessortmenu'] = 'Valgmuligheder for sortering af noteliste';
$labels['arialabelnotesoptionsmenu'] = 'Handlingsmenu for notebog';
$labels['arialabelnotebookform'] = 'Egenskaber for notesbog';
$labels['arialabelmessagereferences'] = 'Sammenkædede e-mailbeskeder';
$labels['arialabelfolderearchform'] = 'Søgeformular for notesbøger';
$labels['arialabelnoteform'] = 'Redigeringsformular for note';
