<?php
/**
 * Localizations for the Kolab Folders plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_notes/
 */
$labels['navtitle'] = 'Notizen';
$labels['tags'] = 'Tags';
$labels['lists'] = 'Notizbücher';
$labels['notes'] = 'Notizen';
$labels['create'] = 'Neue Notiz';
$labels['createnote'] = 'Neue Notiz erstellen';
$labels['send'] = 'Senden';
$labels['sendnote'] = 'Notiz über E-Mail versenden';
$labels['newnote'] = 'Neue Notiz';
$labels['notags'] = 'Keine Schlagworte';
$labels['removetag'] = 'Schlagwort entfernen';
$labels['created'] = 'Erstellt';
$labels['changed'] = 'Geändert';
$labels['title'] = 'Titel';
$labels['now'] = 'Jetzt';
$labels['sortby'] = 'Sortieren nach';
$labels['newnotebook'] = 'Neues Notizbuch erstellen';
$labels['addnotebook'] = 'Notizbuch hinzufügen';
$labels['editlist'] = 'Notizbuch bearbeiten';
$labels['listname'] = 'Name';
$labels['tabsharing'] = 'Freigabe';
$labels['discard'] = 'Verwerfen';
$labels['abort'] = 'Abbrechen';
$labels['unsavedchanges'] = 'Nicht gespeicherte Änderungen!';
$labels['appendnote'] = 'Eine Notiz hinzufügen';
$labels['editnote'] = 'Notiz bearbeiten';
$labels['savein'] = 'Speichern in';
$labels['foldersubscribe'] = 'Permanent anzeigen';
$labels['findnotebooks'] = 'Suche Notizbücher...';
$labels['listsearchresults'] = 'Zusätzliche Notizbücher';
$labels['nrnotebooksfound'] = '$nr Notizbücher gefunden';
$labels['nonotebooksfound'] = 'Keine Notizbücher gefunden';
$labels['removelist'] = 'Von der Liste entfernen';
$labels['removelink'] = 'E-Mail-Referenz entfernen';
$labels['savingdata'] = 'Speichere...';
$labels['recordnotfound'] = 'Eintrag nicht gefunden';
$labels['norecordsfound'] = 'Keine Notizen gefunden';
$labels['nochanges'] = 'Keine Änderungen werden gespeichert';
$labels['entertitle'] = 'Bitte geben Sie einen Titel für diese Notiz ein!';
$labels['deletenotesconfirm'] = 'Willst du wirklich die ausgewählten Notizen löschen?';
$labels['deletenotebookconfirm'] = 'Willst du wirklich die ausgewählten Notizbücher löschen? Diese Aktion kann nicht rückgängig gemacht werden.';
$labels['discardunsavedchanges'] = 'Die aktuelle Notiz wurde noch nicht gespeichert. Die Änderungen verwerfen?';
$labels['invalidlistproperties'] = 'Ungültige Notizbuch Eigenschaften! Bitte gebe einen gültigen Namen ein.';
$labels['entertitle'] = 'Bitte geben Sie einen Titel für diese Notiz ein!';
$labels['aclnorights'] = 'Dir fehlen die Administrationsrechte für dieses Notizbuch.';
$labels['arialabelnoteslist'] = 'Notizliste';
$labels['arialabelnotesearchform'] = 'Notizen-Suchmaske';
$labels['arialabelnotesquicksearchbox'] = 'Notiz-Sucheingabe';
$labels['arialabelnotessortmenu'] = 'Sortieroptionen für Notizen';
$labels['arialabelnotesoptionsmenu'] = 'Notizbuch Aktionsmenü';
$labels['arialabelnotebookform'] = 'Notizbucheigenschaften';
$labels['arialabelmessagereferences'] = 'Verknüpfte E-Mail-Mitteilungen';
$labels['arialabelfolderearchform'] = 'Notizbücher-Suchmaske';
$labels['arialabelnoteform'] = 'Notizbearbeitungsmaske';
