<?php
/**
 * Localizations for the Kolab Folders plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_notes/
 */
$labels['navtitle'] = 'Σημειώσεις';
$labels['tags'] = 'Ετικέτες';
$labels['notes'] = 'Σημειώσεις';
$labels['create'] = 'Νέα σημείωση';
$labels['createnote'] = 'Δημιουργία νέας σημείωσης';
$labels['send'] = 'Αποστολή';
$labels['sendnote'] = 'Αποστολή σημείωσης μέσω ηλ. αλληλογραφίας';
$labels['newnote'] = 'Νέα σημείωση';
$labels['notags'] = 'Καμία ετικέτα';
$labels['removetag'] = 'Αφαίρεση ετικέτας';
$labels['created'] = 'Δημιουργήθηκε';
$labels['changed'] = 'Τελευταία τροποποίηση';
$labels['title'] = 'Τίτλος';
$labels['now'] = 'Τώρα';
$labels['sortby'] = 'Ταξινόμηση κατά';
$labels['listname'] = 'Όνομα';
$labels['removelist'] = 'Αφαίρεση από την λίστα';
$labels['savingdata'] = 'Αποθήκευση δεδομένων...';
