<?php
/**
 * Localizations for the Kolab Folders plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_notes/
 */
$labels['navtitle'] = 'Notas';
$labels['tags'] = 'Etiquetas';
$labels['lists'] = 'Libretas de notas';
$labels['notes'] = 'Notas';
$labels['create'] = 'Nueva Nota';
$labels['createnote'] = 'Crear nueva nota';
$labels['send'] = 'Enviar';
$labels['sendnote'] = 'Enviar nota por email';
$labels['newnote'] = 'Nueva Nota';
$labels['notags'] = 'Sin etiquetas';
$labels['removetag'] = 'Eliminar etiqueta';
$labels['created'] = 'Creado';
$labels['changed'] = 'Última modificación';
$labels['title'] = 'Título';
$labels['now'] = 'Ahora';
$labels['sortby'] = 'Ordenar por';
$labels['newnotebook'] = 'Crear nueva libreta de notas';
$labels['addnotebook'] = 'Agregar libreta de notas';
$labels['editlist'] = 'Editar libreta de notas';
$labels['listname'] = 'Nombre';
$labels['tabsharing'] = 'Compartir';
$labels['discard'] = 'Descartar';
$labels['abort'] = 'Cancelar';
$labels['unsavedchanges'] = '¡Cambios sin guardar!';
$labels['appendnote'] = 'Agregar nota';
$labels['editnote'] = 'Editar nota';
$labels['savein'] = 'Guardar en';
$labels['foldersubscribe'] = 'Listar permanentemente';
$labels['findnotebooks'] = 'Encontrar libretas de notas...';
$labels['listsearchresults'] = 'Libretas de notas adicionales';
$labels['nrnotebooksfound'] = '$nr libretas de notas encontradas';
$labels['nonotebooksfound'] = 'No se encontraron libretas de notas';
$labels['removelist'] = 'Eliminar de la lista';
$labels['removelink'] = 'Eliminar referencia de correo';
$labels['savingdata'] = 'Guardando...';
$labels['recordnotfound'] = 'Registro no encontrado';
$labels['norecordsfound'] = 'No se encontraron notas';
$labels['nochanges'] = 'No hay cambios para guardar';
$labels['entertitle'] = '¡Por favor ingrese un título para esta nota!';
$labels['deletenotesconfirm'] = 'Confirme que desea eliminar la nota seleccionada';
$labels['deletenotebookconfirm'] = 'Confirme que desea eliminar esta libreta de notas con todas sus notas. Esta acción no se puede deshacer.';
$labels['discardunsavedchanges'] = 'La nota actual no ha sido guardada. ¿Descartar los cambios?';
$labels['invalidlistproperties'] = 'Propiedades de la libreta de notas erroneas. Por favor ingrese un nombre válido.';
$labels['entertitle'] = '¡Por favor ingrese un título para esta nota!';
$labels['aclnorights'] = 'No tiene permisos de administrador en esta libreta de notas.';
$labels['arialabelnoteslist'] = 'Lista de notas';
$labels['arialabelnotesearchform'] = 'Formulario de búsqueda de notas';
$labels['arialabelnotesquicksearchbox'] = 'Entrada de búsqueda de notas';
$labels['arialabelnotessortmenu'] = 'Opciones de orden de notas';
$labels['arialabelnotesoptionsmenu'] = 'Menú de acciones de libreta de notas';
$labels['arialabelnotebookform'] = 'Propiedades de libreta de notas';
$labels['arialabelmessagereferences'] = 'Mensajes de email enlazados';
$labels['arialabelfolderearchform'] = 'Formulario de búsqueda de libretas de notas';
$labels['arialabelnoteform'] = 'Formulario de edición de nota';
