<?php
/**
 * Localizations for the Kolab Folders plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_notes/
 */
$labels['navtitle'] = 'Notas';
$labels['tags'] = 'Etiquetas';
$labels['lists'] = 'Libro de notas';
$labels['notes'] = 'Notas';
$labels['create'] = 'Nota nueva';
$labels['createnote'] = 'Crear una nota nueva';
$labels['send'] = 'Enviar';
$labels['sendnote'] = 'Enviar nota por correo electrónico';
$labels['newnote'] = 'Nota nueva';
$labels['notags'] = 'Sin etiquetas';
$labels['removetag'] = 'Eliminar etiqueta';
$labels['created'] = 'Creado';
$labels['changed'] = 'Última modificación';
$labels['title'] = 'Título';
$labels['now'] = 'Ahora';
$labels['sortby'] = 'Ordenar por';
$labels['newnotebook'] = 'Crear una libreta de notas nueva';
$labels['addnotebook'] = 'Añadir libro de notas';
$labels['editlist'] = 'Editar libro de notas';
$labels['listname'] = 'Nombre';
$labels['tabsharing'] = 'Compartir';
$labels['discard'] = 'Descartar';
$labels['abort'] = 'Abortar';
$labels['unsavedchanges'] = 'Cambios sin guardar';
$labels['appendnote'] = 'Añadir una nota';
$labels['editnote'] = 'Editar nota';
$labels['savein'] = 'Guardar en';
$labels['foldersubscribe'] = 'Lista Permanente';
$labels['findnotebooks'] = 'Encontrar libretas de notas...';
$labels['listsearchresults'] = 'Libretas de direcciones adicionales';
$labels['nrnotebooksfound'] = '$nr libreta de notas encontradas';
$labels['nonotebooksfound'] = 'No se han encontrado libretas de notas';
$labels['removelist'] = 'Borrar de la lista';
$labels['removelink'] = 'Eliminar la referencia de correo electrónico';
$labels['savingdata'] = 'Guardando datos...';
$labels['recordnotfound'] = 'Registro no encontrado';
$labels['norecordsfound'] = 'notas no encontradas';
$labels['nochanges'] = 'No se han guardado los cambios';
$labels['entertitle'] = 'Introduzca un título para esta nota';
$labels['deletenotesconfirm'] = '¿Está seguro de querer borrar las notas seleccionadas?';
$labels['deletenotebookconfirm'] = '¿Está seguro de eliminar esta libreta de notas con todas sus notas? Esta acción no puede deshacerse?';
$labels['discardunsavedchanges'] = 'Aún no se ha guardado la nota actual. ¿Descartar cambios?';
$labels['invalidlistproperties'] = 'Las propiedades de la libreta de notas no son válidas. Establezca un nombre válido.';
$labels['entertitle'] = 'Introduzca un título para esta nota';
$labels['aclnorights'] = 'Usted no tiene derechos de administrador en esta libreta de notas.';
$labels['arialabelnoteslist'] = 'Lista de notas';
$labels['arialabelnotesearchform'] = 'Formulario de búsqueda de notas';
$labels['arialabelnotesquicksearchbox'] = 'Entrada de búsqueda de notas';
$labels['arialabelnotessortmenu'] = 'Opciones de clasificación de la lista de notas';
$labels['arialabelnotesoptionsmenu'] = 'Menú de acciones de la lista de notas';
$labels['arialabelnotebookform'] = 'Propiedades de la lista de notas';
$labels['arialabelmessagereferences'] = 'Mensajes de correo electrónico vinculados';
$labels['arialabelfolderearchform'] = 'Formulario de búsqueda de la libreta de notas';
$labels['arialabelnoteform'] = 'Formulario de edición de la nota';
