<?php
/**
 * Localizations for the Kolab Folders plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_notes/
 */
$labels['navtitle'] = 'Muistiot';
$labels['tags'] = 'Tunnisteet';
$labels['notes'] = 'Muistiot';
$labels['removetag'] = 'Poista tunniste';
$labels['created'] = 'Luotu';
$labels['changed'] = 'Viimeksi muokattu';
$labels['title'] = 'Nimi';
$labels['listname'] = 'Nimi';
$labels['tabsharing'] = 'Jakaminen';
$labels['abort'] = 'Keskeytä';
$labels['foldersubscribe'] = 'Luetteloi pysyvästi';
$labels['removelist'] = 'Poista listasta';
$labels['removelink'] = 'Poista sähköpostiviittaus';
$labels['savingdata'] = 'Tallennetaan tietoja...';
