<?php
/**
 * Localizations for the Kolab Folders plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_notes/
 */
$labels['navtitle'] = 'Notes';
$labels['tags'] = 'Étiquettes';
$labels['lists'] = 'Carnets';
$labels['notes'] = 'Notes';
$labels['create'] = 'Nouvelle note';
$labels['createnote'] = 'Créer une nouvelle note';
$labels['send'] = 'Envoyer';
$labels['sendnote'] = 'Envoyer la note par mail';
$labels['newnote'] = 'Nouvelle note';
$labels['notags'] = 'Pas d\'étiquette';
$labels['removetag'] = 'Supprimer l\'étiquette';
$labels['created'] = 'Créé';
$labels['changed'] = 'Dernière modification';
$labels['title'] = 'Titre';
$labels['now'] = 'Maintenant';
$labels['sortby'] = 'Tri par';
$labels['newnotebook'] = 'Créer un nouveau carnet';
$labels['addnotebook'] = 'Ajout carnet';
$labels['editlist'] = 'Modifier le carnet';
$labels['listname'] = 'Nom';
$labels['tabsharing'] = 'Partage';
$labels['discard'] = 'Abandonner';
$labels['abort'] = 'Abandon';
$labels['unsavedchanges'] = 'Modifications non sauvegardées !';
$labels['appendnote'] = 'Ajout d\'une note';
$labels['editnote'] = 'Modifier une note';
$labels['savein'] = 'Enregistrer sous';
$labels['foldersubscribe'] = 'Lister définitivement';
$labels['findnotebooks'] = 'Rechercher carnets...';
$labels['listsearchresults'] = 'Carnets supplémentaires';
$labels['nrnotebooksfound'] = '$nr carnets touvés';
$labels['nonotebooksfound'] = 'Pas de carnet trouvé';
$labels['removelist'] = 'Supprimer de la liste';
$labels['removelink'] = 'Supprimer référence d\'e-mail';
$labels['savingdata'] = 'Enregistrer...';
$labels['recordnotfound'] = 'Enregistrement non trouvé';
$labels['norecordsfound'] = 'Pas de note trouvée';
$labels['nochanges'] = 'Aucun changement à sauvegarder';
$labels['entertitle'] = 'Saisissez un titre pour cette note !';
$labels['deletenotesconfirm'] = 'Voulez-vous vraiment supprimer les notes selectionnées ?';
$labels['deletenotebookconfirm'] = 'Voulez vous vraiment supprimer ce carnet et toutes ses notes ? Cette action est irréversible.';
$labels['discardunsavedchanges'] = 'Cette note n\'a pas été sauvegardée. Voulez-vous abandonner les changements ?';
$labels['invalidlistproperties'] = 'Propriétés du carnet invalide. Saisissez un nom valide.';
$labels['entertitle'] = 'Saisissez un titre pour cette note !';
$labels['aclnorights'] = 'Vous ne disposez pas des droits pour administrer ce carnet.';
$labels['arialabelnoteslist'] = 'Liste des notes';
$labels['arialabelnotesearchform'] = 'Formulaire de recherche de notes';
$labels['arialabelnotesquicksearchbox'] = 'Champ de recherche des notes';
$labels['arialabelnotessortmenu'] = 'Options de tri de la liste de notes';
$labels['arialabelnotesoptionsmenu'] = 'Menu des actions pour un carnet';
$labels['arialabelnotebookform'] = 'Propriétés du carnet';
$labels['arialabelmessagereferences'] = 'Courriels liés';
$labels['arialabelfolderearchform'] = 'Masque de recherche des carnets';
$labels['arialabelnoteform'] = 'Zone d\'édition de note';
