<?php
/**
 * Localizations for the Kolab Folders plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_notes/
 */
$labels['created'] = 'Created';
$labels['changed'] = 'Last Modified';
$labels['listname'] = 'Name';
$labels['tabsharing'] = 'Sharing';
$labels['foldersubscribe'] = 'List permanently';
$labels['removelist'] = 'Remove from list';
$labels['savingdata'] = 'Saving data...';
