<?php
/**
 * Localizations for the Kolab Folders plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_notes/
 */
$labels['navtitle'] = 'ノート';
$labels['tags'] = 'タグ';
$labels['lists'] = 'ノートブック';
$labels['notes'] = 'ノート';
$labels['create'] = '新しいノート';
$labels['createnote'] = '新しいノートの作成';
$labels['send'] = '送信';
$labels['sendnote'] = 'Eメールでノートを送信';
$labels['newnote'] = '新しいノート';
$labels['notags'] = 'タグなし';
$labels['removetag'] = 'タグを削除';
$labels['created'] = '作成済';
$labels['changed'] = '最終変更';
$labels['title'] = 'タイトル';
$labels['now'] = '現在';
$labels['sortby'] = '並び替え';
$labels['newnotebook'] = '新しいノートブックの作成';
$labels['addnotebook'] = 'ノートブックの追加';
$labels['editlist'] = 'ノートブックの編集';
$labels['listname'] = '名前';
$labels['tabsharing'] = '共有';
$labels['discard'] = '捨てる';
$labels['abort'] = '中止';
$labels['unsavedchanges'] = '保存していない変更あり!';
$labels['appendnote'] = 'ノートを追加';
$labels['editnote'] = 'ノートを保存';
$labels['savein'] = '…に保存';
$labels['foldersubscribe'] = '持続的なもののリスト';
$labels['findnotebooks'] = 'ノートブックを探す…';
$labels['listsearchresults'] = '追加のノートブック';
$labels['nrnotebooksfound'] = '$nr 個のノートブックがみつかりました';
$labels['nonotebooksfound'] = 'ノートブックは見つかりませんでした';
$labels['removelist'] = 'リストから削除';
$labels['removelink'] = 'Eメール引用文の削除';
$labels['savingdata'] = 'データを保存中…';
$labels['recordnotfound'] = 'レコードは見つかりませんでした';
$labels['norecordsfound'] = 'ノートは見つかりませんでした';
$labels['nochanges'] = '保存される変更はありません';
$labels['entertitle'] = 'このノートのタイトルを入力してください!';
$labels['deletenotesconfirm'] = '本当に選択したノートを削除しますか?';
$labels['deletenotebookconfirm'] = '本当にすべてのノートとともにこのノートブックを削除しますか?この操作は元に戻せません。';
$labels['discardunsavedchanges'] = '現在のノートはまだ保存されていません。変更を破棄しますか?';
$labels['invalidlistproperties'] = '無効なノートブックのプロパティです!有効な名前を設定してください。';
$labels['entertitle'] = 'このノートのタイトルを入力してください!';
$labels['aclnorights'] = 'このノートブックに対する管理権限がありません。';
$labels['arialabelnoteslist'] = 'ノートのリスト';
$labels['arialabelnotesearchform'] = 'ノート検索フォーム';
$labels['arialabelnotesquicksearchbox'] = 'ノート検索入力';
$labels['arialabelnotessortmenu'] = 'ノートリスト並び替えオプション';
$labels['arialabelnotesoptionsmenu'] = 'ノートブック操作メニュー';
$labels['arialabelnotebookform'] = 'ノートブックプロパティ';
$labels['arialabelmessagereferences'] = 'Eメールメッセージをリンク';
$labels['arialabelfolderearchform'] = 'ノートブック検索フォーム';
$labels['arialabelnoteform'] = 'ノート編集フォーム';
