<?php
/**
 * Localizations for the Kolab Folders plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_notes/
 */
$labels['created'] = 'Izveidots';
$labels['changed'] = 'Mainīts';
$labels['listname'] = 'Nosaukums';
$labels['tabsharing'] = 'Dalīšanās';
$labels['foldersubscribe'] = 'Rādīt sarakstā vienmēr';
$labels['removelist'] = 'Dzēst no saraksta';
$labels['removelink'] = 'Noņemt atsauci uz e-pastu';
$labels['savingdata'] = 'Saglabājam...';
