<?php
/**
 * Localizations for the Kolab Folders plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_notes/
 */
$labels['navtitle'] = 'Notities';
$labels['tags'] = 'Tags';
$labels['lists'] = 'Notitieblokken';
$labels['notes'] = 'Notities';
$labels['create'] = 'Nieuwe notitie';
$labels['createnote'] = 'Nieuwe notitie maken';
$labels['send'] = 'Versturen';
$labels['sendnote'] = 'Notitie versturen per e-mail';
$labels['newnote'] = 'Nieuwe notitie';
$labels['notags'] = 'Geen tags';
$labels['removetag'] = 'Tag verwijderen';
$labels['created'] = 'Gemaakt op';
$labels['changed'] = 'Laatst gewijzigd op';
$labels['title'] = 'Naam';
$labels['now'] = 'Nu';
$labels['sortby'] = 'Sorteren op';
$labels['newnotebook'] = 'Nieuw notitieblok maken';
$labels['addnotebook'] = 'Notitieblok toevoegen';
$labels['editlist'] = 'Notitieblok bewerken';
$labels['listname'] = 'Naam';
$labels['tabsharing'] = 'Delen';
$labels['discard'] = 'Verwijderen';
$labels['abort'] = 'Afbreken';
$labels['unsavedchanges'] = 'Niet-opgeslagen wijzigingen!';
$labels['appendnote'] = 'Notitie toevoegen';
$labels['editnote'] = 'Notitie bewerken';
$labels['savein'] = 'Opslaan in';
$labels['foldersubscribe'] = 'Definitief weergeven';
$labels['findnotebooks'] = 'Notitieblokken zoeken...';
$labels['listsearchresults'] = 'Extra notitieblokken';
$labels['nrnotebooksfound'] = '$nr notitieblokken gevonden';
$labels['nonotebooksfound'] = 'Geen notitieblokken gevonden';
$labels['removelist'] = 'Verwijderen uit lijst';
$labels['removelink'] = 'E-mailreferentie verwijderen';
$labels['savingdata'] = 'Gegevens opslaan...';
$labels['recordnotfound'] = 'Record niet gevonden';
$labels['norecordsfound'] = 'Geen notities gevonden';
$labels['nochanges'] = 'Geen wijzigingen om op te slaan';
$labels['entertitle'] = 'Voer een naam voor deze notitie in!';
$labels['deletenotesconfirm'] = 'Weet u zeker dat u de geselecteerde notities wilt verwijderen?';
$labels['deletenotebookconfirm'] = 'Weet u zeker dat u dit notitieblok met alle notities erin wilt verwijderen? Deze actie kunt u niet ongedaan maken.';
$labels['discardunsavedchanges'] = 'De huidige notitie is nog niet opgeslagen. Wilt u de wijzigingen verwijderen?';
$labels['invalidlistproperties'] = 'Ongeldige eigenschappen van notitieblok! Stel een geldige naam in.';
$labels['entertitle'] = 'Voer een naam voor deze notitie in!';
$labels['aclnorights'] = 'U hebt geen administratorrechten voor dit notitieblok.';
$labels['arialabelnoteslist'] = 'Lijst met notities';
$labels['arialabelnotesearchform'] = 'Zoekformulier voor notities';
$labels['arialabelnotesquicksearchbox'] = 'Zoekopdracht voor notities';
$labels['arialabelnotessortmenu'] = 'Sorteeropties voor lijst met notities';
$labels['arialabelnotesoptionsmenu'] = 'Actiemenu voor notitieblok';
$labels['arialabelnotebookform'] = 'Eigenschappen van notitieblok';
$labels['arialabelmessagereferences'] = 'Gekoppelde e-mailberichten';
$labels['arialabelfolderearchform'] = 'Zoekformulier voor notitieblokken';
$labels['arialabelnoteform'] = 'Formulier voor bewerking van notities';
