<?php
/**
 * Localizations for the Kolab Folders plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_notes/
 */
$labels['tags'] = 'Tagi';
$labels['created'] = 'Utworzone';
$labels['changed'] = 'Ostatnia modyfikacja';
$labels['title'] = 'Tytuł';
$labels['listname'] = 'Nazwa';
$labels['tabsharing'] = 'Udostępnianie';
$labels['foldersubscribe'] = 'Dodaj do listy na stałe';
$labels['removelist'] = 'Usuń z listy';
$labels['removelink'] = 'Usuń odnośnik e-mail';
$labels['savingdata'] = 'Zapisuję dane...';
