<?php
/**
 * Localizations for the Kolab Folders plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_notes/
 */
$labels['tags'] = 'Etiquetas';
$labels['notes'] = 'Notas';
$labels['created'] = 'Criado';
$labels['changed'] = 'Última modificação';
$labels['title'] = 'Título';
$labels['listname'] = 'Nome';
$labels['tabsharing'] = 'Compartilhamento';
$labels['abort'] = 'Abortar';
$labels['foldersubscribe'] = 'Listar permanentemente';
$labels['removelist'] = 'Remover da lista';
$labels['removelink'] = 'Remover referência do email';
$labels['savingdata'] = 'Salvando dados...';
