<?php
/**
 * Localizations for the Kolab Folders plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_notes/
 */
$labels['navtitle'] = 'Заметки';
$labels['tags'] = 'Теги';
$labels['lists'] = 'Записные книжки';
$labels['notes'] = 'Заметки';
$labels['create'] = 'Создать';
$labels['createnote'] = 'Создать новую заметку';
$labels['send'] = 'Отправить';
$labels['sendnote'] = 'Отправить заметку по почте';
$labels['newnote'] = 'Новая заметка';
$labels['notags'] = 'Нет тегов';
$labels['removetag'] = 'Удалить тег';
$labels['created'] = 'Создана';
$labels['changed'] = 'Изменена';
$labels['title'] = 'Заголовок';
$labels['now'] = 'Сейчас';
$labels['sortby'] = 'Сортировать по';
$labels['newnotebook'] = 'Создать новую записную книжку';
$labels['addnotebook'] = 'Добавить записную книжку';
$labels['editlist'] = 'Редактировать записную книжку';
$labels['listname'] = 'Имя';
$labels['tabsharing'] = 'Поделиться';
$labels['discard'] = 'Отказаться';
$labels['abort'] = 'Отменить';
$labels['unsavedchanges'] = 'Несохранённые изменения!';
$labels['appendnote'] = 'Добавить заметку';
$labels['editnote'] = 'Редактировать заметку';
$labels['savein'] = 'Сохранить в';
$labels['foldersubscribe'] = 'Всегда показывать';
$labels['findnotebooks'] = 'Найти записные книжки...';
$labels['listsearchresults'] = 'Дополнительные записные книжки';
$labels['nrnotebooksfound'] = '$nr записных книжек найдено';
$labels['nonotebooksfound'] = 'Записных книжек не найдено';
$labels['removelist'] = 'Удалить из списка';
$labels['removelink'] = 'Удалить ссылку на письмо';
$labels['savingdata'] = 'Сохранение данных...';
$labels['recordnotfound'] = 'Запись не найдена';
$labels['norecordsfound'] = 'Заметок не найдено';
$labels['nochanges'] = 'Сохранять нечего';
$labels['entertitle'] = 'Пожалуйста, укажите заголовок для заметки!';
$labels['deletenotesconfirm'] = 'Вы действительно хотите удалить выбранные заметки?';
$labels['deletenotebookconfirm'] = 'Вы действительно хотите удалить эту записную книжку и все заметки в ней? Это действие невозможно отменить.';
$labels['discardunsavedchanges'] = 'Текущая заметка ещё не была сохранена. Отказаться от изменений?';
$labels['invalidlistproperties'] = 'Неверные параметры записной книжки! Пожалуйста, задайте действительное имя.';
$labels['entertitle'] = 'Пожалуйста, укажите заголовок для заметки!';
$labels['aclnorights'] = 'Вы не имеете прав администратора для этой записной книжки.';
$labels['arialabelnoteslist'] = 'Список заметок';
$labels['arialabelnotesearchform'] = 'Форма поиска заметок';
$labels['arialabelnotesquicksearchbox'] = 'Поиск заметок';
$labels['arialabelnotessortmenu'] = 'Настройки сортировки списка заметок';
$labels['arialabelnotebookform'] = 'Свойства записной книжки';
$labels['arialabelmessagereferences'] = 'Связанные сообщения почты';
$labels['arialabelfolderearchform'] = 'Форма поиска записных книжек';
$labels['arialabelnoteform'] = 'Форма редактирования заметок';
