<?php
/**
 * Localizations for the Kolab Folders plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_notes/
 */
$labels['navtitle'] = 'Zapiski';
$labels['tags'] = 'Tagi';
$labels['lists'] = 'Beležke';
$labels['notes'] = 'Zapiski';
$labels['create'] = 'Nov zapisek';
$labels['createnote'] = 'Ustvari nov zapis';
$labels['send'] = 'Pošlji';
$labels['sendnote'] = 'Pošlji zapisek v emailu';
$labels['newnote'] = 'Nov zapisek';
$labels['notags'] = 'Ni tagov';
$labels['removetag'] = 'Odstrani tag';
$labels['created'] = 'Ustvarjeno';
$labels['changed'] = 'Nazadnje urejeno';
$labels['title'] = 'Naslov';
$labels['now'] = 'Zdaj';
$labels['sortby'] = 'Sortiraj po';
$labels['newnotebook'] = 'Ustvari novo beležko';
$labels['addnotebook'] = 'Dodaj beležko';
$labels['editlist'] = 'Uredi beležko';
$labels['listname'] = 'Ime';
$labels['tabsharing'] = 'Deli z ostalimi';
$labels['discard'] = 'Prekliči';
$labels['abort'] = 'Prekini';
$labels['unsavedchanges'] = 'Neshranjene Spremembe!';
$labels['appendnote'] = 'Dodaj zapisek';
$labels['editnote'] = 'Uredi zapisek';
$labels['savein'] = 'Shrani v';
$labels['foldersubscribe'] = 'Označi za vedno';
$labels['findnotebooks'] = 'Poišči beležke...';
$labels['listsearchresults'] = 'Dodatne beležke';
$labels['nrnotebooksfound'] = '$nr najdenih beležk';
$labels['nonotebooksfound'] = 'Ni najdenih beležk';
$labels['removelist'] = 'Odstrani iz seznama';
$labels['removelink'] = 'Odstrani email povezavo';
$labels['savingdata'] = 'Shranjujem...';
$labels['recordnotfound'] = 'Zapis ni bil najden';
$labels['norecordsfound'] = 'Ni najdenih zapiskov';
$labels['nochanges'] = 'Ni sprememb za shranjevanje';
$labels['entertitle'] = 'Prosim vnesite naslov zapiska!';
$labels['deletenotesconfirm'] = 'Ali želite potrditi brisanje zapiska?';
$labels['deletenotebookconfirm'] = 'Ali želite potrditi brisanje beležke z vsemi zapiski? Izbris je dokončen.';
$labels['discardunsavedchanges'] = 'Trenutni zapisek še ni bil shranjen. Prekličem spremembe?';
$labels['invalidlistproperties'] = 'Napačne nastavitve beležke! Prosim vnesite pravilno ime.';
$labels['entertitle'] = 'Prosim vnesite naslov zapiska!';
$labels['aclnorights'] = 'Nimate administratorskih pravic na tej beležki.';
$labels['arialabelnoteslist'] = 'Seznam zapiskov';
$labels['arialabelnotesearchform'] = 'Obrazec za iskanje zapiskov';
$labels['arialabelnotesquicksearchbox'] = 'Vnos iskanja po zapiskih';
$labels['arialabelnotessortmenu'] = 'Nastavitve za sortiranje zapiskov';
$labels['arialabelnotesoptionsmenu'] = 'Ukazni meni za beležke';
$labels['arialabelnotebookform'] = 'Nastavitve beležke';
$labels['arialabelmessagereferences'] = 'Povezana email sporočila';
$labels['arialabelfolderearchform'] = 'Obrazec za iskanje beležk';
$labels['arialabelnoteform'] = 'Obrazec za urejanje zapiska';
