<?php
/**
 * Localizations for the Kolab Folders plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_notes/
 */
$labels['navtitle'] = 'Anteckningar';
$labels['tags'] = 'Taggar';
$labels['notes'] = 'Anteckningar';
$labels['create'] = 'Ny anteckning';
$labels['createnote'] = 'Skapa ny anteckning';
$labels['send'] = 'Skicka';
$labels['sendnote'] = 'Skicka anteckning med email';
$labels['newnote'] = 'Ny anteckning';
$labels['notags'] = 'Inga taggar';
$labels['removetag'] = 'Ta bort tagg';
$labels['created'] = 'Skapad';
$labels['changed'] = 'Senast ändrad';
$labels['title'] = 'Titel';
$labels['now'] = 'Nu';
$labels['listname'] = 'Namn';
$labels['tabsharing'] = 'Delning';
$labels['foldersubscribe'] = 'Lista permanent';
$labels['removelist'] = 'Ta bort från lista';
$labels['removelink'] = 'Ta bort e-postreferens';
$labels['savingdata'] = 'Sparar data ...';
