<?php
/**
 * Localizations for the Kolab Folders plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_notes/
 */
$labels['navtitle'] = 'สมุดจด';
$labels['tags'] = 'แท็ก';
$labels['lists'] = 'สมุดบันทึก';
$labels['notes'] = 'บันทึก';
$labels['create'] = 'บันทึกใหม่';
$labels['createnote'] = 'สร้างบันทึกใหม่';
$labels['send'] = 'จัดส่ง';
$labels['sendnote'] = 'ส่งบันทึกทางอีเมล์';
$labels['newnote'] = 'สร้างบันทึกใหม่';
$labels['removetag'] = 'ยกเลิกแท็ก';
$labels['created'] = 'สร้างเมื่อ';
$labels['changed'] = 'แก้ไขครั้งสุดท้ายเมื่อ';
$labels['title'] = 'หัวข้อ';
$labels['now'] = 'ขณะนี้';
$labels['sortby'] = 'จัดเรียงโดย';
$labels['newnotebook'] = 'สร้างสมุดบันทึกใหม่';
$labels['addnotebook'] = 'เพิ่่มสมุดบันทึก';
$labels['editlist'] = 'แก้ไขสมุดบันทึก';
$labels['listname'] = 'ชื่อ';
$labels['tabsharing'] = 'แบ่งปัน';
$labels['discard'] = 'โยนทิ้ง';
$labels['abort'] = 'ยกเลิก';
$labels['unsavedchanges'] = 'การเปลี่ยนที่ยังไม่รับรับการบันทึก';
$labels['appendnote'] = 'เพิ่มบันทึก';
$labels['editnote'] = 'แก้ไขบันทึก';
$labels['savein'] = 'จัดเก็บใน';
$labels['foldersubscribe'] = 'แสดงเป็นรายการถาวร';
$labels['findnotebooks'] = 'ค้นหาสมุดบันทึก...';
$labels['listsearchresults'] = 'สมุดบันทึกเพิ่มเติม';
$labels['nrnotebooksfound'] = 'พบสมุดบันทึก $nr เล่ม';
$labels['nonotebooksfound'] = 'ไม่พบสมุดบันทึก';
$labels['removelist'] = 'ลบออกจากรายการ';
$labels['savingdata'] = 'กำลังจัดเก็บข้อมูล...';
$labels['recordnotfound'] = 'ไม่พบข้อมูล';
$labels['norecordsfound'] = 'ไม่พบบันทึกข้อความ';
$labels['nochanges'] = 'ไม่มีการเปลี่ยนแปลงให้บันทึก';
$labels['entertitle'] = 'โปรดป้อนหัวข้อสำหรับบันทึกฉบับนี้';
$labels['deletenotesconfirm'] = 'คุณต้องการลบบันทีกที่เลือกนี้จริง ๆ หรือ';
$labels['deletenotebookconfirm'] = 'คุณต้องการลบสมุดบันทึกพร้อมบันทึกทั้งหมดหรือ การทำครั้งนี้จะไม่สามารถกู้คืนได้';
$labels['discardunsavedchanges'] = 'บันทึกแผ่นนี้ยังไม่ถูกจัดเก็บ ยกเลิกการเปลี่ยนแปลง';
$labels['invalidlistproperties'] = 'คุณสมบัติของสมุดบันทึกไม่ถูกต้อง  โปรดตั้งชื่อให้ถูกต้อง';
$labels['entertitle'] = 'โปรดป้อนหัวข้อสำหรับบันทึกฉบับนี้';
$labels['aclnorights'] = 'คุณไม่มีสิทธของผู้ดูแลระบบสำหรับสมุดบันทึกเล่มนี้';
$labels['arialabelnoteslist'] = 'รายการบันทึก';
$labels['arialabelnotesearchform'] = 'ฟอร์มการค้นหาบันทึก';
$labels['arialabelnotesquicksearchbox'] = 'ข้อมูลสำหรับค้นหาบันทึก';
$labels['arialabelnotessortmenu'] = 'ทางเลือกการจัดเรียงบันทึก';
$labels['arialabelnotebookform'] = 'คุณสมบัติของสมุดบันทึก';
$labels['arialabelmessagereferences'] = 'ข้อความอีเมล์ที่เชื่อมต่อ';
$labels['arialabelfolderearchform'] = 'ฟอร์มการค้นหาสมุดบันทึก';
$labels['arialabelnoteform'] = 'ฟอร์มการแก้ไขบันทึก';
