<?php
/**
 * Localizations for the Kolab Folders plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_notes/
 */
$labels['navtitle'] = 'Нотатки';
$labels['notes'] = 'Нотатки';
$labels['created'] = 'Створена';
$labels['changed'] = 'Змінена';
$labels['listname'] = 'Назва';
$labels['tabsharing'] = 'Спільне використання';
$labels['foldersubscribe'] = 'Завжди показувати';
$labels['removelist'] = 'Вилучити зі списку';
$labels['savingdata'] = 'Збереження даних...';
