<?php
/**
 * Localizations for the Kolab Folders plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_notes/
 */
$labels['navtitle'] = '笔记';
$labels['tags'] = '标签';
$labels['lists'] = '笔记本';
$labels['notes'] = '笔记';
$labels['create'] = '新笔记';
$labels['createnote'] = '新建备忘录';
$labels['send'] = '发送';
$labels['sendnote'] = '通过邮件发送备忘录';
$labels['newnote'] = '新备忘录';
$labels['notags'] = '无标签';
$labels['removetag'] = '移除标签';
$labels['created'] = '已创建';
$labels['changed'] = '最后更改';
$labels['title'] = '标题';
$labels['now'] = '现在';
$labels['sortby'] = '按此排序';
$labels['newnotebook'] = '创建新笔记本';
$labels['addnotebook'] = '增加笔记本';
$labels['editlist'] = '编辑笔记本';
$labels['listname'] = '名称';
$labels['tabsharing'] = '分享';
$labels['discard'] = '放弃';
$labels['abort'] = '退出';
$labels['unsavedchanges'] = '更改未保存';
$labels['appendnote'] = '增加新笔记';
$labels['editnote'] = '编辑笔记';
$labels['savein'] = '保存为';
$labels['nonotebooksfound'] = '未发现笔记本';
$labels['removelist'] = '从列表中移除';
$labels['savingdata'] = '保存数据...';
$labels['recordnotfound'] = '未找到记录';
$labels['norecordsfound'] = '未找到笔记';
$labels['nochanges'] = '未更改内容';
$labels['entertitle'] = '请为此笔记输入标题';
$labels['deletenotesconfirm'] = '是否删除所选笔记？';
$labels['deletenotebookconfirm'] = '是否删除所选笔记下的所有记录？此步骤无法恢复。';
$labels['discardunsavedchanges'] = '当前笔记未保存。是否放弃更改？';
$labels['invalidlistproperties'] = '无效的笔记本属性！请输入一个有效的名称。';
$labels['entertitle'] = '请为此笔记输入标题';
$labels['aclnorights'] = '您无此笔记本的管理权限。';
$labels['arialabelnoteslist'] = '列出笔记';
$labels['arialabelnotebookform'] = '笔记本属性';
