<?php
/**
 * Localizations for the Kolab Folders plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_folders/
 */
$labels['folderctype'] = 'Тип на съдържанието';
$labels['foldertypemail'] = 'Поща';
$labels['foldertypeevent'] = 'Календар';
$labels['foldertypejournal'] = 'Дневник';
$labels['foldertypetask'] = 'Задачи';
$labels['foldertypenote'] = 'Бележки';
$labels['foldertypecontact'] = 'Контакти';
$labels['foldertypeconfiguration'] = 'Конфигурация';
$labels['foldertypefile'] = 'Файлове';
$labels['default'] = 'По подразбиране';
$labels['inbox'] = 'Вх. поща';
$labels['drafts'] = 'Чернови';
$labels['sentitems'] = 'Изпратени';
$labels['outbox'] = 'Изходящи';
$labels['wastebasket'] = 'Кошче';
$labels['junkemail'] = 'Нежелани';
$messages['defaultfolderexists'] = 'Вече има папка по подразбиране за въпросният тип';
?>
