<?php
/**
 * Localizations for the Kolab Folders plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_folders/
 */
$labels['folderctype'] = 'Typ obsahu';
$labels['foldertypemail'] = 'Pošta';
$labels['foldertypeevent'] = 'Kalendář';
$labels['foldertypejournal'] = 'Deník';
$labels['foldertypetask'] = 'Úkoly';
$labels['foldertypenote'] = 'Poznámky';
$labels['foldertypecontact'] = 'Spojení';
$labels['foldertypeconfiguration'] = 'Nastavení';
$labels['foldertypefile'] = 'Soubory';
$labels['foldertypefreebusy'] = 'Volný/Zaneprázdněný';
$labels['default'] = 'Výchozí';
$labels['inbox'] = 'Doručená pošta';
$labels['drafts'] = 'Návrhy';
$labels['sentitems'] = 'Posláno';
$labels['outbox'] = 'Odeslaná pošta';
$labels['wastebasket'] = 'Koš';
$labels['junkemail'] = 'Nevyžádaná pošta';
$labels['confidential'] = 'Důvěrné';
$labels['private'] = 'Soukromé';
$messages['defaultfolderexists'] = 'Již je výchozí složka daného typu';
?>
