<?php
/**
 * Localizations for the Kolab Folders plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_folders/
 */
$labels['folderctype'] = 'Indholdstype';
$labels['foldertypemail'] = 'Post';
$labels['foldertypeevent'] = 'Kalender';
$labels['foldertypejournal'] = 'Journal';
$labels['foldertypetask'] = 'Opgaver';
$labels['foldertypenote'] = 'Noter';
$labels['foldertypecontact'] = 'Kontakter';
$labels['foldertypeconfiguration'] = 'Konfiguration';
$labels['foldertypefile'] = 'Filer';
$labels['foldertypefreebusy'] = 'Ledig-optaget';
$labels['default'] = 'Standard';
$labels['inbox'] = 'Indbakke';
$labels['drafts'] = 'Kladder';
$labels['sentitems'] = 'Sendt';
$labels['outbox'] = 'Udbakke';
$labels['wastebasket'] = 'Papirkurv';
$labels['junkemail'] = 'Uønsket';
$labels['confidential'] = 'Confidential';
$labels['private'] = 'Privat';
$messages['defaultfolderexists'] = 'Der er allerede en standardmapper med angive type';
?>
