<?php
/**
 * Localizations for the Kolab Folders plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_folders/
 */
$labels['foldertypemail'] = 'Αλληλογραφία';
$labels['foldertypeevent'] = 'Ημερολόγιο';
$labels['foldertypetask'] = 'Εργασίες';
$labels['foldertypenote'] = 'Σημειώσεις';
$labels['foldertypecontact'] = 'Επαφές';
$labels['foldertypeconfiguration'] = 'Ρυθμίσεις';
$labels['foldertypefile'] = 'Αρχεία';
$labels['default'] = 'Προεπιλογή';
$labels['inbox'] = 'Εισερχόμενα';
$labels['drafts'] = 'Πρόχειρα';
$labels['outbox'] = 'Εξερχόμενα';
$labels['wastebasket'] = 'Κάδος απορριμάτων';
$labels['confidential'] = 'Εμπιστευτικό';
$labels['private'] = 'Ιδιωτικό';
?>
