<?php
/**
 * Localizations for the Kolab Folders plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_folders/
 */
$labels['folderctype'] = 'Tipo de contenido';
$labels['foldertypemail'] = 'Correo';
$labels['foldertypeevent'] = 'Calendario';
$labels['foldertypejournal'] = 'Diario';
$labels['foldertypetask'] = 'Tareas';
$labels['foldertypenote'] = 'Notas';
$labels['foldertypecontact'] = 'Contactos';
$labels['foldertypeconfiguration'] = 'Configuración';
$labels['foldertypefile'] = 'Archivos';
$labels['foldertypefreebusy'] = 'Libre-Ocupado';
$labels['default'] = 'Predeterminado';
$labels['inbox'] = 'Bandeja de entrada';
$labels['drafts'] = 'Borradores';
$labels['sentitems'] = 'Enviado';
$labels['outbox'] = 'Bandeja de salida';
$labels['wastebasket'] = 'Papelera';
$labels['junkemail'] = 'Basura';
$labels['confidential'] = 'Confidential';
$labels['private'] = 'Privado';
$messages['defaultfolderexists'] = 'Ya existe una carpeta predeterminada del tipo especificado';
?>
