<?php
/**
 * Localizations for the Kolab Folders plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_folders/
 */
$labels['folderctype'] = 'Content type';
$labels['foldertypemail'] = 'Mail';
$labels['foldertypeevent'] = 'Calendar';
$labels['foldertypejournal'] = 'Journal';
$labels['foldertypetask'] = 'Tareas';
$labels['foldertypenote'] = 'Notas';
$labels['foldertypecontact'] = 'Contactos';
$labels['foldertypeconfiguration'] = 'Configuración';
$labels['foldertypefile'] = 'Files';
$labels['foldertypefreebusy'] = 'Free-Busy';
$labels['default'] = 'Default';
$labels['inbox'] = 'Inbox';
$labels['drafts'] = 'Drafts';
$labels['sentitems'] = 'Sent';
$labels['outbox'] = 'Outbox';
$labels['wastebasket'] = 'Trash';
$labels['junkemail'] = 'Junk';
$labels['confidential'] = 'Confidential';
$labels['private'] = 'Privado';
$messages['defaultfolderexists'] = 'There is already default folder of specified type';
?>
