<?php
/**
 * Localizations for the Kolab Folders plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_folders/
 */
$labels['folderctype'] = 'Sisältötyyppi';
$labels['foldertypemail'] = 'Sähköposti';
$labels['foldertypeevent'] = 'Kalenteri';
$labels['foldertypejournal'] = 'Päiväkirja';
$labels['foldertypetask'] = 'Tehtävät';
$labels['foldertypenote'] = 'Muistiot';
$labels['foldertypecontact'] = 'Yhteystiedot';
$labels['foldertypeconfiguration'] = 'Asetukset';
$labels['foldertypefile'] = 'Tiedostot';
$labels['foldertypefreebusy'] = 'Vapaa-varattu';
$labels['default'] = 'Oletus';
$labels['inbox'] = 'Saapuneet';
$labels['drafts'] = 'Luonnokset';
$labels['sentitems'] = 'Lähetetyt';
$labels['outbox'] = 'Lähtevät';
$labels['wastebasket'] = 'Roskakori';
$labels['junkemail'] = 'Roskaposti';
$labels['confidential'] = 'Luottamuksellinen';
$labels['private'] = 'Yksityinen';
$messages['defaultfolderexists'] = 'Määritetylle tyypille on jo olemassa oletuskansio';
?>
