<?php
/**
 * Localizations for the Kolab Folders plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_folders/
 */
$labels['folderctype'] = 'Type de contenu';
$labels['foldertypemail'] = 'Courriel';
$labels['foldertypeevent'] = 'Calendrier';
$labels['foldertypejournal'] = 'Journal';
$labels['foldertypetask'] = 'Tâches';
$labels['foldertypenote'] = 'Notes';
$labels['foldertypecontact'] = 'Contacts';
$labels['foldertypeconfiguration'] = 'Configuration';
$labels['foldertypefile'] = 'Fichiers';
$labels['foldertypefreebusy'] = 'Disponible/Occupé';
$labels['default'] = 'Par défaut';
$labels['inbox'] = 'Courrier entrant';
$labels['drafts'] = 'Brouillons';
$labels['sentitems'] = 'Envoyés';
$labels['outbox'] = 'Courrier sortant';
$labels['wastebasket'] = 'Corbeille';
$labels['junkemail'] = 'Indésirables';
$labels['confidential'] = 'Confidentiel';
$labels['private'] = 'Privé';
$messages['defaultfolderexists'] = 'Il existe déjà un répertoire par défaut pour le type spécifié';
?>
