<?php
/**
 * Localizations for the Kolab Folders plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_folders/
 */
$labels['folderctype'] = 'Tartalom típusa';
$labels['foldertypemail'] = 'Levelezés';
$labels['foldertypeevent'] = 'Naptár';
$labels['foldertypejournal'] = 'Journal';
$labels['foldertypetask'] = 'Feladatok';
$labels['foldertypenote'] = 'Jegyzetek';
$labels['foldertypecontact'] = 'Kapcsolatok';
$labels['foldertypeconfiguration'] = 'Beállítások';
$labels['foldertypefile'] = 'Fájlok';
$labels['foldertypefreebusy'] = 'Foglaltság';
$labels['default'] = 'Alapértelmezett';
$labels['inbox'] = 'Beérkezők';
$labels['drafts'] = 'Piszkozatok';
$labels['sentitems'] = 'Elküldöttek';
$labels['outbox'] = 'Kimenő';
$labels['wastebasket'] = 'Kuka';
$labels['junkemail'] = 'Kéretlenek';
$labels['confidential'] = 'Confidential';
$messages['defaultfolderexists'] = 'Már van megadva egy alapértelmezett mappa ehhez a típushoz';
?>
