<?php
/**
 * Localizations for the Kolab Folders plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_folders/
 */
$labels['folderctype'] = 'Tipo di contenuto';
$labels['foldertypemail'] = 'Mail';
$labels['foldertypeevent'] = 'Calendario';
$labels['foldertypejournal'] = 'Diario';
$labels['foldertypetask'] = 'Attività';
$labels['foldertypenote'] = 'Annotazioni';
$labels['foldertypecontact'] = 'Contatti';
$labels['foldertypeconfiguration'] = 'Configurazione';
$labels['foldertypefile'] = 'File';
$labels['foldertypefreebusy'] = 'Libero-Occupato';
$labels['default'] = 'Predefinito';
$labels['inbox'] = 'Posta In arrivo';
$labels['drafts'] = 'Bozze';
$labels['sentitems'] = 'Posta inviata';
$labels['outbox'] = 'In uscita';
$labels['wastebasket'] = 'Cestino';
$labels['junkemail'] = 'Posta indesiderata';
$labels['confidential'] = 'Riservato';
$messages['defaultfolderexists'] = 'Esiste già una cartella predefinita del tipo specificato';
?>
