<?php
/**
 * Localizations for the Kolab Folders plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_folders/
 */
$labels['folderctype'] = 'Inhoudstype';
$labels['foldertypemail'] = 'Mail';
$labels['foldertypeevent'] = 'Agenda';
$labels['foldertypejournal'] = 'Dagboek';
$labels['foldertypetask'] = 'Taken';
$labels['foldertypenote'] = 'Notities';
$labels['foldertypecontact'] = 'Contactpersonen';
$labels['foldertypeconfiguration'] = 'Configuratie';
$labels['foldertypefile'] = 'Bestanden';
$labels['foldertypefreebusy'] = 'Beschikbaar/Bezet';
$labels['default'] = 'Standaard';
$labels['inbox'] = 'Postvak IN';
$labels['drafts'] = 'Concepten';
$labels['sentitems'] = 'Verstuurd';
$labels['outbox'] = 'Postvak UIT';
$labels['wastebasket'] = 'Prullenbak';
$labels['junkemail'] = 'Ongewenst';
$labels['confidential'] = 'Vertrouwelijk';
$labels['private'] = 'Privé';
$messages['defaultfolderexists'] = 'Er is al een standaardmap van het opgegeven type';
?>
