<?php
/**
 * Localizations for the Kolab Folders plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_folders/
 */
$labels['folderctype'] = 'Tipo de conteúdo';
$labels['foldertypemail'] = 'Correio';
$labels['foldertypeevent'] = 'Calendário';
$labels['foldertypejournal'] = 'Journal';
$labels['foldertypetask'] = 'Tarefas';
$labels['foldertypenote'] = 'Notas';
$labels['foldertypecontact'] = 'Contatos';
$labels['foldertypeconfiguration'] = 'Configuração';
$labels['foldertypefile'] = 'Arquivos';
$labels['foldertypefreebusy'] = 'Livre-ocupado';
$labels['default'] = 'Padrão';
$labels['inbox'] = 'Caixa de entrada';
$labels['drafts'] = 'Rascunhos';
$labels['sentitems'] = 'Enviados';
$labels['outbox'] = 'Caixa de saída';
$labels['wastebasket'] = 'Lixeira';
$labels['junkemail'] = 'Spam';
$messages['defaultfolderexists'] = 'Já existe um diretório padrão do tipo especificado';
?>
