<?php
/**
 * Localizations for the Kolab Folders plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_folders/
 */
$labels['foldertypeevent'] = 'Calendário';
$labels['foldertypetask'] = 'Tarefas';
$labels['foldertypenote'] = 'Notas';
$labels['foldertypeconfiguration'] = 'Configuração';
$labels['foldertypefile'] = 'Ficheiros';
?>
