<?php
/**
 * Localizations for the Kolab Folders plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_folders/
 */
$labels['folderctype'] = 'Тип ящика';
$labels['foldertypemail'] = 'Почта';
$labels['foldertypeevent'] = 'Календарь';
$labels['foldertypejournal'] = 'Журнал';
$labels['foldertypetask'] = 'Задачи';
$labels['foldertypenote'] = 'Заметки';
$labels['foldertypecontact'] = 'Контакты';
$labels['foldertypeconfiguration'] = 'Настройки';
$labels['foldertypefile'] = 'Файлы';
$labels['foldertypefreebusy'] = 'Занят/Свободен';
$labels['default'] = 'По умолчанию';
$labels['inbox'] = 'Входящие';
$labels['drafts'] = 'Черновики';
$labels['sentitems'] = 'Отправленные';
$labels['outbox'] = 'Исходящие';
$labels['wastebasket'] = 'Корзина';
$labels['junkemail'] = 'Спам';
$labels['confidential'] = 'Конфиденциальное';
$labels['private'] = 'Личное';
$messages['defaultfolderexists'] = 'Уже назначен ящик по умолчанию для указанного типа';
?>
