<?php
/**
 * Localizations for the Kolab Folders plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_folders/
 */
$labels['folderctype'] = 'Vrsta vsebine';
$labels['foldertypemail'] = 'Pošta';
$labels['foldertypeevent'] = 'Koledar';
$labels['foldertypejournal'] = 'Dnevnik';
$labels['foldertypetask'] = 'Naloge';
$labels['foldertypenote'] = 'Zapiski';
$labels['foldertypecontact'] = 'Kontakti';
$labels['foldertypeconfiguration'] = 'Nastavitve';
$labels['foldertypefile'] = 'Dokumenti';
$labels['foldertypefreebusy'] = 'Prost-Zaseden';
$labels['default'] = 'Privzet';
$labels['inbox'] = 'Dohodna pošta';
$labels['drafts'] = 'Osnutki';
$labels['sentitems'] = 'Poslano';
$labels['outbox'] = 'Izhodna pošta';
$labels['wastebasket'] = 'Koš';
$labels['junkemail'] = 'Smeti';
$labels['confidential'] = 'Zaupno';
$messages['defaultfolderexists'] = 'Privzeta mapa izbranega tipa že obstaja';
?>
