<?php
/**
 * Localizations for the Kolab Folders plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_folders/
 */
$labels['folderctype'] = 'Innehållstyp';
$labels['foldertypemail'] = 'E-post';
$labels['foldertypeevent'] = 'Kalender';
$labels['foldertypejournal'] = 'Journal';
$labels['foldertypetask'] = 'Uppgifter';
$labels['foldertypenote'] = 'Anteckningar';
$labels['foldertypecontact'] = 'Kontakter';
$labels['foldertypeconfiguration'] = 'Konfiguration';
$labels['foldertypefile'] = 'Filer';
$labels['foldertypefreebusy'] = 'Ledig-upptagen';
$labels['default'] = 'Standard';
$labels['inbox'] = 'Inkorg';
$labels['drafts'] = 'Utkast';
$labels['sentitems'] = 'Skickat';
$labels['outbox'] = 'Utkorg';
$labels['wastebasket'] = 'Papperskorg';
$labels['junkemail'] = 'Skräp';
$labels['confidential'] = 'Konfidentiellt';
$messages['defaultfolderexists'] = 'Det finns redan en standardmapp för specificerad typ';
?>
