<?php
/**
 * Localizations for the Kolab Folders plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_folders/
 */
$labels['folderctype'] = 'ชนิดของเนื่้อหา';
$labels['foldertypemail'] = 'จดหมาย';
$labels['foldertypeevent'] = 'ปฎิทิน';
$labels['foldertypetask'] = 'งาน';
$labels['foldertypenote'] = 'บันทึก';
$labels['foldertypecontact'] = 'รายชื้อผู้ติดต่อ';
$labels['foldertypeconfiguration'] = 'ค่าคุณสมบัติ';
$labels['foldertypefile'] = 'ไฟล์';
$labels['foldertypefreebusy'] = 'ว่าง-ติดธุระ';
$labels['default'] = 'ค่าเริ่มต้น';
$labels['inbox'] = 'กล่องขาเข้า';
$labels['drafts'] = 'จดหมายร่าง';
$labels['sentitems'] = 'จัดส่งแล้ว';
$labels['outbox'] = 'กล่องขาออก';
$labels['wastebasket'] = 'ถ้งขยะ';
$labels['junkemail'] = 'ขยะ';
$labels['confidential'] = 'ลับเฉพาะ';
$messages['defaultfolderexists'] = 'มีแฟ้มสำหรับเก็บข้อมูลขนิดดังกล่าวแล้ว';
?>
