<?php
/**
 * Localizations for the Kolab Files plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_files/
 */
$labels['files'] = 'Файлове';
$labels['save'] = 'Запис';
$labels['cancel'] = 'Отказ';
$labels['folderinside'] = 'Внасяне вътре';
$labels['name'] = 'Име';
$labels['edit'] = 'Промяна';
$labels['save'] = 'Запис';
$labels['listpermanent'] = 'Постоянен списък';
$labels['select'] = 'Избиране';
$labels['participant'] = 'Участник';
$labels['status'] = 'Статус';
$labels['addparticipant'] = 'Добавяне на участник';
$labels['invitationtextlabel'] = 'Invitation/notification comment';
$labels['statusorganizer'] = 'Организатор';
$labels['removeparticipant'] = 'Изтриване';
$labels['accept'] = 'Приемане';
$labels['decline'] = 'Отхвърляне';
$labels['owner'] = 'Собственик';
$labels['comment'] = 'Коментар';
