<?php
/**
 * Localizations for the Kolab Files plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_files/
 */
$labels['save'] = 'Desa';
$labels['cancel'] = 'Cancel·la';
$labels['folderinside'] = 'Insereix dins';
$labels['name'] = 'Nom';
$labels['edit'] = 'Edita';
$labels['save'] = 'Desa';
$labels['listpermanent'] = 'Llista permanentment';
$labels['select'] = 'Selecciona';
$labels['participant'] = 'Participant';
$labels['status'] = 'Estat';
$labels['addparticipant'] = 'Afegeix participant';
$labels['invitationtextlabel'] = 'Comentari de la invitació/notificació';
$labels['statusorganizer'] = 'Organitzador';
$labels['removeparticipant'] = 'Suprimeix';
$labels['owner'] = 'Propietari';
$labels['comment'] = 'Comentari';
