<?php
/**
 * Localizations for the Kolab Files plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_files/
 */
$labels['files'] = 'Αρχεία';
$labels['filepreview'] = 'Προεπισκόπηση αρχείου';
$labels['saveall'] = 'Αποθήκευση όλων στο cloud...';
$labels['saveto'] = 'Αποθήκευση στο cloud...';
$labels['saveas'] = 'Αποθήκευση ως:';
$labels['create'] = 'Δημιουργία';
$labels['save'] = 'Αποθήκευση';
$labels['cancel'] = 'Άκυρο';
$labels['fromcloud'] = 'Από το cloud...';
$labels['attachsel'] = 'Επισύναψη επιλεγμένου';
$labels['foldercreate'] = 'Δημιουργία φακέλου';
$labels['folderedit'] = 'Επεξεργασία φακέλου';
$labels['foldermount'] = 'Προσθήκη αποθηκευτικού χώρου';
$labels['folderdelete'] = 'Διαγραφή φακέλου';
$labels['foldername'] = 'Όνομα φακέλου';
$labels['name'] = 'Όνομα';
$labels['type'] = 'Τύπος';
$labels['upload'] = 'Μεταφόρτωση';
$labels['uploadfile'] = 'Μεταφόρτωση αρχείου(ων)';
$labels['get'] = 'Λήψη';
$labels['getfile'] = 'Λήψη αρχείου';
$labels['view'] = 'Προβολή';
$labels['viewfile'] = 'Προβολή αρχείου';
$labels['rename'] = 'Μετονομασία';
$labels['deletefile'] = 'Διαγραφή αρχείου(ων)';
$labels['edit'] = 'Επεξεργασία';
$labels['editfile'] = 'Επεξεργασία αρχείου';
$labels['save'] = 'Αποθήκευση';
$labels['savefile'] = 'Αποθήκευση αρχείου';
$labels['printfile'] = 'Εκτύπωση αρχείου';
$labels['renamefile'] = 'Μετονομασία αρχείου';
$labels['createfile'] = 'Δημιουργία αρχείου';
$labels['createandedit'] = 'Δημιουργία και επεξεργασία';
$labels['copyfile'] = 'Αντιγραφή αρχείου';
$labels['copyandedit'] = 'Αντιγραφή και επεξεργασία';
$labels['documenttitle'] = 'Τίτλος:';
$labels['close'] = 'Κλείσιμο';
$labels['collection_audio'] = 'Ήχος';
$labels['collection_video'] = 'Βίντεο';
$labels['collection_image'] = 'Εικόνες';
$labels['collection_document'] = 'Έγγραφα';
$labels['foldercreating'] = 'Γίνεται δημιουργία φακέλου...';
$labels['folderupdating'] = 'Γίνεται ενημέρωση φακέλου...';
$labels['foldermounting'] = 'Προσθήκη εξωτερικού αποθηκευτικού χώρου...';
$labels['folderdeleting'] = 'Γίνεται διαγραφή φακέλου...';
$labels['fileupdating'] = 'Γίνεται ενημέρωση αρχείου...';
$labels['filecreating'] = 'Γίνεται δημιουργία αρχείου...';
$labels['filemoving'] = 'Μετακίνηση αρχείου(ων)...';
$labels['filecopying'] = 'Αντιγραφή αρχείου(ων)...';
$labels['filedeleting'] = 'Διαγραφή αρχείου(ων)...';
$labels['filedeleteconfirm'] = 'Θέλετε να διαγράψετε τα επιλεγμένα αρχεία;';
$labels['fileoverwrite'] = 'Αντικατάσταση';
$labels['fileoverwriteall'] = 'Αντικατάσταση όλων';
$labels['select'] = 'Επιλογή';
$labels['status'] = 'Κατάσταση';
$labels['addparticipant'] = 'Προσθήκη συμμετεχόντων';
$labels['statusorganizer'] = 'Οργανωτής';
$labels['removeparticipant'] = 'Αφαίρεση';
$labels['file'] = 'Αρχείο';
$labels['comment'] = 'Σχόλιο';
$labels['open'] = 'Άνοιγμα';
$labels['request'] = 'Αίτηση πρόσκλησης';
$labels['arialabelfilelist'] = 'Λίστα αρχείων';
$labels['arialabelfileprops'] = 'Ιδιότητες αρχείου';
$labels['arialabelfilecontent'] = 'Περιεχόμενο αρχείου';
$labels['type.vndoasisopendocumenttext'] = 'Αρχείο κειμένου (ODF)';
$labels['type.html'] = 'Έγγραφο HTML';
