<?php

/**
 * Localizations for the Kolab Files plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_files/
 */

$labels['files'] = 'Files';
$labels['filepreview'] = 'File preview';
$labels['saveall'] = 'Save all to cloud...';
$labels['saveto'] = 'Save to cloud...';
$labels['saveas'] = 'Save as:';
$labels['create'] = 'Create';
$labels['save'] = 'Save';
$labels['cancel'] = 'Cancel';
$labels['fromcloud'] = 'From cloud...';
$labels['selectfiles'] = 'Select file(s) to attach...';
$labels['attachsel'] = 'Attach selected';
$labels['foldercreate'] = 'Create folder';
$labels['folderedit'] = 'Edit folder';
$labels['foldermount'] = 'Add storage';
$labels['folderdelete'] = 'Delete folder';
$labels['folderoptions'] = 'Folder options';

$labels['folderinside'] = 'Insert inside';
$labels['foldername'] = 'Folder name';
$labels['name'] = 'Name';
$labels['mtime'] = 'Modified';
$labels['type'] = 'Type';

$labels['upload'] = 'Upload';
$labels['uploadfile'] = 'Upload file(s)';
$labels['get'] = 'Download';
$labels['getfile'] = 'Download file';
$labels['view'] = 'View';
$labels['viewfile'] = 'View file';
$labels['rename'] = 'Rename';
$labels['deletefile'] = 'Delete file(s)';
$labels['edit'] = 'Edit';
$labels['editfile'] = 'Edit file';
$labels['save'] = 'Save';
$labels['savefile'] = 'Save file';
$labels['printfile'] = 'Print file';
$labels['renamefile'] = 'Rename a file';
$labels['createfile'] = 'Create a file';
$labels['createandedit'] = 'Create and Edit';
$labels['copyfile'] = 'Copy a file';
$labels['copyandedit'] = 'Copy and Edit';
$labels['documenttitle'] = 'Title:';
$labels['close'] = 'Close';
$labels['docedit'] = 'Document editing';

$labels['collection_audio'] = 'Audio';
$labels['collection_video'] = 'Video';
$labels['collection_image'] = 'Images';
$labels['collection_document'] = 'Documents';
$labels['sessions'] = 'Sessions';

$labels['uploading'] = 'Uploading file(s)...';
$labels['attaching'] = 'Attaching file(s)...';
$labels['authenticating'] = 'Authenticating...';
$labels['foldercreating'] = 'Creating folder...';
$labels['folderupdating'] = 'Updating folder...';
$labels['foldermounting'] = 'Adding external storage...';
$labels['folderdeleting'] = 'Deleting folder...';
$labels['folderdeleteconfirm'] = 'Are you sure you want to delete selected folder?';
$labels['folderdeletenotice'] = 'Folder deleted successfully.';
$labels['folderupdatenotice'] = 'Folder updated successfully.';
$labels['foldercreatenotice'] = 'Folder created successfully.';
$labels['foldermountnotice'] = 'Storage added successfully.';
$labels['folderauthtitle'] = 'Logon to $title';
$labels['saveallnotice'] = 'Successfully saved $n file(s).';
$labels['saveallerror'] = 'Saving $n file(s) failed.';
$labels['attacherror'] = 'Failed to attach file(s) from the cloud';
$labels['fileupdating'] = 'Updating file...';
$labels['filecreating'] = 'Creating file...';
$labels['filemoving'] = 'Moving file(s)...';
$labels['filecopying'] = 'Copying file(s)...';
$labels['filedeleting'] = 'Deleting file(s)...';
$labels['filedeleteconfirm'] = 'Are you sure you want to delete selected files?';
$labels['filedeletenotice'] = 'File(s) deleted successfully.';
$labels['filemovenotice'] = 'File(s) moved successfully.';
$labels['filecopynotice'] = 'File(s) copied successfully.';
$labels['uploadsizeerror'] = 'Maximum file size ($size) exceeded!';

$labels['listpermanent'] = 'List permanently';
$labels['additionalfolders'] = 'Additional folders';
$labels['allfolders'] = 'search in all folders';
$labels['fileskip'] = 'Skip';
$labels['fileskipall'] = 'Skip all';
$labels['fileoverwrite'] = 'Overwrite';
$labels['fileoverwriteall'] = 'Overwrite all';
$labels['filemoveconfirm'] = 'This action is going to overwrite the destination file: <b>$file</b>.';

$labels['editfiledialog'] = 'Confirm editing action';
$labels['editfilesessions'] = 'There are ongoing sessions on the selected file. Please, select the action you want to take.';
$labels['newsession'] = 'Create a new session';
$labels['newsessionro'] = 'Create a new session (copy the file into read-write location)';
$labels['ownedsession'] = 'Continue your existing session';
$labels['invitedsession'] = 'Join the session of $user';
$labels['joinsession'] = 'Request an invitation from $user';
$labels['editfilero'] = 'This file is read-only. Do you want to create and edit a copy of the file?';
$labels['editfilerotitle'] = 'Read-only file';
$labels['select'] = 'Select';
$labels['terminatesession'] = 'Terminate the session';
$labels['sessionterminatedtitle'] = 'Session terminated';
$labels['sessionterminated'] = 'The session has been terminated. The window will be closed.';
$labels['terminate'] = 'Terminate';
$labels['sessionterminating'] = 'Terminating the session...';
$labels['unsavedchanges'] = 'There are unsaved changes in the document that will be lost. Do you want to terminate the session anyway?';
$labels['manageeditors'] = 'Invite to document';
$labels['participant'] = 'Participant';
$labels['status'] = 'Status';
$labels['addparticipant'] = 'Add participant';
$labels['delparticipant'] = 'Remove participant';
$labels['invitationtexttitle'] = 'This comment will be attached to the invitation/notification message sent to the participant';
$labels['invitationtextlabel'] = 'Invitation/notification comment';
$labels['statusorganizer'] = 'Organizer';
$labels['statusinvited'] = 'Invited';
$labels['statusaccepted'] = 'Accepted';
$labels['statusdeclined'] = 'Declined';
$labels['statusrequested'] = 'Requested';
$labels['documentinviting'] = 'Inviting participant(s)...';
$labels['documentcancelling'] = 'Removing participant(s)...';
$labels['removeparticipant'] = 'Remove';
$labels['invitednotice'] = 'You have been invited to the editing session by $owner.';
$labels['acceptedownernotice'] = '$owner accepted your request to join the editing session.';
$labels['declinedownernotice'] = '$owner declined your request to join the editing session.';
$labels['acceptednotice'] = '$user accepted your invitation to the editing session.';
$labels['declinednotice'] = '$user declined your invitation to the editing session.';
$labels['requestednotice'] = '$user requested to join the editing session.';
$labels['sessiondialog'] = 'Document editing session';
$labels['sessiondialogcontent'] = 'There is ongoing editing session on $file created by $owner.';
$labels['more'] = 'More.';
$labels['accept'] = 'Accept';
$labels['join'] = 'Join the session';
$labels['decline'] = 'Decline';
$labels['owner'] = 'Owner';
$labels['when'] = 'When';
$labels['file'] = 'File';
$labels['comment'] = 'Comment';
$labels['open'] = 'Open';
$labels['request'] = 'Request an invitation';
$labels['invitationtitle'] = 'Invitation for $file';
$labels['invitationaccepting'] = 'Accepting an invitation...';
$labels['invitationdeclining'] = 'Declining an invitation...';
$labels['invitationrequesting'] = 'Requesting an invitation...';

$labels['storepasswords'] = 'remember password';
$labels['storepasswordsdesc'] = 'Stored passwords will be encrypted. Enable this if you do not want to be asked for the password on every login or you want this storage to be available via WebDAV.';

$labels['arialabelsearchform'] = 'Files search form';
$labels['arialabelquicksearchbox'] = 'Search input';
$labels['arialabellistoptions'] = 'Files list options';
$labels['arialabelfolderoptions'] = 'Folder actions';
$labels['arialabelfileeditform'] = 'File editing form';
$labels['arialabelfilecreateform'] = 'File creation form';
$labels['arialabelfilelist'] = 'List of files';
$labels['arialabelfoldercreateform'] = 'Folder creation form';
$labels['arialabelfoldereditform'] = 'Folder editing form';
$labels['arialabelfoldermountform'] = 'External storage form';
$labels['arialabelfolderauthform'] = 'External storage authentication form';
$labels['arialabelfolderlist'] = 'Folder/Collection selection';
$labels['arialabelfileselectdialog'] = 'File selection dialog';
$labels['arialabelattachmentoptions'] = 'Attachment save options';
$labels['arialabelfilesavedialog'] = 'File(s) saving dialog';
$labels['arialabelfileprops'] = 'File properties';
$labels['arialabelfilecontent'] = 'File content';
$labels['arialabelfileeditdialog'] = 'File editing dialog';
$labels['arialabelsessionslist'] = 'List of document editing sessions';
$labels['arialabelfilerenameform'] = 'File rename form';
$labels['arialabelfilesessiondialog'] = 'Document editing session';
$labels['arialabelcollaborators'] = 'List of document editors';
$labels['arialabelexportoptions'] = 'Export options';
$labels['arialabeldoceditorsdialog'] = 'Document editors (invitations)';

$labels['type.plain'] = 'Plain Text Document';
$labels['type.vndoasisopendocumenttext'] = 'Text Document (ODF)';
$labels['type.html'] = 'HTML Document';
