<?php
/**
 * Localizations for the Kolab Files plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_files/
 */
$labels['listpermanent'] = 'List permanently';
$labels['select'] = 'Select';
$labels['participant'] = 'Participant';
$labels['status'] = 'Status';
$labels['addparticipant'] = 'Add participant';
$labels['invitationtextlabel'] = 'Invitation/notification comment';
$labels['statusorganizer'] = 'Organizer';
$labels['owner'] = 'Owner';
$labels['comment'] = 'Comment';
