<?php
/**
 * Localizations for the Kolab Files plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_files/
 */
$labels['files'] = 'Fájlfelhő';
$labels['saveall'] = 'Csatolmányok mentése a felhőbe...';
$labels['saveto'] = 'Mentés a felhőbe...';
$labels['saveas'] = 'Fájlnév:';
$labels['create'] = 'Létrehozás';
$labels['save'] = 'Mentés';
$labels['cancel'] = 'Mégse';
$labels['fromcloud'] = 'Fájlfelhőből...';
$labels['selectfiles'] = 'Csatolmányok kiválasztása...';
$labels['attachsel'] = 'Jelölt fájlok csatolása';
$labels['foldercreate'] = 'Mappa létrehozása';
$labels['folderdelete'] = 'Mappa törlése';
$labels['folderinside'] = 'Almappa ide';
$labels['foldername'] = 'Mappa neve';
$labels['name'] = 'Név';
$labels['mtime'] = 'Módosítva';
$labels['type'] = 'Típus';
$labels['upload'] = 'Feltöltés';
$labels['uploadfile'] = 'Fájlok feltöltése';
$labels['get'] = 'Letöltés';
$labels['getfile'] = 'Fájlok letöltése';
$labels['view'] = 'Megtekintés';
$labels['viewfile'] = 'Fájl megtekintése';
$labels['rename'] = 'Rename';
$labels['deletefile'] = 'Fájlok törlése';
$labels['edit'] = 'Szerkesztés';
$labels['editfile'] = 'Fájl szerkesztése';
$labels['save'] = 'Mentés';
$labels['savefile'] = 'Fájl mentése';
$labels['printfile'] = 'Fájl nyomtatása';
$labels['close'] = 'Close';
$labels['collection_audio'] = 'Hangfájlok';
$labels['collection_video'] = 'Videó fájlok';
$labels['collection_image'] = 'Képek';
$labels['collection_document'] = 'Dokumentumok';
$labels['uploading'] = 'Feltöltés...';
$labels['attaching'] = 'Csatolás...';
$labels['foldercreating'] = 'Mappa létrehozása...';
$labels['folderdeleting'] = 'Mappa törlése...';
$labels['folderdeleteconfirm'] = 'Biztos benne, hogy törölni szeretné a kijelölt mappát?';
$labels['folderdeletenotice'] = 'Mappa törlése sikeres.';
$labels['foldercreatenotice'] = 'Mappa létrehozása sikeres.';
$labels['saveallnotice'] = '$n fájl mentése sikeres.';
$labels['saveallerror'] = '$n fájl mentése nem sikerült.';
$labels['attacherror'] = 'Nem sikerült csatolni a fájlfelhőből';
$labels['fileupdating'] = 'Fájl frissítése...';
$labels['filemoving'] = 'Áthelyezés...';
$labels['filecopying'] = 'Fájlmásolás...';
$labels['filedeleting'] = 'Fájltörlés...';
$labels['filedeleteconfirm'] = 'Biztos benne, hogy törölni szeretné a kijelölt fájlokat?';
$labels['filedeletenotice'] = 'Törlés sikeres.';
$labels['filemovenotice'] = 'Áthelyezés sikeres.';
$labels['filecopynotice'] = 'Másolás sikeres.';
$labels['listpermanent'] = 'List permanently';
$labels['allfolders'] = 'keresés minden mappában';
$labels['fileskip'] = 'Kihagyás';
$labels['fileskipall'] = 'Mindegyik kihagyása';
$labels['fileoverwrite'] = 'Felülírás';
$labels['fileoverwriteall'] = 'Mindegyik felülírása';
$labels['filemoveconfirm'] = 'Ezzel a művelettel felülíródik a fájl: <b>$file</b>.';
$labels['select'] = 'Jelölés';
$labels['participant'] = 'Résztvevő';
$labels['status'] = 'Stát.';
$labels['addparticipant'] = 'Résztvevő meghívása';
$labels['invitationtextlabel'] = 'Invitation/notification comment';
$labels['statusorganizer'] = 'Szervező';
$labels['removeparticipant'] = 'Eltávolítás';
$labels['accept'] = 'Elfogadás';
$labels['decline'] = 'Elutasítás';
$labels['owner'] = 'Tulajdonos';
$labels['comment'] = 'Comment';
$labels['open'] = 'Open';
$labels['arialabelfileprops'] = 'Fájl tulajdonságai';
