<?php
/**
 * Localizations for the Kolab Files plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_files/
 */
$labels['save'] = '저장';
$labels['cancel'] = '취소';
$labels['name'] = '이름';
$labels['edit'] = '수정';
$labels['save'] = '저장';
$labels['select'] = '선택';
$labels['participant'] = '참가자';
$labels['status'] = '상태';
$labels['addparticipant'] = '참가자 추가';
$labels['statusorganizer'] = '주최자';
$labels['comment'] = '코멘트';
