<?php
/**
 * Localizations for the Kolab Files plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_files/
 */
$labels['files'] = 'Faili';
$labels['save'] = 'Saglabāt';
$labels['cancel'] = 'Atcelt';
$labels['folderinside'] = 'Ievietot';
$labels['name'] = 'Nosaukums';
$labels['edit'] = 'Labot';
$labels['save'] = 'Saglabāt';
$labels['close'] = 'Aizvērt';
$labels['listpermanent'] = 'Rādīt sarakstā vienmēr';
$labels['select'] = 'Izvēlēties';
$labels['participant'] = 'Dalībnieks';
$labels['status'] = 'Statuss';
$labels['addparticipant'] = 'Pievienot dalībnieku';
$labels['invitationtextlabel'] = 'Uzaicinājumam/paziņojuma komentārs';
$labels['statusorganizer'] = 'Organizētājs';
$labels['statusaccepted'] = 'Pieņemts';
$labels['statusdeclined'] = 'Noraidīts';
$labels['accept'] = 'Pieņemt';
$labels['decline'] = 'Noraidīt';
$labels['owner'] = 'Īpašnieks';
$labels['comment'] = 'Komentārs';
