<?php
/**
 * Localizations for the Kolab Files plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_files/
 */
$labels['files'] = 'Pliki';
$labels['filepreview'] = 'Podgląd pliku';
$labels['saveas'] = 'Zapisz jako:';
$labels['create'] = 'Utwórz';
$labels['save'] = 'Zapisz';
$labels['cancel'] = 'Anuluj';
$labels['folderinside'] = 'Wstaw wewnątrz';
$labels['name'] = 'Nazwa';
$labels['mtime'] = 'Zmodyfikowano';
$labels['type'] = 'Typ';
$labels['get'] = 'Pobierz';
$labels['getfile'] = 'Pobierz plik';
$labels['rename'] = 'Zmień nazwę';
$labels['deletefile'] = 'Usuń plik(i)';
$labels['edit'] = 'Edytuj';
$labels['editfile'] = 'Edytuj plik';
$labels['save'] = 'Zapisz';
$labels['savefile'] = 'Zapisz plik';
$labels['printfile'] = 'Wydrukuj plik';
$labels['close'] = 'Zamknij';
$labels['collection_audio'] = 'Audio';
$labels['collection_video'] = 'Video';
$labels['collection_image'] = 'Obrazy';
$labels['collection_document'] = 'Dokumenty';
$labels['authenticating'] = 'Uwierzytelnianie...';
$labels['foldercreating'] = 'Utwórz folder...';
$labels['folderupdating'] = 'Aktualizacja folderu...';
$labels['folderdeleting'] = 'Usuwanie folderu...';
$labels['folderauthtitle'] = 'Zaloguj do $title';
$labels['uploadsizeerror'] = 'Maksymalny rozmiar pliku ($size) przekroczony!';
$labels['listpermanent'] = 'Dodaj do listy na stałe';
$labels['fileskip'] = 'Pomiń';
$labels['fileskipall'] = 'Pomiń wszystko';
$labels['fileoverwrite'] = 'Nadpisz';
$labels['fileoverwriteall'] = 'Nadpisz wszystko';
$labels['select'] = 'Wybierz';
$labels['participant'] = 'Uczestnik';
$labels['status'] = 'Status';
$labels['addparticipant'] = 'Dodaj uczestnika';
$labels['invitationtextlabel'] = 'Komentarz zaproszenia/powiadomienia';
$labels['statusorganizer'] = 'Organizator';
$labels['removeparticipant'] = 'Usuń';
$labels['owner'] = 'Właściciel';
$labels['comment'] = 'Komentarz';
$labels['open'] = 'Otwórz';
$labels['storepasswords'] = 'zapamiętaj hasło';
$labels['arialabelfileprops'] = 'Właściwości';
