<?php
/**
 * Localizations for the Kolab Files plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_files/
 */
$labels['files'] = 'Arquivos';
$labels['saveall'] = 'Salvar tudo na nuvem...';
$labels['saveto'] = 'Salvar na nuvem...';
$labels['saveas'] = 'Salvar como:';
$labels['create'] = 'Criar';
$labels['save'] = 'Salvar';
$labels['cancel'] = 'Cancelar';
$labels['fromcloud'] = 'Da nuvem...';
$labels['selectfiles'] = 'Selecione arquivo(s) para anexar...';
$labels['attachsel'] = 'Anexar selecionado';
$labels['foldercreate'] = 'Criar pasta';
$labels['folderdelete'] = 'Remover pasta';
$labels['folderinside'] = 'Inserir dentro';
$labels['foldername'] = 'Nome da pasta';
$labels['name'] = 'Nome';
$labels['mtime'] = 'Modificado';
$labels['type'] = 'Tipo';
$labels['upload'] = 'Enviar';
$labels['uploadfile'] = 'Enviar arquivo(s)';
$labels['get'] = 'Baixar';
$labels['getfile'] = 'Baixar arquivo';
$labels['view'] = 'Visualizar';
$labels['viewfile'] = 'Visualizar arquivo';
$labels['rename'] = 'Renomear';
$labels['deletefile'] = 'Remover arquivo(s)';
$labels['edit'] = 'Editar';
$labels['editfile'] = 'Editar arquivo';
$labels['save'] = 'Salvar';
$labels['savefile'] = 'Salvar arquivo';
$labels['printfile'] = 'Imprimir arquivo';
$labels['close'] = 'Fechar';
$labels['collection_audio'] = 'Áudio';
$labels['collection_video'] = 'Vídeo';
$labels['collection_image'] = 'Imagens';
$labels['collection_document'] = 'Documentos';
$labels['uploading'] = 'Enviando arquivo(s)...';
$labels['attaching'] = 'Anexando arquivo(s)...';
$labels['foldercreating'] = 'Criando pasta...';
$labels['folderdeleting'] = 'Removendo pasta...';
$labels['folderdeleteconfirm'] = 'Você tem certeza que deseja remover a pasta selecionada?';
$labels['folderdeletenotice'] = 'Pasta removida com sucesso.';
$labels['foldercreatenotice'] = 'Pasta criada com sucesso.';
$labels['saveallnotice'] = 'Salvo(s) $n arquivo(s) com sucesso.';
$labels['saveallerror'] = 'O salvamento de $n arquivo(s) falhou.';
$labels['attacherror'] = 'Falha ao anexar arquivo(s) a partir da nuvem';
$labels['fileupdating'] = 'Atualizando arquivo...';
$labels['filemoving'] = 'Movendo arquivo(s)...';
$labels['filecopying'] = 'Copiando arquivo(s)...';
$labels['filedeleting'] = 'Removendo arquivo(s)...';
$labels['filedeleteconfirm'] = 'Você tem certeza que deseja remover os arquivos selecionados?';
$labels['filedeletenotice'] = 'Arquivo(s) removidos com sucesso.';
$labels['filemovenotice'] = 'Arquivo(s) movidos com sucesso.';
$labels['filecopynotice'] = 'Arquivo(s) copiados com sucesso.';
$labels['uploadsizeerror'] = 'Limite máximo de tamanho de arquivo ($size) excedido!';
$labels['listpermanent'] = 'Listar permanentemente';
$labels['allfolders'] = 'pesquisar em todas as pastas';
$labels['fileskip'] = 'Pular';
$labels['fileskipall'] = 'Pular todos';
$labels['fileoverwrite'] = 'Sobrescrever';
$labels['fileoverwriteall'] = 'Sobrescrever todos';
$labels['filemoveconfirm'] = 'Esta ação irá sobrescrever o arquivo de destino: <b>$file</b>.';
$labels['select'] = 'Selecionar';
$labels['participant'] = 'Participante';
$labels['status'] = 'Situação';
$labels['addparticipant'] = 'Adicionar participante';
$labels['invitationtextlabel'] = 'Invitation/notification comment';
$labels['statusorganizer'] = 'Organizador';
$labels['removeparticipant'] = 'Remover';
$labels['accept'] = 'Aceitar';
$labels['decline'] = 'Rejeitar';
$labels['owner'] = 'Dono';
$labels['comment'] = 'Comentário';
$labels['open'] = 'Abrir';
$labels['arialabelfileprops'] = 'Propriedades do arquivo';
