<?php
/**
 * Localizations for the Kolab Files plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_files/
 */
$labels['files'] = 'Ficheiros';
$labels['save'] = 'Gravar';
$labels['cancel'] = 'Cancelar';
$labels['folderinside'] = 'Inserir dentro';
$labels['name'] = 'Nome';
$labels['edit'] = 'Editar';
$labels['save'] = 'Gravar';
$labels['listpermanent'] = 'Listar sempre';
$labels['select'] = 'Selecionar';
$labels['participant'] = 'Participante';
$labels['status'] = 'Estado';
$labels['addparticipant'] = 'Adicionar participante';
$labels['invitationtextlabel'] = 'Observações — Convite/notificação';
$labels['statusorganizer'] = 'Organizador';
$labels['owner'] = 'Dono';
$labels['comment'] = 'Comentário';
