<?php
/**
 * Localizations for the Kolab Files plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_files/
 */
$labels['files'] = 'Filer';
$labels['save'] = 'Spara';
$labels['cancel'] = 'Avbryt';
$labels['folderinside'] = 'Infoga inuti';
$labels['name'] = 'Namn';
$labels['edit'] = 'Redigera';
$labels['save'] = 'Spara';
$labels['listpermanent'] = 'Lista permanent';
$labels['select'] = 'Välj';
$labels['participant'] = 'Deltagare';
$labels['status'] = 'Status';
$labels['addparticipant'] = 'Lägg till deltagare';
$labels['invitationtextlabel'] = 'Kommentar till inbjudan/meddelande';
$labels['statusorganizer'] = 'Organisatör';
$labels['owner'] = 'Ägare';
$labels['comment'] = 'Kommentar';
