<?php
/**
 * Localizations for the Kolab Address Book plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_addressbook/
 */
$labels['initials'] = 'Инциали';
$labels['profession'] = 'Професия';
$labels['officelocation'] = 'Офис адрес';
$labels['children'] = 'Деца';
$labels['pgppublickey'] = 'PGP публичен ключ';
$labels['pkcs7publickey'] = 'S/MIME публичен ключ';
$labels['freebusyurl'] = 'Free-busy URL';
$labels['typebusiness'] = 'Работен';
$labels['typebusinessfax'] = 'Работен Факс';
$labels['typecompany'] = 'Компания';
$labels['typeprimary'] = 'Основен';
$labels['bookremove'] = 'Remove from list';
$labels['searchterms'] = 'Search terms';
$labels['foldersubscribe'] = 'List permanently';
?>
