<?php
/**
 * Localizations for the Kolab Address Book plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_addressbook/
 */
$labels['searchterms'] = 'Termes de cerca';
$labels['foldersubscribe'] = 'Llista permanentment';
$labels['objectchangelog'] = 'Canvia historial';
$labels['objectdiffnotavailable'] = 'No és possible comparar les revisions seleccionades';
?>
