<?php
/**
 * Localizations for the Kolab Address Book plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_addressbook/
 */
$labels['initials'] = 'Iniciály';
$labels['profession'] = 'Povolání';
$labels['officelocation'] = 'Umístění kanceláře';
$labels['children'] = 'Děti';
$labels['pgppublickey'] = 'Veřejný klíč PGP';
$labels['pkcs7publickey'] = 'Veřejný klíč S/MIME';
$labels['freebusyurl'] = 'Volná/Obsazená adresa';
$labels['typebusiness'] = 'Pracovní';
$labels['typebusinessfax'] = 'Pracovní fax';
$labels['typecompany'] = 'Společnost';
$labels['typeprimary'] = 'Hlavní';
$labels['typetelex'] = 'Dálnopis';
$labels['typeradio'] = 'Bezdrátový telefon';
$labels['typeisdn'] = 'ISDN';
$labels['typettytdd'] = 'TTY/TDD';
$labels['typecallback'] = 'Zpětné volání';
$labels['settings'] = 'Nastavení';
$labels['bookcreate'] = 'Vytvořit adresář';
$labels['bookedit'] = 'Upravit adresář';
$labels['bookdelete'] = 'Smazat adresář';
$labels['bookremove'] = 'Odstranit ze seznamu';
$labels['bookproperties'] = 'Vlastnosti adresáře';
$labels['bookname'] = 'Název knihy';
$labels['parentbook'] = 'Nadřazená kniha';
$labels['bookshowurl'] = 'Zobrazit CardDAV URL';
$labels['carddavurldescription'] = 'Zkopírujte tuto adresu do aplikace <a href="http://en.wikipedia.org/wiki/CardDAV" target="_blank">CardDAV</a> klienta pro úplné synchronizování tohoto adresáře s vaším počítačem nebo mobilním zařízením.';
$labels['addressbookprio'] = 'Pořadí adresářů';
$labels['personalfirst'] = 'Nejprve osobní adresář(e)';
$labels['globalfirst'] = 'Nejprve globální adresář(e)';
$labels['personalonly'] = 'Pouze osobní adresář(e)';
$labels['globalonly'] = 'Pouze globální adresář(e)';
$labels['findaddressbooks'] = 'Hledat adresáře';
$labels['searchterms'] = 'Hledané výrazy';
$labels['listsearchresults'] = 'Další adresáře';
$labels['foldersearchform'] = 'Vyhledávací formulář pro adresář';
$labels['foldersubscribe'] = 'Ukazovat seznam trvale';
$labels['nraddressbooksfound'] = 'Nalezeno $nr adresářů';
$labels['noaddressbooksfound'] = 'Nenalezeny žádné adresáře';
$labels['showhistory'] = 'Ukázat historii';
$labels['objectchangelog'] = 'Historie změn';
$labels['objectdiff'] = 'Změny od $rev1 do $rev2';
$labels['revisionrestoreconfirm'] = 'Opravdu chcete obnovit pozměnění $rev tohoto kontaktu? To nahradí současný kontakt se starou verzí.';
$labels['objectnotfound'] = 'Nepodařilo se nahrát data kontaktu';
$labels['objectchangelognotavailable'] = 'Historie změn není dostupná pro tento kontakt';
$labels['objectdiffnotavailable'] = 'Pro vybrané verze není žádné srovnání možné';
$labels['objectrestoresuccess'] = 'Změna $rev úspěšně obnovena';
$labels['objectrestoreerror'] = 'Nepodařilo se obnovit starou změnu';
$messages['bookdeleteconfirm']  = 'Opravdu chcete smazat označený adresář a veškeré obsažené kontakty?';
$messages['bookdeleting'] = 'Maže se adresář...';
$messages['booksaving'] = 'Adresář se ukládá...';
$messages['bookdeleted'] = 'Adresář byl úspěšně smazán.';
$messages['bookupdated'] = 'Adresář byl úspěšně aktualizován.';
$messages['bookcreated'] = 'Adresář byl úspěšně vytvořen.';
$messages['bookdeleteerror'] = 'Během mazání adresáře došlo k chybě.';
$messages['bookupdateerror'] = 'Během aktualizování adresáře došlo k chybě.';
$messages['bookcreateerror'] = 'Během vytváření adresáře došlo k chybě.';
$messages['nobooknamewarning'] = 'Prosím, zadejte název adresáře.';
$messages['noemailnamewarning'] = 'Prosím, zadejte e-mailovou adresu nebo kontaktní jméno.';
?>
