<?php
/**
 * Localizations for the Kolab Address Book plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_addressbook/
 */
$labels['initials'] = 'Initialer';
$labels['profession'] = 'Stilling';
$labels['officelocation'] = 'Arbejdsplads';
$labels['children'] = 'Børn';
$labels['pgppublickey'] = 'Offentlig PGP-nøgle';
$labels['pkcs7publickey'] = 'Offentlig S/MIME-nøgle';
$labels['freebusyurl'] = 'URL for ledig/optaget';
$labels['typebusiness'] = 'Virksomhed';
$labels['typebusinessfax'] = 'Fax arbejde';
$labels['typecompany'] = 'Firma';
$labels['typeprimary'] = 'Primær';
$labels['typetelex'] = 'Telex';
$labels['typeradio'] = 'Radio';
$labels['typeisdn'] = 'ISDN';
$labels['typettytdd'] = 'TTY/TDD';
$labels['typecallback'] = 'Tilbagekald';
$labels['settings'] = 'Indstillinger';
$labels['bookcreate'] = 'Opret adressebog';
$labels['bookedit'] = 'Redigér adressebog';
$labels['bookdelete'] = 'Slet adressebog';
$labels['bookremove'] = 'Remove from list';
$labels['bookproperties'] = 'Egenskaber for adressebog';
$labels['bookname'] = 'Navn på bog';
$labels['parentbook'] = 'Overordnet bog';
$labels['bookshowurl'] = 'Vis CardDAV-URL';
$labels['carddavurldescription'] = 'Kopiér denne adresse til et <a href="http://en.wikipedia.org/wiki/CardDAV" target="_blank">CardDAV</a>-klientprogram for komplet synkronisering af denne specifikke adressebog med din maskine eller mobilenhed.';
$labels['addressbookprio'] = 'Markering/adfærd for adressebøger';
$labels['personalfirst'] = 'Personlige adressebøger først';
$labels['globalfirst'] = 'Globale adressebøger først';
$labels['personalonly'] = 'Kun personlige adresse';
$labels['globalonly'] = 'Kun globale adressebøger';
$labels['findaddressbooks'] = 'Find adressebøger';
$labels['searchterms'] = 'Søgetermer';
$labels['listsearchresults'] = 'Yderligere adressebøger';
$labels['foldersearchform'] = 'Søgeformular for adressebog';
$labels['foldersubscribe'] = 'Vis permanent';
$labels['nraddressbooksfound'] = 'Der blev fundet $nr adressebøger ';
$labels['noaddressbooksfound'] = 'Fandt ingen adressebøger';
$labels['showhistory'] = 'Vis historik';
$labels['objectchangelog'] = 'Ændringshistorik';
$labels['objectdiff'] = 'Ændringer fra $rev1 til $rev2';
$labels['revisionrestoreconfirm'] = 'Er du sikker på at du vil genskabe revision $rev af denne kontakt? Det vil overskirve den nuværende kontakt med en tidligere version.';
$labels['objectnotfound'] = 'Kunne ikke læse kontakt data';
$labels['objectchangelognotavailable'] = 'Ændringshistorik er ikke tilgængelig for denne kontakt.';
$labels['objectdiffnotavailable'] = 'Det er ikke muligt at sammenligne de valgte revisioner';
$labels['objectrestoresuccess'] = 'Revision $rev blev genskabt';
$labels['objectrestoreerror'] = 'Mislykkedes med at genskabe den gamle revision';
$messages['bookdeleteconfirm']  = 'Vil du virkelig slette den valgte adressebog og alle kontakterne i den?';
$messages['bookdeleting'] = 'Sletter adressebog...';
$messages['booksaving'] = 'Gemmer adressebog...';
$messages['bookdeleted'] = 'Sletning af adressebogen blev gennemført.';
$messages['bookupdated'] = 'Opdateringen af adressebog blev gennemført.';
$messages['bookcreated'] = 'Oprettelsen af adressbog blev gennemført.';
$messages['bookdeleteerror'] = 'Der opstod en fejl under sletning af adressebogen.';
$messages['bookupdateerror'] = 'Der opstod en fejl under opdatering af adressebogen.';
$messages['bookcreateerror'] = 'Der opstod en fejl under oprettelse af adressebogen.';
$messages['nobooknamewarning'] = 'Angiv venligst navnet på adressebogen.';
$messages['noemailnamewarning'] = 'Angiv venligst e-postadresse eller kontaktnavn.';
?>
