<?php
/**
 * Localizations for the Kolab Address Book plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_addressbook/
 */
$labels['initials'] = 'Initialen';
$labels['profession'] = 'Berufsbezeichnung';
$labels['officelocation'] = 'Büro Adresse';
$labels['children'] = 'Kinder';
$labels['pgppublickey'] = 'PGP-Schlüssel';
$labels['pkcs7publickey'] = 'S/MIME-Schlüssel';
$labels['freebusyurl'] = 'Frei/Belegt URL';
$labels['typebusiness'] = 'Dienstlich';
$labels['typebusinessfax'] = 'Dienst';
$labels['typecompany'] = 'Firma';
$labels['typeprimary'] = 'Primär';
$labels['typetelex'] = 'Telex';
$labels['typeradio'] = 'Funk';
$labels['typeisdn'] = 'ISDN';
$labels['typettytdd'] = 'Telescrit';
$labels['typecallback'] = 'Rückruf';
$labels['settings'] = 'Einstellungen';
$labels['bookcreate'] = 'Adressbuch anlegen';
$labels['bookedit'] = 'Adressbuch bearbeiten';
$labels['bookdelete'] = 'Adressbuch löschen';
$labels['bookremove'] = 'Remove from list';
$labels['bookproperties'] = 'Eigenschaften des Adressbuchs';
$labels['bookname'] = 'Name des Buches';
$labels['parentbook'] = 'Übergeordnetes Buch';
$labels['bookshowurl'] = 'CardDAV URL anzeigen';
$labels['carddavurldescription'] = 'Diese Adresse in einen <a href="http://en.wikipedia.org/wiki/CardDAV" target="_blank">CardDAV</a>-Klienten kopieren, um dasAdressbuch mit einem Computer oder mobilen Gerät zu synchronisieren.';
$labels['addressbookprio'] = 'Reihenfolge der Adressbücher';
$labels['personalfirst'] = 'Private(s) Adressbuch/Adressbücher zuerst';
$labels['globalfirst'] = 'Globale(s) Adressbuch/Adressbücher zuerst';
$labels['personalonly'] = 'Nur persönliche(s) Adressbuch/Adressbücher';
$labels['globalonly'] = 'Nur globale(s) Adressbuch/Adressbücher';
$labels['findaddressbooks'] = 'Adressbücher finden';
$labels['searchterms'] = 'Suchbegriffe';
$labels['listsearchresults'] = 'Zusätzliche Adressbücher';
$labels['foldersearchform'] = 'Suchformular für Adressbuch';
$labels['foldersubscribe'] = 'Permanent anzeigen';
$labels['nraddressbooksfound'] = '$nr Adressbücher gefunden';
$labels['noaddressbooksfound'] = 'Keine Adressbücher gefunden';
$labels['showhistory'] = 'Verlauf anzeigen';
$labels['objectchangelog'] = 'Änderungsverlauf';
$labels['objectdiff'] = 'Änderungen aus $rev1 nach $rev2';
$labels['revisionrestoreconfirm'] = 'Wollen Sie wirklich die Version $rev dieses Kontakt wiederherstellen? Diese Aktion wird die aktuelle Kopie mit der älteren Version ersetzen.';
$labels['objectnotfound'] = 'Fehler beim Laden der Addressedaten';
$labels['objectchangelognotavailable'] = 'Änderungshistorie ist nicht verfügbar für diesen Kontakt';
$labels['objectdiffnotavailable'] = 'Vergleich für die gewählten Versionen nicht möglich';
$labels['objectrestoresuccess'] = 'Version $rev erfolgreich wiederhergestellt';
$labels['objectrestoreerror'] = 'Fehler beim Wiederherstellen der alten Version';
$messages['bookdeleteconfirm']  = 'Soll das gewählte Adressbuch und alle Kontakte darin wirklich gelöscht werden?';
$messages['bookdeleting'] = 'Adressbuch wird gelöscht...';
$messages['booksaving'] = 'Adressbuch wird gespeichert...';
$messages['bookdeleted'] = 'Adressbuch erfolgreich gelöscht.';
$messages['bookupdated'] = 'Adressbuch erfolgreich aktualisiert.';
$messages['bookcreated'] = 'Adressbuch erfolgreich angelegt.';
$messages['bookdeleteerror'] = 'Fehler beim Löschen des Adressbuchs.';
$messages['bookupdateerror'] = 'Fehler beim Aktualisieren des Adressbuchs.';
$messages['bookcreateerror'] = 'Fehler beim Anlegen des Adressbuchs.';
$messages['nobooknamewarning'] = 'Bitte den Namen des Adressbuchs angeben.';
$messages['noemailnamewarning'] = 'Bitte E-Mail-Adresse oder Namen des Kontakts angeben.';
?>
