<?php
/**
 * Localizations for the Kolab Address Book plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_addressbook/
 */
$labels['initials'] = 'Αρχικά';
$labels['profession'] = 'Επάγγελμα';
$labels['officelocation'] = 'Τοποθεσία γραφείου';
$labels['children'] = 'Παιδί';
$labels['pgppublickey'] = 'Δημόσιο κλειδί PGP';
$labels['pkcs7publickey'] = 'Δημόσιο κλειδί S/MIME';
$labels['typebusiness'] = 'Εργασία';
$labels['typebusinessfax'] = 'Fax εργασίας';
$labels['typecompany'] = 'Εταιρία';
$labels['typeprimary'] = 'Πρωτεύον';
$labels['typetelex'] = 'Telex';
$labels['typeisdn'] = 'ISDN';
$labels['typettytdd'] = 'TTY/TDD';
$labels['settings'] = 'Ρυθμίσεις';
$labels['bookcreate'] = 'Δημιουργία βιβλίου διευθύνσεων';
$labels['bookedit'] = 'Επεξεργασία βιβλίου διευθύνσεων';
$labels['bookdelete'] = 'Διαγραφή βιβλίου διευθύνσεων';
$labels['bookremove'] = 'Αφαίρεση από την λίστα';
$labels['bookproperties'] = 'Ιδιότητες βιβλίου διευθύνσεων';
$labels['bookname'] = 'Όνομα βιβλίου';
$labels['bookshowurl'] = 'Εμφάνιση URL για CardDAV';
$labels['carddavurldescription'] = 'Αντιγράψτε αυτή τη διεύθυνση στον πελάτη <a href="http://en.wikipedia.org/wiki/CardDAV" target="_blank">CardDAV</a> για πλήρη συγχρονισμό του συγκεκριμένου βιβλίου με τον υπολογιστή σας ή το κινητό σας.';
$labels['findaddressbooks'] = 'Εύρεση βιβλίων διευθύνσεων';
$labels['searchterms'] = 'Όροι αναζήτησης';
$labels['listsearchresults'] = 'Επιπλέον βιβλία διευθύνσεων';
$labels['showhistory'] = 'Προβολή ιστορικού';
$labels['objectchangelog'] = 'Αλλαγή ιστορικού';
$labels['objectnotfound'] = 'Αποτυχία φόρτωσης δεδομένων επαφής';
$messages['bookdeleting'] = 'Γίνεται διαγραφή βιβλίου διευθύνσεων...';
$messages['booksaving'] = 'Γίνεται αποθήκευση βιβλίου διευθύνσεων';
$messages['bookdeleted'] = 'Επιτυχημένη διαγραφή βιβλίου διευθύνσεων.';
$messages['bookupdated'] = 'Επιτυχημένη ενημέρωση βιβλίου διευθύνσεων.';
$messages['bookcreated'] = 'Επιτυχημένη δημιουργία βιβλίου διευθύνσεων.';
$messages['bookdeleteerror'] = 'Παρουσιάστηκε σφάλμα κατά την διαγραφή του βιβλίου διευθύνσεων.';
$messages['bookupdateerror'] = 'Παρουσιάστηκε σφάλμα κατά την ενημέρωση του βιβλίου διευθύνσεων.';
$messages['bookcreateerror'] = 'Παρουσιάστηκε σφάλμα κατά την δημιουργία του βιβλίου διευθύνσεων.';
$messages['nobooknamewarning'] = 'Παρακαλούμε, εισάγετε όνομα του βιβλίου διευθύνσεων.';
$messages['noemailnamewarning'] = 'Παρακαλούμε, εισάγετε διεύθυνση ηλεκτρονικου ταχυδρομείου ή όνομα επαφής.';
?>
