<?php
/**
 * Localizations for the Kolab Address Book plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_addressbook/
 */
$labels['initials'] = 'Iniciales';
$labels['profession'] = 'Profesión';
$labels['officelocation'] = 'Ubicación de la oficina';
$labels['children'] = 'Hijos';
$labels['pgppublickey'] = 'Llave pública PGP';
$labels['pkcs7publickey'] = 'Llave pública S/MIME';
$labels['freebusyurl'] = 'URL Libre-ocupado';
$labels['typebusiness'] = 'Trabajo';
$labels['typebusinessfax'] = 'Fax de trabajo';
$labels['typecompany'] = 'Compañía';
$labels['typeprimary'] = 'Primario';
$labels['typetelex'] = 'Telex';
$labels['typeradio'] = 'Radio';
$labels['typeisdn'] = 'ISDN';
$labels['typettytdd'] = 'TTY/TDD';
$labels['typecallback'] = 'Retorno';
$labels['settings'] = 'Configuraciones';
$labels['bookcreate'] = 'Crear libreta de direcciones';
$labels['bookedit'] = 'Editar libreta de direcciones';
$labels['bookdelete'] = 'Eliminar libreta de direcciones';
$labels['bookremove'] = 'Eliminar de la lista';
$labels['bookproperties'] = 'Propiedades de libreta de direcciones';
$labels['bookname'] = 'Nombre de libro';
$labels['parentbook'] = 'Libro superior';
$labels['bookshowurl'] = 'Mostrar URL CardDAV';
$labels['carddavurldescription'] = 'Copie esta dirección a su aplicación cliente <a href="http://en.wikipedia.org/wiki/CardDAV" target="_blank">CardDAV</a> para sincronizar completamente esta libreta de direcciones específica con su ordenador o dispositivo móvil.';
$labels['addressbookprio'] = 'Selección/comportamiento de libreta(s) de direcciones';
$labels['personalfirst'] = 'Libreta(s) de direcciones personal primero';
$labels['globalfirst'] = 'Libreta(s) de direcciones globales primero';
$labels['personalonly'] = 'Sólo libreta(s) de direcciones personal';
$labels['globalonly'] = 'Sólo libreta(s) de direcciones global';
$labels['findaddressbooks'] = 'Encontrar libreta de direcciones';
$labels['searchterms'] = 'Buscar términos';
$labels['listsearchresults'] = 'Libreta de direcciones adicional';
$labels['foldersearchform'] = 'Formulario de búsqueda de libreta de direcciones';
$labels['foldersubscribe'] = 'Listar permanentemente';
$labels['nraddressbooksfound'] = '$nr libretas de direcciones encontrada(s)';
$labels['noaddressbooksfound'] = 'No se encontraron libretas de direcciones';
$labels['showhistory'] = 'Mostrar Historial';
$labels['objectchangelog'] = 'Cambiar Historial';
$labels['objectdiff'] = 'Cambios de $rev1 a $rev2';
$labels['revisionrestoreconfirm'] = 'Confirme que quiere recuperar la revisión $rev de este contacto. Esta acción reemplazará el evento actual con la versión anterior.';
$labels['objectnotfound'] = 'Fallo al cargar datos del contacto';
$labels['objectchangelognotavailable'] = 'Cambiar historial no está disponible para este contacto';
$labels['objectdiffnotavailable'] = 'No es posible comparar las revisiones seleccionadas';
$labels['objectrestoresuccess'] = 'Revisión $rev recuperada exitosamente';
$labels['objectrestoreerror'] = 'Fallo al restaurar el evento anterior';
$messages['bookdeleteconfirm']  = 'Confirme que desea eliminar la libreta de direcciones y todos los contactos en ella';
$messages['bookdeleting'] = 'Eliminando libreta de direcciones...';
$messages['booksaving'] = 'Guardando libreta de direcciones...';
$messages['bookdeleted'] = 'Libreta de direcciones eliminada exitosamente.';
$messages['bookupdated'] = 'Libreta de direcciones actualizada exitosamente.';
$messages['bookcreated'] = 'Libreta de direcciones creada exitosamente.';
$messages['bookdeleteerror'] = 'Fallo eliminando la libreta de direcciones.';
$messages['bookupdateerror'] = 'Fallo al actualizar la libreta de direcciones.';
$messages['bookcreateerror'] = 'Fallo al crear la libreta de direcciones.';
$messages['nobooknamewarning'] = 'Por favor, ingrese el nombre de la libreta de direcciones.';
$messages['noemailnamewarning'] = 'Por favor, ingrese la dirección de correo electrónico o el nombre del contacto.';
?>
