<?php
/**
 * Localizations for the Kolab Address Book plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_addressbook/
 */
$labels['initials'] = 'Iniciales';
$labels['profession'] = 'Profesión';
$labels['officelocation'] = 'Ubicación de la oficina';
$labels['children'] = 'Niños';
$labels['pgppublickey'] = 'Llave pública PGP';
$labels['pkcs7publickey'] = 'Llave pública S/MIME';
$labels['freebusyurl'] = 'URL Fee-busy';
$labels['typebusiness'] = 'Negocio';
$labels['typebusinessfax'] = 'Fax del negocio';
$labels['typecompany'] = 'Compania';
$labels['typeprimary'] = 'Principal';
$labels['typetelex'] = 'Telex';
$labels['typeradio'] = 'Radio';
$labels['typeisdn'] = 'ISDN';
$labels['typettytdd'] = 'TTY/TDD';
$labels['typecallback'] = 'Devolución de llamada';
$labels['settings'] = 'Servicios';
$labels['bookcreate'] = 'Crear libreta de direcciones';
$labels['bookedit'] = 'Editar libreta de direcciones';
$labels['bookdelete'] = 'Borrar libreta de direcciones';
$labels['bookremove'] = 'Remove from list';
$labels['bookproperties'] = 'Propiedades de la libreta de direcciones';
$labels['bookname'] = 'Nombre de la libreta';
$labels['parentbook'] = 'Libreta superior';
$labels['bookshowurl'] = 'Mostrar URL CardDAV';
$labels['carddavurldescription'] = 'Copie esta dirección <a href="http://en.wikipedia.org/wiki/CardDAV" target="_blank"> CardDAV </a> en una aplicación de cliente para sincronizar totalmente esta libreta de direcciones específica con su ordenador o dispositivo móvil .';
$labels['addressbookprio'] = 'Selección/comportamiento de la libreta de direcciones';
$labels['personalfirst'] = 'Libreta de direcciones personal primero';
$labels['globalfirst'] = 'Libreta de direcciones global primero';
$labels['personalonly'] = 'Libreta de direcciones personal solo';
$labels['globalonly'] = 'Libreta de direcciones global solo';
$labels['findaddressbooks'] = 'Encontrar libreta de direcciones';
$labels['searchterms'] = 'Search terms';
$labels['listsearchresults'] = 'Libreta de direcciones adicional';
$labels['foldersearchform'] = 'Formulario de búsqueda de la libreta de direcciones';
$labels['foldersubscribe'] = 'List permanently';
$labels['nraddressbooksfound'] = '$nr libreta de direcciones encontradas';
$labels['noaddressbooksfound'] = 'No se han encontrado libreta de direcciones';
$labels['showhistory'] = 'Mostrar historial';
$labels['objectchangelog'] = 'Cambiar historial';
$labels['objectdiff'] = 'Cambiar de $rev1 a $rev2';
$labels['revisionrestoreconfirm'] = '¿Realmente desea restaurar la revisión $rev de este contacto? Esto reemplazará el contacto actual con la antigua versión.';
$labels['objectnotfound'] = 'No pudo cargarse los datos de contacto';
$labels['objectchangelognotavailable'] = 'El historial de cambios no está disponible para este contacto';
$labels['objectdiffnotavailable'] = 'No hay comparación posible que las revisiones seleccionadas';
$labels['objectrestoresuccess'] = 'Revisión $rev restaurado correctamente';
$labels['objectrestoreerror'] = 'No se pudo restaurar la revisión antigua';
$messages['bookdeleteconfirm']  = '¿Está seguro de eliminar esta libreta de direcciones y todas sus contactos?';
$messages['bookdeleting'] = 'Borrando libreta de direcciones...';
$messages['booksaving'] = 'Guardando libreta de direcciones...';
$messages['bookdeleted'] = 'Se ha eliminado la libreta de direcciones con éxito.';
$messages['bookupdated'] = 'Se ha cargado la libreta de direcciones con éxito.';
$messages['bookcreated'] = 'Se ha creado la libreta de direcciones con éxito.';
$messages['bookdeleteerror'] = 'Se ha producido un error durante la eliminación de la libreta de direcciones.';
$messages['bookupdateerror'] = 'Se ha producido un error durante la actualización de la libreta de direcciones.';
$messages['bookcreateerror'] = 'Se ha producido un error durante la creación de la libreta de direcciones.';
$messages['nobooknamewarning'] = 'Introducir un nombre para la libreta de direcciones';
$messages['noemailnamewarning'] = 'Introduzca una dirección de correo electrónico o nombre de contacto';
?>
