<?php
/**
 * Localizations for the Kolab Address Book plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_addressbook/
 */
$labels['initials'] = 'Nimikirjaimet';
$labels['profession'] = 'Ammatti';
$labels['officelocation'] = 'Toimiston sijainti';
$labels['children'] = 'Lapset';
$labels['pgppublickey'] = 'Julkinen PGP-avain';
$labels['pkcs7publickey'] = 'Julkinen S/MIME-avain';
$labels['typebusiness'] = 'Työ';
$labels['typebusinessfax'] = 'Työfaksi';
$labels['typecompany'] = 'Yhtiö';
$labels['typeprimary'] = 'Ensisijainen';
$labels['typeisdn'] = 'ISDN';
$labels['typecallback'] = 'Takaisinsoitto';
$labels['settings'] = 'Asetukset';
$labels['bookcreate'] = 'Luo osoitekirja';
$labels['bookedit'] = 'Muokkaa osoitekirjaa';
$labels['bookdelete'] = 'Poista osoitekirja';
$labels['bookremove'] = 'Poista listasta';
$labels['bookproperties'] = 'Osoitekirjan ominaisuudet';
$labels['bookname'] = 'Kirjan nimi';
$labels['bookshowurl'] = 'Näytä CardDAV-osoite';
$labels['carddavurldescription'] = 'Kopioi tämä osoite <a href="http://en.wikipedia.org/wiki/CardDAV" target="_blank">CardDAV</a-asiakassovellukseen synkronoidaksesi tämän osoitekirjan tietokoneesi tai mobiililaitteesi kanssa.';
$labels['addressbookprio'] = 'Osoitekirjojen valinta ja toiminta';
$labels['personalfirst'] = 'Henkilökohtainen osoitekirja ensin';
$labels['globalfirst'] = 'Yleinen osoitekirja ensin';
$labels['personalonly'] = 'Pelkkä henkilökohtainen osoitekirja';
$labels['globalonly'] = 'Pelkkä yleinen osoitekirja';
$labels['findaddressbooks'] = 'Etsi osoitekirjoja';
$labels['searchterms'] = 'Hakuehdot';
$labels['listsearchresults'] = 'Lisäosoitekirjat';
$labels['foldersearchform'] = 'Osoitekirjan hakulomake';
$labels['foldersubscribe'] = 'Luetteloi pysyvästi';
$labels['nraddressbooksfound'] = '$nr osoitekirjaa löytyi';
$labels['noaddressbooksfound'] = 'Osoitekirjoja ei löytynyt';
$labels['showhistory'] = 'Näytä historia';
$labels['objectchangelog'] = 'Muutoshistoria';
$labels['objectdiff'] = 'Muutokset versiosta $rev1 versioon $rev2';
$labels['revisionrestoreconfirm'] = 'Haluatko palauttaa tämän yhteystiedon version $rev? Tämä toimenpide korvaa nykyisen yhteystiedon vanhalla versiolla.';
$labels['objectnotfound'] = 'Yhteystiedon lataaminen epäonnistui';
$labels['objectchangelognotavailable'] = 'Muutoshistoria ei ole käytettävissä tämän yhteystiedon kohdalla';
$labels['objectdiffnotavailable'] = 'Valituille versioille ei ole mahdollista tehdä vertailua';
$labels['objectrestoresuccess'] = 'Versio $rev palautettu onnistuneesti';
$labels['objectrestoreerror'] = 'Vanhan version palauttaminen epäonnistui';
$messages['bookdeleteconfirm']  = 'Haluatko varmasti poistaa valitun osoitekirjan ja siinä olevat yhteystiedot?';
$messages['bookdeleting'] = 'Poistetaan osoitekirja...';
$messages['booksaving'] = 'Tallennetaan osoitekirjaa...';
$messages['bookdeleted'] = 'Osoitekirja poistettiin onnistuneesti.';
$messages['bookupdated'] = 'Osoitekirja päivitettiin onnistuneesti.';
$messages['bookcreated'] = 'Osoitekirja luotiin onnistuneesti.';
$messages['bookdeleteerror'] = 'Osoitekirjaa poistaessa tapahtui virhe.';
$messages['bookupdateerror'] = 'Osoitekirjaa päivittäessä tapahtui virhe.';
$messages['bookcreateerror'] = 'Osoitekirjaa luotaessa tapahtui virhe.';
$messages['nobooknamewarning'] = 'Anna osoitekirjalle nimi.';
$messages['noemailnamewarning'] = 'Anna sähköpostiosoite tai yhteystiedon nimi.';
?>
