<?php
/**
 * Localizations for the Kolab Address Book plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_addressbook/
 */
$labels['initials'] = 'Initiales';
$labels['profession'] = 'Profession';
$labels['officelocation'] = 'Emplacement du bureau';
$labels['children'] = 'Enfants';
$labels['pgppublickey'] = 'Clé publique PGP';
$labels['pkcs7publickey'] = 'Clé publique S/MIME';
$labels['freebusyurl'] = 'URL disponible/occupé';
$labels['typebusiness'] = 'Travail';
$labels['typebusinessfax'] = 'Fax travail';
$labels['typecompany'] = 'Société';
$labels['typeprimary'] = 'Principal';
$labels['typetelex'] = 'Télex';
$labels['typeradio'] = 'Radio';
$labels['typeisdn'] = 'ISDN';
$labels['typettytdd'] = 'TTY/TDD';
$labels['typecallback'] = 'Rappel';
$labels['settings'] = 'Paramètres';
$labels['bookcreate'] = 'Créer un carnet d\'adresses';
$labels['bookedit'] = 'Modifier un carnet d\'adresses';
$labels['bookdelete'] = 'Supprimer un carnet d\'adresses';
$labels['bookremove'] = 'Supprimer de la liste';
$labels['bookproperties'] = 'Propriétés du carnet d\'adresses';
$labels['bookname'] = 'Nom du carnet';
$labels['parentbook'] = 'Carnet parent';
$labels['bookshowurl'] = 'Afficher l\'URL CardDAV';
$labels['carddavurldescription'] = 'Copiez cette adresse dans une application client compatible <a href="http://fr.wikipedia.org/wiki/CardDAV" target="_blank">CardDAV</a> pour synchroniser ce carnet d\'adresses avec votre ordinateur ou votre smartphone.';
$labels['addressbookprio'] = 'Sélection du(des) carnet(s) d\'adresses/comportement';
$labels['personalfirst'] = 'Carnet(s) d\'adresses personnel(s) en premier';
$labels['globalfirst'] = 'Carnet(s) d\'adresses global(aux) en premier';
$labels['personalonly'] = 'Carnet(s) d\'adresses personnel(s) seulement';
$labels['globalonly'] = 'Carnet(s) d\'adresse global(aux) seulement';
$labels['findaddressbooks'] = 'Trouver carnets d\'adresses';
$labels['searchterms'] = 'Critères de recherche';
$labels['listsearchresults'] = 'Carnets d\'adresses supplémentaires';
$labels['foldersearchform'] = 'Formulaire de recherche carnet d\'adresses';
$labels['foldersubscribe'] = 'Lister définitivement';
$labels['nraddressbooksfound'] = '$nr carnets d\'adresses trouvés';
$labels['noaddressbooksfound'] = 'Aucun carnet d\'adresses trouvé';
$labels['showhistory'] = 'Montrer l\'historique';
$labels['objectchangelog'] = 'Historique des modifications';
$labels['objectdiff'] = 'Modifications de $rev1 à $rev2';
$labels['revisionrestoreconfirm'] = 'Souhaitez-vous restaurer la révision $rev  de ce contrat ? Cela remplacera le contrat actuel par l\'ancienne version.';
$labels['objectnotfound'] = 'Échec de chargement des données de contact';
$labels['objectchangelognotavailable'] = 'L\'historique des changements n\'est pas disponible pour ce contrat';
$labels['objectdiffnotavailable'] = 'La comparaison des versions sélectionnées est impossible';
$labels['objectrestoresuccess'] = 'La révision $rev a été restaurée avec succès';
$labels['objectrestoreerror'] = 'Échec lors de la restauration de la précédente révision';
$messages['bookdeleteconfirm']  = 'Voulez-vous vraiment supprimer le carnet d\'adresses sélectionné et tous ses contacts ?';
$messages['bookdeleting'] = 'Suppression du carnet d\'adresses...';
$messages['booksaving'] = 'Enregistrement du carnet d\'adresses...';
$messages['bookdeleted'] = 'Carnet d\'adresses supprimé.';
$messages['bookupdated'] = 'Carnet d\'adresses modifié.';
$messages['bookcreated'] = 'Carnet d\'adresses créé.';
$messages['bookdeleteerror'] = 'Une erreur est survenue lors de la suppression du carnet d\'adresses.';
$messages['bookupdateerror'] = 'Une erreur est survenue lors de la modification du carnet d\'adresses.';
$messages['bookcreateerror'] = 'Une erreur est survenue lors de la création du carnet d\'adresses.';
$messages['nobooknamewarning'] = 'Merci de saisir un nom pour le carnet d\'adresses';
$messages['noemailnamewarning'] = 'Merci de saisir une adresse de courriel ou un nom de contact.';
?>
