<?php
/**
 * Localizations for the Kolab Address Book plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_addressbook/
 */
$labels['bookremove'] = 'Remove from list';
$labels['searchterms'] = 'Search terms';
$labels['foldersubscribe'] = 'List permanently';
$labels['objectchangelog'] = 'Change History';
$labels['objectdiffnotavailable'] = 'No comparison possible for the selected revisions';
?>
