<?php
/**
 * Localizations for the Kolab Address Book plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_addressbook/
 */
$labels['initials'] = 'Megszólítás';
$labels['profession'] = 'Foglalkozás';
$labels['officelocation'] = 'Irodai cím';
$labels['children'] = 'Gyermekek';
$labels['pgppublickey'] = 'PGP nyilvános kulcs';
$labels['pkcs7publickey'] = 'S/MIME nyilvános kulcs';
$labels['freebusyurl'] = 'Foglaltság URL';
$labels['typebusiness'] = 'Munkahely';
$labels['typebusinessfax'] = 'Munkahelyi Fax';
$labels['typecompany'] = 'Munkaadó';
$labels['typeprimary'] = 'Elsődleges';
$labels['typetelex'] = 'Telex';
$labels['typeradio'] = 'Mobil';
$labels['typeisdn'] = 'ISDN';
$labels['typettytdd'] = 'Pager';
$labels['typecallback'] = 'Pager';
$labels['settings'] = 'Beállítások';
$labels['bookcreate'] = 'Címjegyzék létrehozása';
$labels['bookedit'] = 'Címjegyzék szerkesztése';
$labels['bookdelete'] = 'Címjegyzék törlése';
$labels['bookproperties'] = 'Címjegyzék tulajdonságai';
$labels['bookname'] = 'Címjegyzékmappa neve';
$labels['parentbook'] = 'Szülőmappa';
$labels['bookshowurl'] = 'Címjegyzék URL címe';
$labels['carddavurldescription'] = 'Másolja be ezt a címet egy <a href="http://en.wikipedia.org/wiki/CardDAV" target="_blank">CardDAV</a>-kompatibilis kliensbe hogy kétirányú szinkronizációval tudjon a címjegyzékéhez onnan is hozzáférni.';
$labels['addressbookprio'] = 'Címjegyzék használatának módja';
$labels['personalfirst'] = 'Saját címjegyzék előbb';
$labels['globalfirst'] = 'Központi címjegyzék előbb';
$labels['personalonly'] = 'Csak saját címjegyzék';
$labels['globalonly'] = 'Csak központi címjegyzék';
$messages['bookdeleteconfirm']  = 'Biztos benne, hogy törölni szeretné a kiválasztott címjegyzékett a benne lévő összes kapcsolattal?';
$messages['bookdeleting'] = 'Címjegyzék törlése...';
$messages['booksaving'] = 'Címjegyzék mentése...';
$messages['bookdeleted'] = 'Címjegyzék sikeresen törölve.';
$messages['bookupdated'] = 'Címjegyzék sikeresen frissítve.';
$messages['bookcreated'] = 'Címjegyzék sikeresen létrehozva.';
$messages['bookdeleteerror'] = 'A címjegyzék törlése során hiba lépett fel.';
$messages['bookupdateerror'] = 'A címjegyzék frissítése során hiba lépett fel.';
$messages['bookcreateerror'] = 'A címjegyzék létrehozása során hiba lépett fel.';
$messages['nobooknamewarning'] = 'Kérem, adja meg a címjegyzék nevét.';
$messages['noemailnamewarning'] = 'Kérem, adja meg az e-mail címet vagy a kapcsolat nevét.';
?>
