<?php
/**
 * Localizations for the Kolab Address Book plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_addressbook/
 */
$labels['initials'] = 'Iniziali';
$labels['profession'] = 'Professione';
$labels['officelocation'] = 'Office location';
$labels['children'] = 'Figli';
$labels['pgppublickey'] = 'Chiave pubblica PGP';
$labels['pkcs7publickey'] = 'Chiave pubblica S/MIME';
$labels['freebusyurl'] = 'URL Free-busy';
$labels['typebusiness'] = 'Lavoro';
$labels['typebusinessfax'] = 'Fax Ufficio';
$labels['typecompany'] = 'Azienda';
$labels['typeprimary'] = 'Principale';
$labels['typetelex'] = 'Telex';
$labels['typeradio'] = 'Radio';
$labels['typeisdn'] = 'ISDN';
$labels['typettytdd'] = 'TTY/TDD';
$labels['typecallback'] = 'Callback';
$labels['settings'] = 'Impostazioni';
$labels['bookcreate'] = 'Crea rubrica';
$labels['bookedit'] = 'Modifica rubrica';
$labels['bookdelete'] = 'Elimina rubrica';
$labels['bookremove'] = 'Rimuovi dalla lista';
$labels['bookproperties'] = 'Proprietà rubrica';
$labels['bookname'] = 'Nome rubrica';
$labels['parentbook'] = 'Rubrica genitore';
$labels['bookshowurl'] = 'Mostra URL CardDAV';
$labels['carddavurldescription'] = 'Copia questo indirizzo su una applicazione client  <a href="http://en.wikipedia.org/wiki/CardDAV" target="_blank">CardDAV</a> per sincronizzare completamente questa specifica rubrica con il tuo computer o dispositivo mobile.';
$labels['addressbookprio'] = 'Selezione/comportamento rubrica/che';
$labels['personalfirst'] = 'Usa prima rubrica/che personale/i';
$labels['globalfirst'] = 'Usa prima rubrica/che globale/i';
$labels['personalonly'] = 'Usa solo rubrica/che personale/i';
$labels['globalonly'] = 'Usa solo rubrica/che globale/i';
$labels['findaddressbooks'] = 'Torva rubrica';
$labels['searchterms'] = 'Cerca elemento';
$labels['listsearchresults'] = 'Rubriche aggiuntive';
$labels['foldersearchform'] = 'Modulo ricerca rubrica';
$labels['foldersubscribe'] = 'Elenca sempre';
$labels['nraddressbooksfound'] = 'trovate $nr rubriche';
$labels['noaddressbooksfound'] = 'Nessuna rubrica trovata';
$labels['objectchangelog'] = 'Storico modifiche';
$labels['objectdiffnotavailable'] = 'Nessun confronto possibile tra le revisioni selezionate';
$messages['bookdeleteconfirm']  = 'Vuoi veramente eliminare la rubrica selezionata con tutti i contatti attualmente presenti?';
$messages['bookdeleting'] = 'Eliminazione rubrica...';
$messages['booksaving'] = 'Salvataggio rubrica...';
$messages['bookdeleted'] = 'Rubrica eliminata con successo.';
$messages['bookupdated'] = 'Rubrica aggiornata con successo.';
$messages['bookcreated'] = 'Rubrica creata con successo.';
$messages['bookdeleteerror'] = 'Si è verificato un errore durante l\'eliminazione della rubrica.';
$messages['bookupdateerror'] = 'Si è verificato un errore durante l\'aggiornamento della rubrica.';
$messages['bookcreateerror'] = 'Si è verificato un errore durante la creazione della rubrica.';
$messages['nobooknamewarning'] = 'Inserire il nome della rubrica.';
$messages['noemailnamewarning'] = 'Inserire l\'indirizzo email o il nome del contatto.';
?>
