<?php
/**
 * Localizations for the Kolab Address Book plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_addressbook/
 */
$labels['bookremove'] = 'Dzēst no saraksta';
$labels['searchterms'] = 'Meklēšanas nosacījumi';
$labels['foldersubscribe'] = 'Rādīt sarakstā vienmēr';
$labels['objectchangelog'] = 'Mainīt vēsturi';
$labels['objectdiff'] = 'Izmaiņas no $rev1 uz $rev2';
$labels['objectdiffnotavailable'] = 'Izvēlētās versijas nav salīdzināmas';
$labels['objectrestoresuccess'] = 'Versija $rev veiksmīgi atjaunota';
$labels['objectrestoreerror'] = 'Kļūda atjaunojot veco versiju';
$messages['nobooknamewarning'] = 'Lūdzu, ievadiet adrešu grāmatas nosaukumu.';
$messages['noemailnamewarning'] = 'Lūdzu, ievadiet e-pasta adresi vai kontaktpersonas vārdu.';
?>
