<?php
/**
 * Localizations for the Kolab Address Book plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_addressbook/
 */
$labels['initials'] = 'Initialen';
$labels['profession'] = 'Beroep';
$labels['officelocation'] = 'Kantoorlocatie';
$labels['children'] = 'Kinderen';
$labels['pgppublickey'] = 'Openbare PGP-sleutel';
$labels['pkcs7publickey'] = 'Openbare S/MIME-sleutel';
$labels['freebusyurl'] = 'URL Beschikbaar/Bezet';
$labels['typebusiness'] = 'Zakelijk';
$labels['typebusinessfax'] = 'Fax op werk';
$labels['typecompany'] = 'Bedrijf';
$labels['typeprimary'] = 'Primair';
$labels['typetelex'] = 'Telex';
$labels['typeradio'] = 'Radio';
$labels['typeisdn'] = 'ISDN';
$labels['typettytdd'] = 'TTY/TDD';
$labels['typecallback'] = 'Terugbellen';
$labels['settings'] = 'Instellingen';
$labels['bookcreate'] = 'Adresboek maken';
$labels['bookedit'] = 'Adresboek bewerken';
$labels['bookdelete'] = 'Adresboek verwijderen';
$labels['bookremove'] = 'Verwijderen uit lijst';
$labels['bookproperties'] = 'Adresboekeigenschappen';
$labels['bookname'] = 'Adresboeknaam';
$labels['parentbook'] = 'Primair adresboek';
$labels['bookshowurl'] = 'CardDAV-URL tonen';
$labels['carddavurldescription'] = 'Kopieer dit adres naar een <a href="http://en.wikipedia.org/wiki/CardDAV" target="_blank">CardDAV</a>-client om dit specifieke adresboek volledig te synchroniseren met uw computer of mobiele apparaat.';
$labels['addressbookprio'] = 'Selectie/gedrag van adresboek(en)';
$labels['personalfirst'] = 'Eerst persoonlijke adresboeken';
$labels['globalfirst'] = 'Eerst algemene adresboeken';
$labels['personalonly'] = 'Alleen persoonlijke adresboeken';
$labels['globalonly'] = 'Alleen algemene adresboeken';
$labels['findaddressbooks'] = 'Adresboeken zoeken';
$labels['searchterms'] = 'Zoektermen';
$labels['listsearchresults'] = 'Extra adresboeken';
$labels['foldersearchform'] = 'Zoekformulier voor adresboeken';
$labels['foldersubscribe'] = 'Definitief weergeven';
$labels['nraddressbooksfound'] = '$nr adresboeken gevonden';
$labels['noaddressbooksfound'] = 'Geen adresboeken gevonden';
$labels['showhistory'] = 'Geschiedenis tonen';
$labels['objectchangelog'] = 'Geschiedenis wijzigen';
$labels['objectdiff'] = 'Wijzigingen van $rev1 tot $rev2';
$labels['revisionrestoreconfirm'] = 'Weet u zeker dat u revisie $rev van deze contactpersoon wilt herstellen? Met deze actie vervangt u de huidige contactpersoon door de oude versie.';
$labels['objectnotfound'] = 'Laden van contactpersoonsgegevens is mislukt';
$labels['objectchangelognotavailable'] = 'Voor deze contactpersoon kunt u de geschiedenis niet wijzigen';
$labels['objectdiffnotavailable'] = 'Geen vergelijking mogelijk voor de geselecteerde revisies';
$labels['objectrestoresuccess'] = 'Revisie $rev met succes hersteld';
$labels['objectrestoreerror'] = 'Herstellen van oude revisie is mislukt';
$messages['bookdeleteconfirm']  = 'Weet u zeker dat u het geselecteerde adresboek en alle contactpersonen erin wilt verwijderen?';
$messages['bookdeleting'] = 'Adresboek verwijderen...';
$messages['booksaving'] = 'Adresboek opslaan...';
$messages['bookdeleted'] = 'Adresboek is met succes verwijderd.';
$messages['bookupdated'] = 'Adresboek is met succes bijgewerkt.';
$messages['bookcreated'] = 'Adresboek is met succes gemaakt.';
$messages['bookdeleteerror'] = 'Er is een fout opgetreden tijdens de verwijdering van het adresboek.';
$messages['bookupdateerror'] = 'Er is een fout opgetreden tijdens het bijwerken van het adresboek.';
$messages['bookcreateerror'] = 'Er is een fout opgetreden tijdens het maken van het adresboek.';
$messages['nobooknamewarning'] = 'Voer een naam voor het adresboek in.';
$messages['noemailnamewarning'] = 'Voor een e-mailadres of een naam van een contactpersoon in.';
?>
