<?php
/**
 * Localizations for the Kolab Address Book plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_addressbook/
 */
$labels['initials'] = 'Iniciais';
$labels['profession'] = 'Profissão';
$labels['officelocation'] = 'Local de trabalho';
$labels['children'] = 'Crianças';
$labels['pgppublickey'] = 'Chave pública PGP';
$labels['pkcs7publickey'] = 'Chave pública S/MIME';
$labels['freebusyurl'] = 'URL livre-ocupado';
$labels['typebusiness'] = 'Comercial';
$labels['typebusinessfax'] = 'Fax Comercial';
$labels['typecompany'] = 'Empresa';
$labels['typeprimary'] = 'Primário';
$labels['typetelex'] = 'Telex';
$labels['typeradio'] = 'Rádio';
$labels['typeisdn'] = 'ISDN';
$labels['typettytdd'] = 'TTY/TDD';
$labels['typecallback'] = 'Chamada de retorno';
$labels['settings'] = 'Configurações';
$labels['bookcreate'] = 'Criar catálogo de endereços';
$labels['bookedit'] = 'Editar catálogo de endereços';
$labels['bookdelete'] = 'Remover catálogo de endereços';
$labels['bookremove'] = 'Remove from list';
$labels['bookproperties'] = 'Propriedades do catálogo de endereços';
$labels['bookname'] = 'Nome do catálogo';
$labels['parentbook'] = 'Catalogo superior';
$labels['bookshowurl'] = 'Exibir URL do CardDAV';
$labels['carddavurldescription'] = 'Copie este endereço em um aplicativo cliente <a href="http://en.wikipedia.org/wiki/CardDAV" target="_blank">CardDav</a> para que possa sincronizar este específico endereço para seu computador ou dispositivo móvel.';
$labels['addressbookprio'] = 'Seleção/comportamento do(s) catálogo de endereços';
$labels['personalfirst'] = 'Catálogo(s) de endereço primeiro ';
$labels['globalfirst'] = 'Catálogo de endereço(s) global primeiro';
$labels['personalonly'] = 'Catálogo de endereço(s) pessoal apenas';
$labels['globalonly'] = 'Catálogo(s) de endereço global apenas';
$labels['searchterms'] = 'Search terms';
$labels['foldersubscribe'] = 'Listar permanentemente';
$labels['objectchangelog'] = 'Mudar Histórico';
$messages['bookdeleteconfirm']  = 'Você realmente gostaria de remover o catálogo de endereços selecionado e todos os contatos que estão dentro dele?';
$messages['bookdeleting'] = 'Removendo catálogo de endereço...';
$messages['booksaving'] = 'Salvando catálogo de endereço...';
$messages['bookdeleted'] = 'Catálogo de endereço removido com sucesso.';
$messages['bookupdated'] = 'Catálogo de endereço atualizado com sucesso.';
$messages['bookcreated'] = 'Catálogo de endereço criado com sucesso.';
$messages['bookdeleteerror'] = 'Ocorreu um erro ao remover o catálogo de endereço.';
$messages['bookupdateerror'] = 'Ocorreu um erro ao atualizar o catálogo de endereço.';
$messages['bookcreateerror'] = 'Ocorreu um erro ao criar o catálogo de endereço.';
$messages['nobooknamewarning'] = 'Por favor, insira um nome para o catálogo de endereço.';
$messages['noemailnamewarning'] = 'Por favor, insira um e-mail ou nome para o contato.';
?>
