<?php
/**
 * Localizations for the Kolab Address Book plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_addressbook/
 */
$labels['initials'] = 'Iniciais';
$labels['profession'] = 'Profissão';
$labels['officelocation'] = 'Localização de escritório';
$labels['children'] = 'Criança';
$labels['pgppublickey'] = 'chave pública GPG';
$labels['pkcs7publickey'] = 'chave pública S/MIME';
$labels['freebusyurl'] = 'URL Livre-ocupado ';
$labels['typebusiness'] = 'Negócio';
$labels['typebusinessfax'] = 'Fax empresárial';
$labels['typecompany'] = 'Empresa';
$labels['typeprimary'] = 'Primário';
$labels['typeradio'] = 'Rádio';
$labels['typeisdn'] = 'RDSI';
$labels['settings'] = 'Definições';
$labels['bookcreate'] = 'Criar contacto';
$labels['bookedit'] = 'Editar contacto';
$labels['bookdelete'] = 'Apagar contacto';
$labels['bookremove'] = 'Remove from list';
$labels['bookproperties'] = 'Propriedades do contacto';
$labels['bookname'] = 'Nome do livro';
$labels['parentbook'] = 'Livro superior';
$labels['bookshowurl'] = 'Mostrar CardDAV URL';
$labels['carddavurldescription'] = 'Copie este endereço <a href="http://en.wikipedia.org/wiki/CardDAV" target="_blank">CardDAV</a> para uma aplicação cliente para sincronizar totalmente este contacto com o seu computador ou dispositivo móvel.';
$labels['addressbookprio'] = 'Selecção/comportamento do contacto(s)';
$labels['personalfirst'] = 'Contacto(s) pessoais primeiro';
$labels['searchterms'] = 'Search terms';
$labels['foldersubscribe'] = 'Listar permanentemente';
$labels['objectchangelog'] = 'Alterar histórico';
$labels['objectdiff'] = 'Diferenças entre $rev1 e $rev2';
$labels['objectdiffnotavailable'] = 'Não é possível comparar as versões selecionadas';
$labels['objectrestoresuccess'] = 'A versão $rev foi reposta com sucesso.';
$labels['objectrestoreerror'] = 'Não foi possível repor a versão anterior.';
?>
