<?php
/**
 * Localizations for the Kolab Address Book plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_addressbook/
 */
$labels['initials'] = 'Инициалы';
$labels['profession'] = 'Профессия';
$labels['officelocation'] = 'Адрес офиса';
$labels['children'] = 'Дети';
$labels['pgppublickey'] = 'Публичный ключ PGP';
$labels['pkcs7publickey'] = 'Публичный ключ S/MIME';
$labels['freebusyurl'] = 'URL свободен/занят';
$labels['typebusiness'] = 'Служебный';
$labels['typebusinessfax'] = 'Служебный факс';
$labels['typecompany'] = 'Организация';
$labels['typeprimary'] = 'Основной(ая)';
$labels['typetelex'] = 'Telex';
$labels['typeradio'] = 'Радиотелефон';
$labels['typeisdn'] = 'ISDN';
$labels['typettytdd'] = 'TTY/TDD';
$labels['typecallback'] = 'Коллбэк';
$labels['settings'] = 'Настройки';
$labels['bookcreate'] = 'Создать адресную книгу';
$labels['bookedit'] = 'Редактировать адресную книгу';
$labels['bookdelete'] = 'Удалить адресную книгу';
$labels['bookremove'] = 'Удалить из списка';
$labels['bookproperties'] = 'Параметры адресной книги';
$labels['bookname'] = 'Название книги';
$labels['parentbook'] = 'Родительская книга';
$labels['bookshowurl'] = 'Показать URL CardDAV';
$labels['carddavurldescription'] = 'Скопируйте этот адрес в клиент, <a href="http://en.wikipedia.org/wiki/CardDAV" target="_blank">поддерживающий CardDAV</a> для полной синхронизации данной адресной книги со своим компьютером или мобильным устройством.';
$labels['addressbookprio'] = 'Поведение/отображение адресных книг';
$labels['personalfirst'] = 'Персональные адресные книги в начале';
$labels['globalfirst'] = 'Глобальные адресные книги в начале';
$labels['personalonly'] = 'Только персональные адресные книги';
$labels['globalonly'] = 'Только глобальные адресные книги';
$labels['findaddressbooks'] = 'Найти адресные книги';
$labels['searchterms'] = 'Условия поиска';
$labels['listsearchresults'] = 'Дополнительные адресные книги';
$labels['foldersearchform'] = 'Форма поиска адресных книг';
$labels['foldersubscribe'] = 'Всегда показывать';
$labels['nraddressbooksfound'] = '$nr адресных книг найдено';
$labels['noaddressbooksfound'] = 'Адресных книг не найдено';
$labels['showhistory'] = 'Показать Историю';
$labels['objectchangelog'] = 'История изменений';
$labels['objectdiff'] = 'Изменения с $rev1 до $rev2';
$labels['revisionrestoreconfirm'] = 'Вы уверенны, что хотите восстановить этот контакт из ревизии $rev? Он заменит текущее контакт старой версией. ';
$labels['objectnotfound'] = 'Не удалось загрузить информацию о контакте';
$labels['objectchangelognotavailable'] = 'История изменений для этого контакта недоступна';
$labels['objectdiffnotavailable'] = 'Невозможно провести сравнение выбранных ревизий ';
$labels['objectrestoresuccess'] = 'Ревизия $rev успешно восстановлена';
$labels['objectrestoreerror'] = 'Не удалось восстановить старую ревизию';
$messages['bookdeleteconfirm']  = 'Вы действительно хотите удалить выбранную адресную книгу и все контакты в ней?';
$messages['bookdeleting'] = 'Удаление адресной книги...';
$messages['booksaving'] = 'Сохранение адресной книги...';
$messages['bookdeleted'] = 'Адресная книга успешно удалена.';
$messages['bookupdated'] = 'Адресная книга успешно обновлена.';
$messages['bookcreated'] = 'Адресная книга успешно создана.';
$messages['bookdeleteerror'] = 'Возникла ошибка при удалении адресной книги.';
$messages['bookupdateerror'] = 'Возникла ошибка при обновлении адресной книги.';
$messages['bookcreateerror'] = 'Возникла ошибка при создании адресной книги.';
$messages['nobooknamewarning'] = 'Пожалуйста, заполните название книги.';
$messages['noemailnamewarning'] = 'Пожалуйста, заполните почтовый адрес или имя контакта.';
?>
