<?php
/**
 * Localizations for the Kolab Address Book plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_addressbook/
 */
$labels['bookremove'] = 'Odstrani iz seznama';
$labels['searchterms'] = 'Iskalni pogoji';
$labels['foldersubscribe'] = 'Označi za vedno';
$labels['objectchangelog'] = 'Spremeni Zgodovino';
$labels['objectdiffnotavailable'] = 'Primerjava za izbrane verzije ni na voljo';
?>
