<?php
/**
 * Localizations for the Kolab Address Book plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_addressbook/
 */
$labels['bookremove'] = 'Ta bort från lista';
$labels['searchterms'] = 'Sökord';
$labels['foldersubscribe'] = 'Lista permanent';
$labels['objectchangelog'] = 'Ändringshistorik';
$labels['objectdiffnotavailable'] = 'Ingen jämförelse möjlig för valda revisioner';
?>
