<?php
/**
 * Localizations for the Kolab Address Book plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_addressbook/
 */
$labels['initials'] = 'ชื่อย่อ';
$labels['profession'] = 'อาชีพ';
$labels['officelocation'] = 'สถานที่ที่ทำงาน';
$labels['pgppublickey'] = 'กุญแจ PGP สาธารณะ';
$labels['pkcs7publickey'] = 'กุญแจ S/MIME สาธารธะ';
$labels['freebusyurl'] = 'ลิงค์ ว่าง-ติดธุระ';
$labels['typebusiness'] = 'ธุรกิจ';
$labels['typebusinessfax'] = 'โทรสาร ธุรกิจ';
$labels['typecompany'] = 'บริษัท';
$labels['typetelex'] = 'เทเลกซ์';
$labels['typeradio'] = 'วิทยุ';
$labels['typeisdn'] = 'รหัส ISDN';
$labels['typecallback'] = 'บริการเรียกกลับ';
$labels['settings'] = 'การตั้งค่า';
$labels['bookcreate'] = 'สร้างสมุดรายชื่อ';
$labels['bookedit'] = 'แก้ไขสมุดรายชื่อ';
$labels['bookdelete'] = 'ลบสมุดรายชื่อ';
$labels['bookremove'] = 'ลบออกจากรายชื่อ';
$labels['bookproperties'] = 'คุณสมบัติของสมุดรายชื่อ';
$labels['bookname'] = 'ชื่อสมุด';
$labels['bookshowurl'] = 'แสดงลิงค์ CardDAV';
$labels['carddavurldescription'] = 'คัดลอกลิงค์ที่อยู่นี้ไปยัง <a href="http://en.wikipedia.org/wiki/CardDAV" target="_blank">CardDAV</a> โปรแกรมที่เครื่องลูกข่ายเพื่อซิงค์ข้อมูลในสมุดที่อยู่ฉบับนี้กับคอมพิวเตอร์หรืออุปกรณ์มือถือของท่าน';
$labels['personalfirst'] = 'สมุดที่อยู่ส่วนตัวก่อน';
$labels['personalonly'] = 'สมุดที่อยู่ส่วนตัวเท่านั้น';
$labels['findaddressbooks'] = 'ค้นหาสมุดที่อยู่';
$labels['searchterms'] = 'ข้อความที่ต้องการค้นหา';
$labels['listsearchresults'] = 'สมุดที่อยู่เพิ่มเติม';
$labels['foldersearchform'] = 'ฟอร์มค้นหาสมุดที่อยู่';
$labels['foldersubscribe'] = 'แสดงเป็นรายการถาวร';
$labels['nraddressbooksfound'] = 'พบ สมุดที่อยุ่จำนวน $nr เล่ม';
$labels['noaddressbooksfound'] = 'ไม่พบสมุดที่อยุ่';
$labels['objectchangelog'] = 'ประวัติการปรับเปลี่ยน';
$labels['objectdiffnotavailable'] = 'ไม่สามารถเปรียบเทียบรุ่นการปรับปรุงที่เลือกได้';
$messages['bookdeleteconfirm']  = 'คุณต้องการลบสมุดที่อยู่ดังกล่าวพร้อมรายชื่อผู้ติดต่อในนั้นหรือ';
$messages['bookdeleting'] = 'ลบสมุดที่อยู่';
$messages['booksaving'] = 'บันทึกสมุดที่อยุ่';
$messages['bookdeleted'] = 'ลบสมุดที่อยู่เรียบร้อยแล้ว';
$messages['bookupdated'] = 'ปรับปรุงสมุดที่อยู่เรียบร้อยแล้ว';
$messages['bookcreated'] = 'สร้างสมุดที่อยู่เรียบร้อยแล้ว';
$messages['bookdeleteerror'] = 'เกิดข้อผิดพลาดในระหว่างลบสมุดที่อยู่';
$messages['bookupdateerror'] = 'เกิดข้อผิดพลาดในระหว่า่งปรับปรุงสมุดที่อยู่';
$messages['bookcreateerror'] = 'เกิดข้อผิดพลาดในระหว่างสร้างสมุดที่อยุ่';
$messages['nobooknamewarning'] = 'กรุณาป้อนชื่อสมุดบันทึกที่อยู่';
$messages['noemailnamewarning'] = 'กรุณาป้อน อีเมล์ และ ชื่อผู้ติดต่อ';
?>
