<?php
/**
 * Localizations for the Kolab Address Book plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_addressbook/
 */
$labels['settings'] = 'Налаштування';
$labels['bookremove'] = 'Вилучити зі списку';
$labels['searchterms'] = 'Умови пошуку';
$labels['foldersubscribe'] = 'Завжди показувати';
$labels['objectchangelog'] = 'Історія змін';
?>
