<?php
$labels['tabtitle'] = 'Activesync';
$labels['devices'] = 'Устройства';
$labels['devicealias'] = 'Име на устройство';
$labels['synchronize'] = 'Синхронизиране';
$labels['withalarms'] = 'С аларми';
$labels['syncsettings'] = 'Настройки на синхронизация';
$labels['folderstosync'] = 'Папки за синхронизиране';
$labels['mail'] = 'Електронна поща';
$labels['contact'] = 'Адресни книги';
$labels['event'] = 'Календари';
$labels['task'] = 'Задачи';
$labels['note'] = 'Бележки';
$labels['configuration'] = 'Конфигурация';
$labels['deletedevice'] = 'Изтриване на устройство';
$labels['savingdata'] = 'Запазване на данни...';
$labels['savingerror'] = 'Неуспех при запазване на конфигурацията';
$labels['notsupported'] = 'Your server does not support metadata/annotations';
$labels['devicedeleteconfirm'] = 'Наистина ли искате да изтриете конфигурацията за това устройство?';
$labels['successfullydeleted'] = 'Конфигурацията за устройството беше премахната успешно';
$labels['devicenotfound'] = 'Невъзможно прочитането на конфигурацията на устройството';
?>
