<?php

$labels['tabtitle'] = 'Activesync';
$labels['activesynctitle'] = 'Manage Activesync devices';
$labels['devices'] = 'Devices';
$labels['devicealias'] = 'Device name';
$labels['synchronize'] = 'Synchronize';
$labels['withalarms'] = 'With alarms';
$labels['syncsettings'] = 'Synchronization settings';
$labels['deviceconfig'] = 'Device configuration';
$labels['folderstosync'] = 'Folders to synchronize';
$labels['mail'] = 'Email';
$labels['contact'] = 'Address Books';
$labels['event'] = 'Calendars';
$labels['task'] = 'Tasks';
$labels['note'] = 'Notes';
$labels['configuration'] = 'Configuration';
$labels['deletedevice'] = 'Delete device';
$labels['nodevices'] = 'There are currently no devices registered.<br/><br/>In order to register a device, please connect it to the server first, using instructions from <a href="$url" target="_blank">this page</a>. Afterwards the device should become available for configuration here.';
$labels['savingdata'] = 'Saving data...';
$labels['savingerror'] = 'Failed to save configuration';
$labels['notsupported'] = 'Your server does not support metadata/annotations';
$labels['devicedeleteconfirm'] = 'Do you really want to delete the configuration for this device?';
$labels['successfullydeleted'] = 'The device configuration was successfully removed';
$labels['devicenotfound'] = 'Unable to read device configuration';
$labels['devicetype'] = 'Device type';
$labels['acsversion'] = 'Protocol version';
$labels['useragent'] = 'User agent';
$labels['friendlyname'] = 'Friendly name';
$labels['os'] = 'Operating system';
$labels['oslanguage'] = 'OS language';
$labels['phonenumber'] = 'Phone number';
$labels['arialabeldeviceframe'] = 'Device synchronization settings form';

?>
