<?php
$labels['tabtitle'] = 'Activesync';
$labels['devices'] = 'Dispositivos';
$labels['devicealias'] = 'Nome do dispositivo';
$labels['synchronize'] = 'Sincronizar';
$labels['withalarms'] = 'Com alarmes';
$labels['syncsettings'] = 'Sincronizar configurações';
$labels['folderstosync'] = 'Pastas para sincronizar';
$labels['mail'] = 'Email';
$labels['contact'] = 'Catálogo de Endereços';
$labels['event'] = 'Calendários';
$labels['task'] = 'Tarefas';
$labels['note'] = 'Notas';
$labels['configuration'] = 'Configuração';
$labels['deletedevice'] = 'Remover dispositivo';
$labels['savingdata'] = 'Salvando dados...';
$labels['savingerror'] = 'Falha ao salvar a configuração';
$labels['notsupported'] = 'Seu servidor não suporta metadados/anotações';
$labels['devicedeleteconfirm'] = 'Você deseja realmente remover a configuração deste dispositivo?';
$labels['successfullydeleted'] = 'A configuração do dispositivo foi removida com sucesso';
$labels['devicenotfound'] = 'Não foi possível ler a configuração do dispositivo';
$labels['phonenumber'] = 'Telefone';
?>
