<?php
$labels['tabtitle'] = 'Activesync';
$labels['activesynctitle'] = 'Gerir dispositivos Activesync';
$labels['devices'] = 'Dispostivos';
$labels['devicealias'] = 'Nome do Dispositivo';
$labels['synchronize'] = 'Sincronizar';
$labels['withalarms'] = 'Com alarme';
$labels['syncsettings'] = 'Definições de sincronização';
$labels['deviceconfig'] = 'Configuração de dispositivo';
$labels['folderstosync'] = 'Pastas a sincronizar';
$labels['mail'] = 'Email';
$labels['contact'] = 'Livro de Contactos';
$labels['event'] = 'Calendários';
$labels['task'] = 'Tarefas';
$labels['note'] = 'Notas';
$labels['configuration'] = 'Configuração';
$labels['deletedevice'] = 'Remover dispositivo';
$labels['savingdata'] = 'A guardar os dados...';
$labels['savingerror'] = 'Falha ao guardar as alterações.';
?>
