<?php
/**
 * Localizations for the Kolab Delegation plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_delegation/
 */
$labels['mail'] = 'Електронна поща';
$labels['contact'] = 'Адресни книги';
$labels['event'] = 'Календари';
$labels['task'] = 'Задачи';
$labels['note'] = 'Бележки';
$labels['savingdata'] = 'Запазване на данни...';
?>
