<?php
/**
 * Localizations for the Kolab Delegation plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_delegation/
 */
$labels['tabtitle'] = 'Zastupování';
$labels['delegationtitle'] = 'Spravovat zástupce';
$labels['delegates'] = 'Zástupci';
$labels['delegate'] = 'Zástupce';
$labels['mail'] = 'E-mail';
$labels['contact'] = 'Adresáře';
$labels['event'] = 'Kalendáře';
$labels['task'] = 'Úkoly';
$labels['note'] = 'Poznámky';
$labels['yes'] = 'Ano';
$labels['no'] = 'Ne';
$labels['read'] = 'Pouze pro čtení';
$labels['write'] = 'Zapsat';
$labels['adddelegate'] = 'Přidat zástupce';
$labels['deletedelegate'] = 'Smazat zástupce';
$labels['savingdata'] = 'Ukládají se data...';
$labels['delegatedeleteconfirm'] = 'Opravdu chcete smazat tohoto zástupce?';
$labels['delegateremoveacl'] = 'Odstranit přístupová oprávnění ke složkám přiděleným tomuto uživateli';
$labels['deleteconfirm'] = 'Potvrzení';
$labels['deletesuccess'] = 'Zástupce byl úspěšně odebrán.';
$labels['deleteerror'] = 'Nepodařilo se odebrat zástupce.';
$labels['updatesuccess'] = 'Zástupce byl úspěšně aktualizován.';
$labels['updateerror'] = 'Zástupce se nepodařilo aktualizovat.';
$labels['createsuccess'] = 'Zástupce byl úspěšně přidán.';
$labels['createerror'] = 'Zástupce se nepodařilo přidat.';
$labels['arialabeldelegatedelete'] = 'Dialog pro smazání zástupce';
$labels['arialabeldelegateform'] = 'Vlastnosti zástupce';
?>
