<?php
/**
 * Localizations for the Kolab Delegation plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_delegation/
 */
$labels['tabtitle'] = 'Delegering';
$labels['delegationtitle'] = 'Manage delegates';
$labels['delegates'] = 'Delegerede';
$labels['delegate'] = 'Delegér';
$labels['mail'] = 'E-post';
$labels['contact'] = 'Adressebøger';
$labels['event'] = 'Kalendere';
$labels['task'] = 'Opgaver';
$labels['note'] = 'Noter';
$labels['yes'] = 'Ja';
$labels['no'] = 'Nej';
$labels['read'] = 'Skrivebeskyttet';
$labels['write'] = 'Skriv';
$labels['adddelegate'] = 'Tilføj delegeret';
$labels['deletedelegate'] = 'Slet delegeret';
$labels['savingdata'] = 'Gemmer data...';
$labels['delegatedeleteconfirm'] = 'Sikker på du vil slette denne delegerede?';
$labels['delegateremoveacl'] = 'fjern adgangsrettigheder til mapper tildelt denne bruger';
$labels['deleteconfirm'] = 'Bekræftelse';
$labels['deletesuccess'] = 'Gennemførte fjernelsen af delegerede.';
$labels['deleteerror'] = 'Kunne ikke fjerne delegerede.';
$labels['updatesuccess'] = 'Gennemførte opdatering af delegerede.';
$labels['updateerror'] = 'Kunne ikke opdatere delegerede.';
$labels['createsuccess'] = 'Gennemførte tilføjelse af den delegerede.';
$labels['createerror'] = 'Kunne ikke tilføje delegerede.';
$labels['arialabeldelegatedelete'] = 'Vindue til sletning af delegeret';
$labels['arialabeldelegateform'] = 'Formular med egenskaber for delegeret';
?>
