<?php
/**
 * Localizations for the Kolab Delegation plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_delegation/
 */
$labels['tabtitle'] = 'Vertretung';
$labels['delegationtitle'] = 'Verwalte Vertreter';
$labels['delegates'] = 'Vertreter';
$labels['delegate'] = 'Vertreter';
$labels['mail'] = 'E-Mail';
$labels['contact'] = 'Kontakte';
$labels['event'] = 'Kalender';
$labels['task'] = 'Aufgaben';
$labels['note'] = 'Notizen';
$labels['yes'] = 'Ja';
$labels['no'] = 'Nein';
$labels['read'] = 'Schreibgeschützt';
$labels['write'] = 'Schreiben';
$labels['adddelegate'] = 'Vertreter hinzufügen';
$labels['deletedelegate'] = 'Vertreter löschen';
$labels['savingdata'] = 'Speichere Daten...';
$labels['delegatedeleteconfirm'] = 'Wollen Sie diesen Vertreter wirklich löschen?';
$labels['delegateremoveacl'] = 'Zugriffsrechte von diesem Benutzer zugeordneten Ordnern entfernen';
$labels['deleteconfirm'] = 'Bestätigung';
$labels['deletesuccess'] = 'Der Vertreter wurde erfolgreich entfernt.';
$labels['deleteerror'] = 'Vertreter konnte nicht entfernt werden.';
$labels['updatesuccess'] = 'Der Vertreter wurde erfolgreich aktualisiert.';
$labels['updateerror'] = 'Vertreter konnte nicht aktualisiert werden.';
$labels['createsuccess'] = 'Der Vertreter wurde erfolgreich hinzugefügt.';
$labels['createerror'] = 'Vertreter konnte nicht hinzugefügt werden.';
$labels['arialabeldelegatedelete'] = 'Vertreter Löschen Dialog';
$labels['arialabeldelegateform'] = 'Verterter Eigenschaften Maske';
?>
