<?php
/**
 * Localizations for the Kolab Delegation plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_delegation/
 */
$labels['mail'] = 'Ηλεκτρονική αλληλογραφία';
$labels['contact'] = 'Βιβλίο διευθύνσεων';
$labels['event'] = 'Ημερολόγια';
$labels['task'] = 'Εργασίες';
$labels['note'] = 'Σημειώσεις';
$labels['yes'] = 'Ναι';
$labels['no'] = 'Όχι';
$labels['write'] = 'Εγγραφή';
$labels['savingdata'] = 'Αποθήκευση δεδομένων...';
?>
