<?php

/**
 * Localizations for the Kolab Delegation plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_delegation/
 */

$labels = array();

$labels['tabtitle'] = 'Delegation';
$labels['delegationtitle'] = 'Manage delegates';
$labels['delegates'] = 'Delegates';
$labels['delegate'] = 'Delegate';
$labels['mail'] = 'Email';
$labels['contact'] = 'Address Books';
$labels['event'] = 'Calendars';
$labels['task'] = 'Tasks';
$labels['note'] = 'Notes';
$labels['yes'] = 'Yes';
$labels['no'] = 'No';
$labels['read'] = 'Read-only';
$labels['write'] = 'Write';
$labels['adddelegate'] = 'Add delegate';
$labels['deletedelegate'] = 'Delete delegate';
$labels['savingdata'] = 'Saving data...';
$labels['delegatedeleteconfirm'] = 'Do you really want to delete this delegate?';
$labels['delegateremoveacl'] = 'remove access rights on folders assigned to this user';
$labels['deleteconfirm'] = 'Confirmation';
$labels['deletesuccess'] = 'The delegate was successfully removed.';
$labels['deleteerror'] = 'Could not remove delegate.';
$labels['updatesuccess'] = 'The delegate was successfully updated.';
$labels['updateerror'] = 'Could not update delegate.';
$labels['createsuccess'] = 'The delegate was successfully added.';
$labels['createerror'] = 'Could not add delegate.';

$labels['arialabeldelegatedelete'] = 'Delegate deletion dialog';
$labels['arialabeldelegateform'] = 'Delegate properties form';

?>
