<?php
/**
 * Localizations for the Kolab Delegation plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_delegation/
 */
$labels['tabtitle'] = 'Delegación';
$labels['delegationtitle'] = 'Administrar delegados';
$labels['delegates'] = 'Delegados';
$labels['delegate'] = 'Delegado';
$labels['mail'] = 'Correo electrónico';
$labels['contact'] = 'Libreta de direcciones';
$labels['event'] = 'Calendarios';
$labels['task'] = 'Tareas';
$labels['note'] = 'Notas';
$labels['yes'] = 'Si';
$labels['no'] = 'No';
$labels['read'] = 'Sólo lectura';
$labels['write'] = 'Escribir';
$labels['adddelegate'] = 'Agregar delegado';
$labels['deletedelegate'] = 'Eliminar delegado';
$labels['savingdata'] = 'Guardando...';
$labels['delegatedeleteconfirm'] = 'Confirme que desea eliminar este delegado';
$labels['delegateremoveacl'] = 'eliminar derechos de acceso a las carpetas asignadas a este usuario';
$labels['deleteconfirm'] = 'Confirmación';
$labels['deletesuccess'] = 'El delegado fue eliminado exitosamente.';
$labels['deleteerror'] = 'No se puede eliminar el delegado.';
$labels['updatesuccess'] = 'El delegado fue actualizado exitosamente.';
$labels['updateerror'] = 'No se puede actualizar el delegado.';
$labels['createsuccess'] = 'El delegado fue agregado exitosamente.';
$labels['createerror'] = 'No se puede agregar el delegado.';
$labels['arialabeldelegatedelete'] = 'Diálogo de eliminación de delegado';
$labels['arialabeldelegateform'] = 'Formulario de propiedades del delegado';
?>
