<?php
/**
 * Localizations for the Kolab Delegation plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_delegation/
 */
$labels['tabtitle'] = 'Delegación';
$labels['delegationtitle'] = 'Gestionar delegados';
$labels['delegates'] = 'Delegados';
$labels['delegate'] = 'Delegado';
$labels['mail'] = 'Correo electrónico';
$labels['contact'] = 'Libreta de direcciones';
$labels['event'] = 'Calendarios';
$labels['task'] = 'Tareas';
$labels['note'] = 'Notas';
$labels['yes'] = 'Sí';
$labels['no'] = 'No';
$labels['read'] = 'Solo-lectura';
$labels['write'] = 'Escribir';
$labels['adddelegate'] = 'Añadir delegado';
$labels['deletedelegate'] = 'Borrar delegado';
$labels['savingdata'] = 'Guardando datos...';
$labels['delegatedeleteconfirm'] = '¿Esta seguro de eliminar este delegado?';
$labels['delegateremoveacl'] = 'retirar los derechos de acceso de todas las carpetas asignadas a este usuario';
$labels['deleteconfirm'] = 'Confirmación';
$labels['deletesuccess'] = 'El delegado se ha eliminado con éxito';
$labels['deleteerror'] = 'No es posible eliminar al delegado.';
$labels['updatesuccess'] = 'El delegado se ha actualizado con éxito.';
$labels['updateerror'] = 'No es posible actualizar al delegado.';
$labels['createsuccess'] = 'El delegado se ha añadido con éxito.';
$labels['createerror'] = 'No es posible añadir al delegado.';
$labels['arialabeldelegatedelete'] = 'Diálogo de eliminación del delegado';
$labels['arialabeldelegateform'] = 'Formulario de propiedades del delegado';
?>
