<?php
/**
 * Localizations for the Kolab Delegation plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_delegation/
 */
$labels['tabtitle'] = 'Edustus';
$labels['delegationtitle'] = 'Hallitse edustajia';
$labels['delegates'] = 'Edustajat';
$labels['delegate'] = 'Edustaja';
$labels['mail'] = 'Sähköposti';
$labels['contact'] = 'Osoitekirjat';
$labels['event'] = 'Kalenterit';
$labels['task'] = 'Tehtävät';
$labels['note'] = 'Muistiot';
$labels['yes'] = 'Kyllä';
$labels['no'] = 'Ei';
$labels['read'] = 'Vain luku';
$labels['write'] = 'Kirjoitus';
$labels['adddelegate'] = 'Lisää edustaja';
$labels['deletedelegate'] = 'Poista edustaja';
$labels['savingdata'] = 'Tallennetaan tietoja...';
$labels['delegatedeleteconfirm'] = 'Haluatko varmasti poistaa tämän edustajan?';
$labels['delegateremoveacl'] = 'poista tälle käyttäjälle kansioihin määritetyt käyttöoikeudet';
$labels['deleteconfirm'] = 'Vahvistus';
$labels['deletesuccess'] = 'Edustaja poistettiin onnistuneesti.';
$labels['deleteerror'] = 'Edustajan poistaminen ei onnistunut.';
$labels['updatesuccess'] = 'Edustaja päivitettiin onnistuneesti.';
$labels['updateerror'] = 'Edustajan päivittäminen ei onnistunut.';
$labels['createsuccess'] = 'Edustaja lisättiin onnistuneesti.';
$labels['createerror'] = 'Edustajan lisääminen ei onnistunut.';
$labels['arialabeldelegatedelete'] = 'Edustajien poistoikkuna';
$labels['arialabeldelegateform'] = 'Edustajien ominaisuuslomake';
?>
