<?php
/**
 * Localizations for the Kolab Delegation plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_delegation/
 */
$labels['tabtitle'] = 'Meghatalmazás';
$labels['delegates'] = 'Meghatalmazottak';
$labels['delegate'] = 'Meghatalmazott:';
$labels['mail'] = 'E-mail';
$labels['contact'] = 'Címjegyzékek';
$labels['event'] = 'Naptárak';
$labels['task'] = 'Feladatok';
$labels['note'] = 'Jegyzetek';
$labels['yes'] = 'Igen';
$labels['no'] = 'Nem';
$labels['read'] = 'Csak olvasásra';
$labels['write'] = 'Írásra';
$labels['adddelegate'] = 'Meghatalmazás';
$labels['deletedelegate'] = 'Meghatalmazás visszavonása';
$labels['savingdata'] = 'Adatok mentése...';
$labels['delegatedeleteconfirm'] = 'Biztos benne, hogy meg szeretné szüntetni ezt a meghatalmazást?';
$labels['delegateremoveacl'] = 'a mappákhoz megadott hozzáférések visszavonásával';
$labels['deleteconfirm'] = 'Megerősítés';
$labels['deletesuccess'] = 'A meghatalmazás sikeresen meg lett szüntetve.';
$labels['deleteerror'] = 'Nem sikerült visszavonni a meghatalmazást.';
$labels['updatesuccess'] = 'A meghatalmazás sikeresen frissítve lett.';
$labels['updateerror'] = 'Nem sikerült frissíteni a meghatalmazást.';
$labels['createsuccess'] = 'A meghatalmazás sikeresen létre lett hozva.';
$labels['createerror'] = 'Nem sikerült létrehozni a meghatalmazást.';
?>
