<?php
/**
 * Localizations for the Kolab Delegation plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_delegation/
 */
$labels['tabtitle'] = 'Deleghe';
$labels['delegationtitle'] = 'Gestisci delegati';
$labels['delegates'] = 'Delegati';
$labels['delegate'] = 'Delegato';
$labels['mail'] = 'Email';
$labels['contact'] = 'Rubriche';
$labels['event'] = 'Calendari';
$labels['task'] = 'Attività';
$labels['note'] = 'Note';
$labels['yes'] = 'Sì';
$labels['no'] = 'No';
$labels['read'] = 'Sola lettura';
$labels['write'] = 'Scrittura';
$labels['adddelegate'] = 'Aggiungi delegato';
$labels['deletedelegate'] = 'Elimina delegato';
$labels['savingdata'] = 'Salvataggio dati...';
$labels['delegatedeleteconfirm'] = 'Vuoi davvero eliminare questo delegato?';
$labels['delegateremoveacl'] = 'rimuovi i diritti di accesso alle cartelle assegnati a questo utente';
$labels['deleteconfirm'] = 'Conferma';
$labels['deletesuccess'] = 'Il delegato è stato rimosso correttamente.';
$labels['deleteerror'] = 'Impossibile rimuovere il delegato.';
$labels['updatesuccess'] = 'Il delegato è stato aggiornato correttamente.';
$labels['updateerror'] = 'Impossibile aggiornare il delegato.';
$labels['createsuccess'] = 'Il delegato è stato aggiunto correttamente.';
$labels['createerror'] = 'Impossibile aggiungere il delegato.';
$labels['arialabeldelegatedelete'] = 'Dialogo cancellazione del delegato';
$labels['arialabeldelegateform'] = 'Modulo proprietà del delegato';
?>
