<?php
/**
 * Localizations for the Kolab Delegation plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_delegation/
 */
$labels['tabtitle'] = '代理';
$labels['delegationtitle'] = '代理人の管理';
$labels['delegates'] = '代理人';
$labels['delegate'] = '代理人';
$labels['mail'] = 'Eメール';
$labels['contact'] = 'アドレス帳';
$labels['event'] = 'カレンダー';
$labels['task'] = 'タスク';
$labels['note'] = 'ノート';
$labels['yes'] = 'はい';
$labels['no'] = 'いいえ';
$labels['read'] = '読込のみ';
$labels['write'] = '書込';
$labels['adddelegate'] = '代理人を追加';
$labels['deletedelegate'] = '代理人を削除';
$labels['savingdata'] = 'データを保存中…';
$labels['delegatedeleteconfirm'] = 'この代理人を本当に削除しますか？';
$labels['delegateremoveacl'] = 'このユーザにアサインされたフォルダのアクセス権を削除しました';
$labels['deleteconfirm'] = '確認';
$labels['deletesuccess'] = '代理人の削除に成功しました';
$labels['deleteerror'] = '代理人の削除ができません。';
$labels['updatesuccess'] = '代理人の更新に成功しました。';
$labels['updateerror'] = '代理人の更新ができません。';
$labels['createsuccess'] = '代理人の追加に成功しました。';
$labels['createerror'] = '代理人の追加ができません。';
$labels['arialabeldelegatedelete'] = '代理人削除ダイアログ';
$labels['arialabeldelegateform'] = '代理人プロパティフォーム';
?>
