<?php
/**
 * Localizations for the Kolab Delegation plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_delegation/
 */
$labels['tabtitle'] = 'Delegatie';
$labels['delegationtitle'] = 'Gedelegeerden beheren';
$labels['delegates'] = 'Gedelegeerden';
$labels['delegate'] = 'Gedelegeerde';
$labels['mail'] = 'E-mail';
$labels['contact'] = 'Adresboeken';
$labels['event'] = 'Agenda\'s';
$labels['task'] = 'Taken';
$labels['note'] = 'Notities';
$labels['yes'] = 'Ja';
$labels['no'] = 'Nee';
$labels['read'] = 'Alleen-lezen';
$labels['write'] = 'Schrijven';
$labels['adddelegate'] = 'Gedelegeerde toevoegen';
$labels['deletedelegate'] = 'Gedelegeerde verwijderen';
$labels['savingdata'] = 'Gegevens opslaan...';
$labels['delegatedeleteconfirm'] = 'Weet u zeker dat u deze gedelegeerde wilt verwijderen?';
$labels['delegateremoveacl'] = 'toegangsrechten voor mappen toegewezen aan deze gebruiker verwijderen';
$labels['deleteconfirm'] = 'Bevestiging';
$labels['deletesuccess'] = 'De gedelegeerde is met succes verwijderd.';
$labels['deleteerror'] = 'De gedelegeerde kon niet worden verwijderd.';
$labels['updatesuccess'] = 'De gedelegeerde is met succes bijgewerkt.';
$labels['updateerror'] = 'De gedelegeerde kon niet worden bijgewerkt.';
$labels['createsuccess'] = 'De gedelegeerde is met succes toegevoegd.';
$labels['createerror'] = 'De gedelegeerde kon niet worden toegevoegd.';
$labels['arialabeldelegatedelete'] = 'Dialoogvenster voor verwijdering van gedelegeerde';
$labels['arialabeldelegateform'] = 'Formulier voor eigenschappen van gedelegeerde';
?>
