<?php
/**
 * Localizations for the Kolab Delegation plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_delegation/
 */
$labels['tabtitle'] = 'Delegação';
$labels['delegates'] = 'Delegados';
$labels['delegate'] = 'Delegado';
$labels['mail'] = 'E-mail';
$labels['contact'] = 'Catálogo de endereços';
$labels['event'] = 'Calendários';
$labels['task'] = 'Tarefas';
$labels['note'] = 'Notas';
$labels['yes'] = 'SIm';
$labels['no'] = 'Não';
$labels['read'] = 'Somente leitura';
$labels['write'] = 'Gravar';
$labels['adddelegate'] = 'Adicionar delegado';
$labels['deletedelegate'] = 'Remover delegado';
$labels['savingdata'] = 'Salvando dados...';
$labels['delegatedeleteconfirm'] = 'Você realmente gostaria de remover este delegado?';
$labels['delegateremoveacl'] = 'remover permissões de acesso sobre pastas assinadas por este usuário ';
$labels['deleteconfirm'] = 'Confirmação';
$labels['deletesuccess'] = 'O delegado foi removido com sucesso.';
$labels['deleteerror'] = 'Não foi possível remover o delegado.';
$labels['updatesuccess'] = 'O delegado foi atualizado com sucesso.';
$labels['updateerror'] = 'Não foi possível atualizar o delegado';
$labels['createsuccess'] = 'O delegado foi adicionado com sucesso.';
$labels['createerror'] = 'Não foi possível adicionar o delegado';
?>
