<?php
/**
 * Localizations for the Kolab Delegation plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_delegation/
 */
$labels['mail'] = 'Email';
$labels['contact'] = 'Livro de Contactos';
$labels['event'] = 'Calendários';
$labels['task'] = 'Tarefas';
$labels['note'] = 'Notas';
$labels['savingdata'] = 'Salvando dados...';
?>
