<?php
/**
 * Localizations for the Kolab Delegation plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_delegation/
 */
$labels['tabtitle'] = 'Делегирование';
$labels['delegationtitle'] = 'Управление представителями';
$labels['delegates'] = 'Представители';
$labels['delegate'] = 'Представитель';
$labels['mail'] = 'Почта';
$labels['contact'] = 'Адресные книги';
$labels['event'] = 'Календари';
$labels['task'] = 'Задачи';
$labels['note'] = 'Заметки';
$labels['yes'] = 'Да';
$labels['no'] = 'Нет';
$labels['read'] = 'Только для чтения';
$labels['write'] = 'Запись';
$labels['adddelegate'] = 'Добавить представителя';
$labels['deletedelegate'] = 'Исключить из представителей';
$labels['savingdata'] = 'Сохранение данных...';
$labels['delegatedeleteconfirm'] = 'Вы действительно хотите исключить этого пользователя из представителей?';
$labels['delegateremoveacl'] = 'удалить права на доступ к каталогам назначенные этому пользователю';
$labels['deleteconfirm'] = 'Подтверждение';
$labels['deletesuccess'] = 'Пользователь успешно исключён из представителей.';
$labels['deleteerror'] = 'Не удалось исключить представителя.';
$labels['updatesuccess'] = 'Представитель был успешно обновлён.';
$labels['updateerror'] = 'Не удалось обновить представителя.';
$labels['createsuccess'] = 'Представитель успешно добавлен.';
$labels['createerror'] = 'Не удалось добавить представителя.';
$labels['arialabeldelegatedelete'] = 'Диалог удаления представителей';
$labels['arialabeldelegateform'] = 'Диалог свойств представителей';
?>
