<?php
/**
 * Localizations for the Kolab Delegation plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_delegation/
 */
$labels['tabtitle'] = 'Prenos nalog';
$labels['delegationtitle'] = 'Uredi sodelujoče';
$labels['delegates'] = 'Sodelujoči';
$labels['delegate'] = 'Sodelujoč';
$labels['mail'] = 'Email';
$labels['contact'] = 'Imeniki';
$labels['event'] = 'Koledarji';
$labels['task'] = 'Naloge';
$labels['note'] = 'Zapiski';
$labels['yes'] = 'Da';
$labels['no'] = 'Ne';
$labels['read'] = 'Samo za branje';
$labels['write'] = 'Zapiši';
$labels['adddelegate'] = 'Dodaj sodelujočega';
$labels['deletedelegate'] = 'Izbriši sodelujočega';
$labels['savingdata'] = 'Shranjujem...';
$labels['delegatedeleteconfirm'] = 'Ali želite potrditi brisanje sodelujočega?';
$labels['delegateremoveacl'] = 'odstrani pravice za dostop do mape za tega uporabnika';
$labels['deleteconfirm'] = 'Potrditev';
$labels['deletesuccess'] = 'Ta sodelujoči je bil uspešno odstranjen.';
$labels['deleteerror'] = 'Napaka. Ne morem odstraniti sodelujočega.';
$labels['updatesuccess'] = 'Stanje sodelujočega je bilo uspešno posodobljeno.';
$labels['updateerror'] = 'Ne morem posodobiti stanja sodelujočega.';
$labels['createsuccess'] = 'Sodelujoči je bil uspešno dodan.';
$labels['createerror'] = 'Ne morem dodati sodelujočega.';
$labels['arialabeldelegatedelete'] = 'Izbrisani dogodki s sodelujočim';
$labels['arialabeldelegateform'] = 'Obrazec za nastavitve sodelujočih';
?>
