<?php
/**
 * Localizations for the Kolab Delegation plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_delegation/
 */
$labels['tabtitle'] = 'การมอบหมายงาน';
$labels['delegationtitle'] = 'การจัดการการมอบหมายงาน';
$labels['mail'] = 'อีเมล์';
$labels['contact'] = 'สมุดรายชื่อ';
$labels['event'] = 'ปฎิทิน';
$labels['task'] = 'งาน';
$labels['note'] = 'บันทึก';
$labels['yes'] = 'ใช่';
$labels['no'] = 'ไม่';
$labels['read'] = 'อ่านเท่านั้น';
$labels['write'] = 'เขียน';
$labels['adddelegate'] = 'เพิ่ม(ผู้รับ/การ)มอบงาน';
$labels['deletedelegate'] = 'ลบ(ผู้รับ/การ)มอบงาน';
$labels['savingdata'] = 'บันทึกข้อมูล';
$labels['delegatedeleteconfirm'] = 'คุณแน่ใจว่าต้องการยกเลิก(ผู้รับ/การ)มอบงานนี้หรือ';
$labels['delegateremoveacl'] = 'ยกเลิกสิทธิการเข้าถึงแฟ้มของผู้ใช้รายนี้';
$labels['deleteconfirm'] = 'การยืนยัน';
$labels['deletesuccess'] = '(ผู้รับ/การ)มอบงานถูกลบเรียบร้อยแล้ว';
$labels['deleteerror'] = 'ไม่สามารถลบการมอบหมายงานได้';
$labels['updatesuccess'] = '(ผู้รับ/การ)มอบงานถูกปรับปรุงเรียบร้อยแล้ว';
$labels['updateerror'] = 'ไม่สามารถปรับปรุง(ผู้รับ/การ)มอบงานได้';
$labels['createsuccess'] = '(ผู้รับ/การ)มอบงานถูกเพิ่มเรียบร้อยแล้ว';
$labels['createerror'] = 'ไม่สามารถเพิ่ม(ผู้รับ/การ)มอบงานได้';
?>
