<?php
/**
 * Localizations for the Kolab Delegation plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_delegation/
 */
$labels['delegates'] = 'Представники';
$labels['delegate'] = 'Представник';
$labels['mail'] = 'Пошта';
$labels['contact'] = 'Адресні книги';
$labels['event'] = 'Календарі';
$labels['task'] = 'Задачі';
$labels['note'] = 'Нотатки';
$labels['yes'] = 'Так';
$labels['no'] = 'Ні';
$labels['read'] = 'Тільки для читання';
$labels['write'] = 'Запис';
$labels['adddelegate'] = 'Додати представника';
$labels['deletedelegate'] = 'Вилучити представника';
$labels['savingdata'] = 'Збереження даних...';
$labels['deleteconfirm'] = 'Підтвердження';
?>
