<?php
/**
 * Localizations for the Kolab Tags plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_tags/
 */
$labels['tags'] = 'Značky';
$labels['unset'] = 'Odznačit vše';
$labels['manage'] = 'Spravovat značky...';
$labels['tagactions'] = 'Označit činnosti...';
$labels['tagadd'] = 'Označit jako...';
$labels['tagremove'] = 'Odstranit značku...';
$labels['untag'] = 'Odstranit značku';
$labels['tagremoveall'] = 'Odstranit všechny značky';
$labels['add'] = 'Přidat';
$labels['edit'] = 'Upravit';
$labels['delete'] = 'Smazat';
$labels['tagname'] = 'Název';
$labels['tagcolor'] = 'Barva';
$labels['nameempty'] = 'Název značky nemůže být prázdný!';
$labels['nameexists'] = 'Značka s daným názvem již je!';
$labels['colorinvalid'] = 'Neplatné stanovení barvy!';
$labels['saving'] = 'Ukládají se data...';
$labels['updatesuccess'] = 'Značky byly úspěšně aktualizovány.';
$labels['updateerror'] = 'Nepodařilo se aktualizovat značky - klíčová slova.';
$labels['taggingsuccess'] = 'Značky byly úspěšně přiřazeny.';
$labels['taggingerror'] = 'Nepodařilo se přiřadit značky.';
$labels['untaggingsuccess'] = 'Značka (značky) byly úspěšně odstraněny.';
$labels['untaggingerror'] = 'Nepodařilo se odstranit přiřazení značek.';
