<?php
/**
 * Localizations for the Kolab Tags plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_tags/
 */
$labels['tags'] = 'Mærker';
$labels['unset'] = 'Fravælg alle';
$labels['manage'] = 'Administrér mærker...';
$labels['tagactions'] = 'Afmærk handlinger...';
$labels['tagadd'] = 'Markér som...';
$labels['tagremove'] = 'Fjern mærke...';
$labels['untag'] = 'Fjern mærke';
$labels['tagremoveall'] = 'Fjern alle mærker';
$labels['add'] = 'Tilføj';
$labels['edit'] = 'Redigér';
$labels['delete'] = 'Slet';
$labels['tagname'] = 'Navn';
$labels['tagcolor'] = 'Farve';
$labels['nameempty'] = 'Navn på mærke må ikke stå tomt!';
$labels['nameexists'] = 'Afmærkning med det angivne navn findes allerede!';
$labels['colorinvalid'] = 'Ugyldig specifikation af farve!';
$labels['saving'] = 'Gemmer data...';
$labels['updatesuccess'] = 'Opdateringen af mærkerne er blevet gennemført.';
$labels['updateerror'] = 'Mislykkedes med at opdatere information om mærker.';
$labels['taggingsuccess'] = 'Tildelingen af mærkerne er blevet gennemført.';
$labels['taggingerror'] = 'Mislykkedes med at tildele mærkerne.';
$labels['untaggingsuccess'] = 'Fjernelse af mærke(r) er blevet gennemført.';
$labels['untaggingerror'] = 'Mislykkedes med at fjerne tildelingen af mærkerne.';
