<?php
/**
 * Localizations for the Kolab Tags plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_tags/
 */
$labels['tags'] = 'Schlagworte';
$labels['unset'] = 'Alle abwählen';
$labels['manage'] = 'Schlagworte verwalten...';
$labels['tagactions'] = 'Schlagwort Aktion...';
$labels['tagadd'] = 'Vergebe Schlagwort...';
$labels['tagremove'] = 'Entferne Schlagwort..';
$labels['untag'] = 'Entferne Schlagwort';
$labels['tagremoveall'] = 'Entferne alle Schlagworte';
$labels['add'] = 'Hinzufügen';
$labels['edit'] = 'Bearbeiten';
$labels['delete'] = 'Löschen';
$labels['tagname'] = 'Name';
$labels['tagcolor'] = 'Farbe';
$labels['nameempty'] = 'Schlagwort kann nicht leer sein!';
$labels['nameexists'] = 'Das Schlagwort existiert bereits';
$labels['colorinvalid'] = 'Ungültige Farbangabe';
$labels['saving'] = 'Speichere...';
$labels['updatesuccess'] = 'Schlagworte wurden erfolgreich aktualisiert.';
$labels['updateerror'] = 'Schlagworte konnten nicht aktualisiert werden.';
$labels['taggingsuccess'] = 'Schlagwort wurde erfolgreich zugewiesen.';
$labels['taggingerror'] = 'Konnte Schlagwort nicht zuweisen.';
$labels['untaggingsuccess'] = 'Schlagwort(e) wurden erfolgreich entfernt.';
$labels['untaggingerror'] = 'Schlagwort konnte nicht entfernt werden.';
$labels['newtag'] = 'Neues Schlagwort';
$labels['tagsearchnew'] = 'Text eingeben zur Suche oder für die Anlage eines neuen Schlagworts';
