<?php
/**
 * Localizations for the Kolab Tags plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_tags/
 */
$labels['tags'] = 'Ετικέτες';
$labels['unset'] = 'Αναίρεση επιλογής όλων';
$labels['tagremove'] = 'Αφαίρεση ετικέτας...';
$labels['untag'] = 'Αφαίρεση ετικέτας';
$labels['add'] = 'Προσθήκη';
$labels['edit'] = 'Επεξεργασία';
$labels['delete'] = 'Διαγραφή';
$labels['tagname'] = 'Όνομα';
$labels['tagcolor'] = 'Χρώμα';
$labels['saving'] = 'Αποθήκευση δεδομένων...';
