<?php
/**
 * Localizations for the Kolab Tags plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_tags/
 */
$labels['tags'] = 'Etiquetas';
$labels['unset'] = 'Deseleccionar todo';
$labels['manage'] = 'Administrar etiquetas...';
$labels['tagactions'] = 'Acciones de etiquetas...';
$labels['tagadd'] = 'Etiquetar como...';
$labels['tagremove'] = 'Eliminar etiqueta...';
$labels['untag'] = 'Eliminar etiqueta';
$labels['tagremoveall'] = 'Eliminar todas las etiquetas';
$labels['add'] = 'Agregar';
$labels['edit'] = 'Editar';
$labels['delete'] = 'Eliminar';
$labels['tagname'] = 'Nombre';
$labels['tagcolor'] = 'Color';
$labels['nameempty'] = '¡El nombre de la etiqueta no puede estar vacío!';
$labels['nameexists'] = '¡Ya existe una etiqueta con el nombre especificado!';
$labels['colorinvalid'] = '¡Especificación de color incorrecta!';
$labels['saving'] = 'Guardando...';
$labels['updatesuccess'] = 'Las etiquetas han sido actualizadas exitosamente.';
$labels['updateerror'] = 'Fallo al actualizar la información de las etiquetas';
$labels['taggingsuccess'] = 'Las etiquetas han sido asignadas exitosamente.';
$labels['taggingerror'] = 'Fallo al asignar etiquetas.';
$labels['untaggingsuccess'] = 'Una o más etiquetas han sido eliminadas exitosamente.';
$labels['untaggingerror'] = 'Fallo al eliminar asignaciones de etiquetas.';
$labels['newtag'] = 'Nueva etiqueta';
$labels['tagsearchnew'] = 'Ingrese el texto a buscar o cree una nueva etiqueta';
