<?php
/**
 * Localizations for the Kolab Tags plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_tags/
 */
$labels['tags'] = 'Etiquetas';
$labels['unset'] = 'Desmarcar todos';
$labels['manage'] = 'Gestionar tareas...';
$labels['tagactions'] = 'Etiquetar acciones...';
$labels['tagadd'] = 'Etiquetar como...';
$labels['tagremove'] = 'Eliminar etiqueta...';
$labels['untag'] = 'Eliminar etiqueta';
$labels['tagremoveall'] = 'Eliminar todas las etiquetas';
$labels['add'] = 'Añadir';
$labels['edit'] = 'Editar';
$labels['delete'] = 'Borrar';
$labels['tagname'] = 'Nombre';
$labels['tagcolor'] = 'Color';
$labels['nameempty'] = 'El nombre de la etiqueta no puede estar vacío';
$labels['nameexists'] = 'Marcado con un nombre específicado que ya existe';
$labels['colorinvalid'] = 'Especificación del color inválida';
$labels['saving'] = 'Guardando datos...';
$labels['updatesuccess'] = 'Se han actualizado las etiquetas con éxito.';
$labels['updateerror'] = 'Error al actualizar la información de las etiquetas';
$labels['taggingsuccess'] = 'Se han asignado las etiquetas con éxito.';
$labels['taggingerror'] = 'Error al asignar los datos.';
$labels['untaggingsuccess'] = 'Se han eliminado las etiquetas con éxito.';
$labels['untaggingerror'] = 'No se pudieron eliminar las asignaciones de etiquetas';
$labels['newtag'] = 'Etiqueta nueva';
$labels['tagsearchnew'] = 'Introduzca un texto para buscar o crear una etiqueta nueva';
