<?php
/**
 * Localizations for the Kolab Tags plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_tags/
 */
$labels['tags'] = 'Tunnisteet';
$labels['unset'] = 'Älä valitse mitään';
$labels['manage'] = 'Hallitse tunnisteita...';
$labels['tagactions'] = 'Tunnistetoiminnot...';
$labels['tagadd'] = 'Merkitse tunnisteella...';
$labels['tagremove'] = 'Poista tunniste...';
$labels['untag'] = 'Poista tunniste';
$labels['tagremoveall'] = 'Poista kaikki tunnisteet';
$labels['add'] = 'Lisää';
$labels['edit'] = 'Muokkaa';
$labels['delete'] = 'Poista';
$labels['tagname'] = 'Nimi';
$labels['tagcolor'] = 'Väri';
$labels['nameempty'] = 'Tunnisteen nimi ei voi olla tyhjä!';
$labels['nameexists'] = 'Samalla nimellä on jo olemassa tunniste!';
$labels['colorinvalid'] = 'Virheellinen värimääritys!';
$labels['saving'] = 'Tallennetaan tietoja...';
$labels['updatesuccess'] = 'Tunnisteet on päivitetty onnistuneesti.';
$labels['updateerror'] = 'Tunnistetietojen päivittäminen epäonnistui.';
$labels['taggingsuccess'] = 'Tunnisteet on asetettu onnistuneesti.';
$labels['taggingerror'] = 'Tunnisteiden asettaminen epäonnistui.';
$labels['untaggingsuccess'] = 'Tunnisteet on poistettu onnistuneesti.';
$labels['newtag'] = 'Uusi tunniste';
$labels['tagsearchnew'] = 'Kirjoita haettava teksti tai luo uusi tunniste';
