<?php
/**
 * Localizations for the Kolab Tags plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_tags/
 */
$labels['tags'] = 'Étiquettes';
$labels['unset'] = 'Tout désélectionner';
$labels['manage'] = 'Gestion des étiquettes...';
$labels['tagactions'] = 'Actions étiquette...';
$labels['tagadd'] = 'Étiqueter en tant que...';
$labels['tagremove'] = 'Supprimer l\'étiquette...';
$labels['untag'] = 'Supprimer l\'étiquette';
$labels['tagremoveall'] = 'Supprimer toutes les étiquettes';
$labels['add'] = 'Ajouter';
$labels['edit'] = 'Modifier';
$labels['delete'] = 'Supprimer';
$labels['tagname'] = 'Nom';
$labels['tagcolor'] = 'Couleur';
$labels['nameempty'] = 'Le nom d\'une étiquette ne peut être vide !';
$labels['nameexists'] = 'Une étiquette portant ce nom existe déjà !';
$labels['colorinvalid'] = 'Code couleur invalide !';
$labels['saving'] = 'Enregistrer...';
$labels['updatesuccess'] = 'L\'étiquette a été modifiée avec succès.';
$labels['updateerror'] = 'Impossible de mettre à jour les informations de l\'étiquette.';
$labels['taggingsuccess'] = 'Les étiquettes ont été affectées avec succès.';
$labels['taggingerror'] = 'Impossible d\'affecter les étiquettes.';
$labels['untaggingsuccess'] = 'Étiquette(s) supprimée(s) avec succès.';
$labels['untaggingerror'] = 'Impossible de supprimer les affectations.';
$labels['newtag'] = 'Nouvelle balise';
$labels['tagsearchnew'] = 'Entrez votre texte afin de chercher ou créez une nouvelle balise';
