<?php
/**
 * Localizations for the Kolab Tags plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_tags/
 */
$labels['tags'] = 'Etichette';
$labels['add'] = 'Aggiungi';
$labels['edit'] = 'Modifica';
$labels['delete'] = 'Elimina';
$labels['tagname'] = 'Nome';
$labels['tagcolor'] = 'Colore';
$labels['saving'] = 'Salvataggio dati...';
