<?php
/**
 * Localizations for the Kolab Tags plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_tags/
 */
$labels['tags'] = 'タグ';
$labels['unset'] = '全選択解除';
$labels['manage'] = 'タグの管理';
$labels['tagactions'] = 'タグの動作…';
$labels['tagadd'] = 'タグの種類';
$labels['tagremove'] = 'タグの削除…';
$labels['untag'] = 'タグを削除';
$labels['tagremoveall'] = '全タグの削除';
$labels['add'] = '追加';
$labels['edit'] = '編集';
$labels['delete'] = '削除';
$labels['tagname'] = '名前';
$labels['tagcolor'] = '色';
$labels['nameempty'] = 'タグには必ず名前が必要です!';
$labels['nameexists'] = '指定された名前のタグはすでにあります!';
$labels['colorinvalid'] = '無効な色の指定です!';
$labels['saving'] = 'データを保存中…';
$labels['updatesuccess'] = 'タグの更新に成功しました。';
$labels['updateerror'] = 'タグ情報の更新に失敗しました。';
$labels['taggingsuccess'] = 'タグの割当に成功しました。';
$labels['taggingerror'] = 'タグの割当に失敗しました。';
$labels['untaggingsuccess'] = 'タグ(s)の削除に成功しました。';
$labels['untaggingerror'] = 'タグ割当の削除に失敗しました。';
