<?php
/**
 * Localizations for the Kolab Tags plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_tags/
 */
$labels['tags'] = 'Tags';
$labels['unset'] = 'Alle selecties opheffen';
$labels['manage'] = 'Tags beheren...';
$labels['tagactions'] = 'Tagacties...';
$labels['tagadd'] = 'Taggen als...';
$labels['tagremove'] = 'Tag verwijderen...';
$labels['untag'] = 'Tag verwijderen';
$labels['tagremoveall'] = 'Alle tags verwijderen';
$labels['add'] = 'Toevoegen';
$labels['edit'] = 'Bewerken';
$labels['delete'] = 'Verwijderen';
$labels['tagname'] = 'Naam';
$labels['tagcolor'] = 'Kleur';
$labels['nameempty'] = 'Tagnaam mag niet leeg zijn!';
$labels['nameexists'] = 'Tag met opgegeven naam bestaat al!';
$labels['colorinvalid'] = 'Ongeldige kleurspecificatie!';
$labels['saving'] = 'Gegevens opslaan...';
$labels['updatesuccess'] = 'Tags zijn met succes bijgewerkt.';
$labels['updateerror'] = 'Bijwerken van taginformatie is mislukt.';
$labels['taggingsuccess'] = 'Tags zijn met succes toegewezen.';
$labels['taggingerror'] = 'Toewijzen van tags is mislukt.';
$labels['untaggingsuccess'] = 'Tag(s) met succes verwijderd.';
$labels['untaggingerror'] = 'Verwijderen van toegewezen tags is mislukt.';
$labels['newtag'] = 'Nieuwe tag';
$labels['tagsearchnew'] = 'Voer tekst in die u wilt zoeken of maak een nieuwe tag';
