<?php
/**
 * Localizations for the Kolab Tags plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_tags/
 */
$labels['tags'] = 'Etiquetas';
$labels['add'] = 'Adicionar';
$labels['edit'] = 'Editar';
$labels['delete'] = 'Deletar';
$labels['tagname'] = 'Nome';
$labels['tagcolor'] = 'Cor';
$labels['saving'] = 'Salvando dados...';
