<?php
/**
 * Localizations for the Kolab Tags plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_tags/
 */
$labels['tags'] = 'Теги';
$labels['unset'] = 'Снять все выделения';
$labels['manage'] = 'Управление тегами...';
$labels['tagactions'] = 'Действия с тегами...';
$labels['tagadd'] = 'Назначить тег...';
$labels['tagremove'] = 'Снять тег...';
$labels['untag'] = 'Удалить тег';
$labels['tagremoveall'] = 'Удалить все теги';
$labels['add'] = 'Добавить';
$labels['edit'] = 'Редактировать';
$labels['delete'] = 'Удалить';
$labels['tagname'] = 'Имя';
$labels['tagcolor'] = 'Цвет';
$labels['nameempty'] = 'Тег не может быть пустым!';
$labels['nameexists'] = 'Тег с указанным именем уже существует!';
$labels['colorinvalid'] = 'Неверное указание цвета!';
$labels['saving'] = 'Сохранение данных...';
$labels['updatesuccess'] = 'Теги успешно обновлены.';
$labels['updateerror'] = 'Не удалось обновить информацию о тегах.';
$labels['taggingsuccess'] = 'Теги успешно назначены.';
$labels['taggingerror'] = 'Не удалось назначить теги.';
$labels['untaggingsuccess'] = 'Тег(и) успешно убраны.';
$labels['untaggingerror'] = 'Не удалось снять назначенные теги.';
$labels['newtag'] = 'Новый тег';
$labels['tagsearchnew'] = 'Введите текст для поиска или создания тега';
