<?php
/**
 * Localizations for the Kolab Tags plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_tags/
 */
$labels['tags'] = 'Tagi';
$labels['unset'] = 'Odznači vse';
$labels['manage'] = 'Uredi tage...';
$labels['tagactions'] = 'Možnosti taga...';
$labels['tagadd'] = 'Označi kot tag...';
$labels['tagremove'] = 'Odstrani tag...';
$labels['untag'] = 'Odstrani tag';
$labels['tagremoveall'] = 'Odstrani vse tage';
$labels['add'] = 'Dodaj';
$labels['edit'] = 'Uredi';
$labels['delete'] = 'Izbriši';
$labels['tagname'] = 'Ime';
$labels['tagcolor'] = 'Barva';
$labels['nameempty'] = 'Ime taga ne more biti prazno!';
$labels['nameexists'] = 'Tag z izbranim imenom že obstaja!';
$labels['colorinvalid'] = 'Napačna izbira barve!';
$labels['saving'] = 'Shranjujem...';
$labels['updatesuccess'] = 'Tagi so bili uspešno posodobljeni.';
$labels['updateerror'] = 'Napaka. Posodabljanje tagov ni uspelo.';
$labels['taggingsuccess'] = 'Tagi so bili uspešno dodeljeni.';
$labels['taggingerror'] = 'Napaka. Tagi niso bili dodeljeni.';
$labels['untaggingsuccess'] = 'Tag(i) so bili uspešno odstranjeni.';
$labels['untaggingerror'] = 'Napaka. Tagi nalog niso bili odstranjeni.';
