<?php
/**
 * Localizations for the Kolab Tags plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_tags/
 */
$labels['tags'] = 'แท็ก';
$labels['unset'] = 'ยกเลิกการเลือกทั้งหมด';
$labels['manage'] = 'จัดการ แท็ก...';
$labels['tagremove'] = 'ยกเลิก แท็ก...';
$labels['untag'] = 'ยกเลิกแท็ก';
$labels['tagremoveall'] = 'ยกเลิกแท็กทั้งหมด';
$labels['add'] = 'เพิ่ม';
$labels['edit'] = 'แก้ไข';
$labels['delete'] = 'ลบ';
$labels['tagname'] = 'ชื่อ';
$labels['tagcolor'] = 'สี';
$labels['nameempty'] = 'ชื่อของแท็กต้องไม่ว่างเปล่า';
$labels['nameexists'] = 'แท็กชื่อนี้มีอยู่แล้ว';
$labels['colorinvalid'] = 'ข้อมูลสีไม่ถูกต้อง';
$labels['saving'] = 'กำลังจัดเก็บข้อมูล...';
$labels['updatesuccess'] = 'แท็กถูกปรับปรุงเรียบร้อยแล้ว';
$labels['updateerror'] = 'การปรับปรุงข้อมูลแท็กล้มเหลว';
$labels['taggingsuccess'] = 'การติดตั้งแท็กเรียบร้อยแล้ว';
$labels['taggingerror'] = 'การติดตั้งแท็กล้มเหลว';
$labels['untaggingsuccess'] = 'แท็กถูกลบเรียบร้อยแล้ว';
