<?php

/**
 * Localizations for the WPA Clien plugin
 *
 * Copyright (C) 2016, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/wpa_client/
 */

$labels['accountoptions'] = 'Account options';
$labels['accounttype'] = 'Account type';
$labels['failedtypedetection'] = 'Failed to retrieve account type.';
$labels['failedtypeupdate'] = 'Failed to change account type.';
